feat/landing-second-step
atls-academy/Mirved64.github.io pull request #11
Opened 2023-07-17 12:44 UTC by Mirved64

Close #10

2023-07-18 17:17 UTC, TorinAsakura requested changes
Разберись с семантикой. Выглядит уже на порядки лучше

2023-07-18 17:17 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/card-small/card-small.component.tsx
> +  <Box flexBasis={[260, 560]} display={[mobile!, desktop!]} flexShrink='0'>
зачем ты используешь операнды "!" в display?

2023-07-18 17:17 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/card-small/card-small.component.tsx
> +        <Box>
зачем пустой див когда у тебя уже есть один? Я понимаю будь у тебя тут сетка или роу/каламн

2023-07-18 17:17 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/card-small/card-small.component.tsx
> +        <Box>
Обрати внимание на markup в каждом примере https://getuikit.com/docs/grid

2023-07-18 17:17 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards-big/cards-big.component.tsx
> +    <Column>
зачем?

2023-07-18 17:17 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards-big/cards-big.component.tsx
> +            <Box>
опять

2023-07-18 17:17 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +import { CardSmall } from './card-small'
почему ты создаёшь новые компоненты только на основе их отличий по модификатору размера? Может начнём создавать компоненты кнопок на каждый пропс?

2023-07-18 17:44 UTC, Mirved64 commented on landing/fragments/landing-courses/src/cards/card-small/card-small.component.tsx
> +  <Box flexBasis={[260, 560]} display={[mobile!, desktop!]} flexShrink='0'>
@TorinAsakura без них ts ругается, т.к. может быть undefined. Так я обозначаю, что не будет значения undefined

2023-07-18 17:55 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/card-small/card-small.component.tsx
> +  <Box flexBasis={[260, 560]} display={[mobile!, desktop!]} flexShrink='0'>
> @TorinAsakura без них ts ругается, т.к. может быть undefined. Так я обозначаю, что не будет значения undefined

не может быть, а посмотри-ка как у Оксаны сделано и потом запусти её код

2023-07-19 06:40 UTC, Mirved64 commented on landing/fragments/landing-courses/src/cards/cards-big/cards-big.component.tsx
> +    <Column>
@TorinAsakura 

Здесь я оборачиваю в `Column` большую карточку (Фронтэнд и Мини курс). Пока нет стилизации у карточек, решил оставить `Column` и позже заменить на `Box` и задать `background-color`

2023-07-19 14:08 UTC, TorinAsakura requested changes

2023-07-19 14:08 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards-learning-and-courses/cards-learning-and-coursess.component.tsx
> +export const CardsLearningAndCoursess = () => (
Просто cards, они же внутри фрагмента…

2023-07-19 14:08 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards-learning-and-courses/cards-learning-and-coursess.component.tsx
> +    <Box flexDirection='column'>
я не понимаю зачем тебе колонна с шириной в 100% и зачем тебе потом див из которого ты делаешь такую же колонну…

2023-07-19 14:08 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards-learning-and-courses/cards-learning-and-coursess.component.tsx
> +    <Box flexDirection='column'>
А почему не <Column>?

2023-07-19 14:08 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards-learning-and-courses/index.ts
> +export * from './cards-learning-and-coursess.component'
Courses

2023-07-19 14:08 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +import { CardsLearningAndCoursess } from './cards-learning-and-courses'
Абсолютно очевидно, что это один и тот же компонент, который ты зачем-то копипастишь, отличием которого при разных сценариях является размер. Так может вынести его в компоненты и просто переиспользовать?

2023-07-19 14:08 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +        <Column flexBasis={[335, 1610]} flexGrow='1' margin='0 auto'>
зачем ты используешь центрирование через марджин? У флексов нет для этого никаких средств?

2023-07-19 14:08 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/hero.component.tsx
> +              />
Что ты делаешь?Зачем ты создал такую громоздкую конструкцию? Зачем ты сделал ссылку свойством кнопки?

2023-07-19 14:20 UTC, Mirved64 commented on landing/fragments/landing-courses/src/cards/cards-learning-and-courses/cards-learning-and-coursess.component.tsx
> +    <Box flexDirection='column'>
колонна, которая занимает 100% родителя
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/5b47f529-8787-46bd-a4a7-c53442ae15b0)
в ней два бокса-колонны 
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/cc4c2dba-7649-4757-9854-76f445b66bb6)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/3aed59b7-bf2a-41ef-b626-3b97bf5f42a7)
боксы, потому что в следующем шаге задавать бекграунд им, т.е. стилизовать

2023-07-19 14:33 UTC, Mirved64 commented on landing/fragments/landing-hero/src/hero.component.tsx
> +              />
я вынес в пропсы `icon`, `widthIcon`, `heightIcon` чтобы управлять иконками в кнопках. С ссылкой погорячился.

2023-07-19 19:52 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards-learning-and-courses/cards-learning-and-coursess.component.tsx
> +    <Box flexDirection='column'>
Так может тебе нужен роу, а не колонна, судя по направлению блоков, который я вижу? А высоту они и так получат за счёт расширения

2023-07-19 19:53 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/cards-big/cards-big.component.tsx
> +    <Column>
Так почему сразу не использовать бокс? Тебе-то какая разница?

2023-07-20 22:37 UTC, TorinAsakura requested changes

2023-07-20 22:37 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/cards/card.factory.tsx
> +import React      from 'react'
зачем ты используешь тут факторию? Тебе нужно сделать ui компонент и положить его в папку к остальным UI компонентам. Что ты делаешь?

2023-07-21 22:33 UTC, TorinAsakura requested changes
Посмотри как оформляются компоненты. Если не понятно - можно созвониться.

2023-07-23 22:43 UTC, TorinAsakura requested changes
Всё ты никак с карточками не разберёшься. Ещё раз: компонент - это тупая визуальная сущность, просто кусок отвечающий за рендер себя любимого, все частности типа курсов, миникурсов и прочих переменных - выносятся в частную область проекта. Ну вот скажи, завтра я тебе скажу сделать ещё с пяток страниц где будут другие курсы, что, будешь под каждый курс делать дочернюю сущность для карточки? Прекращай.

2023-07-24 08:57 UTC, Mirved64 commented
> Всё ты никак с карточками не разберёшься. Ещё раз: компонент - это тупая визуальная сущность, просто кусок отвечающий за рендер себя любимого, все частности типа курсов, миникурсов и прочих переменных - выносятся в частную область проекта. Ну вот скажи, завтра я тебе скажу сделать ещё с пяток страниц где будут другие курсы, что, будешь под каждый курс делать дочернюю сущность для карточки? Прекращай.

@TorinAsakura 

Другими словами, `ui/card` должен отрисовывать стилизованный контейнер? И используем его в компоненте `fragments/sources/courses.component.tsx` как обертку, плюсом компоненту приписываем пропсы, для конкретного места макета?

Вот [здесь](https://github.com/atls/convention/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-UI#%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4) прочитал. Я правильно понял? 

Если не так, то прошу созвониться.

2023-07-24 09:00 UTC, TorinAsakura commented
@Mirved64 Браво. Именно так. Жаль, что ты единственный, кто прочёл это. Всё ещё не понятно для кого писал. Повторюсь - следуйте конвенции, я её не просто так писал.

2023-07-24 12:50 UTC, Mirved64 commented
@TorinAsakura 

Сделал `ui/card` по сути `Box` занимающий всего родителя и меняющий курсор на поинтер. Пока такие стили, в следующих степах буду добавлять.

Теперь не могу понять куда вставлять кастомные карточки, т.е. три вида карточек проекта (курсы, миникурсы, материалы) уже с версткой. 

Создавать директорию `landing/fragments/sources` куда уже поместить директории кастомных карточек? И от туда импортировать в `landing/fragments/landing-courses/courses.component.tsx` как элементы `CardCourse`, `CardMiniCourse`, `CardMaterials` и вставлять уже контент в них?
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/665a3a40-b026-4921-a281-cd991d460b97)

2023-07-24 12:51 UTC, TorinAsakura commented
> @TorinAsakura
> 
> Сделал `ui/card` по сути `Box` занимающий всего родителя и меняющий курсор на поинтер. Пока такие стили, в следующих степах буду добавлять.
> 
> Теперь не могу понять куда вставлять кастомные карточки, т.е. три вида карточек проекта (курсы, миникурсы, материалы) уже с версткой.
> 
> Создавать директорию `landing/fragments/sources` куда уже поместить директории кастомных карточек? И от туда импортировать в `landing/fragments/landing-courses/courses.component.tsx` как элементы `CardCourse`, `CardMiniCourse`, `CardMaterials` и вставлять уже контент в них? ![image](https://user-images.githubusercontent.com/99605124/255594226-665a3a40-b026-4921-a281-cd991d460b97.png)

1. Что такое sources?
2. Почему оно во фрагментах?

@oksssvv помоги человеку

2023-07-24 15:23 UTC, Mirved64 commented
@TorinAsakura 

**Скоуп**
макет

**Описание**
В макете в карточках в десктопной версии `font-size` и `line-height` у категории, тайтла и текста у всех карточек одинаковые. В мобильной версии  `font-size` и `line-height` у тайтла карточек курса и мини-курса одинаковые, а карточек материалов отличаются на пару пикселей.
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/b48fead3-3970-4b73-a323-233c43958aa1)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/b069ef9b-28c3-443c-a07e-8d740d54394b)

**Вопрос**
Так и должно быть, или же размеры текста в карточках должны быть одинаковы?

2023-07-24 15:35 UTC, TorinAsakura commented
@Mirved64 Делай как в дизайне

2023-07-24 18:25 UTC, TorinAsakura requested changes

2023-07-24 18:25 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +              {titleMobile}
чот я не пойму, а как у тебя тут два заголовка сразу, да ещё и без кондишена?

2023-07-24 18:25 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/card/card.interface.ts
> +  topGap: string | string[] | number | number[]
почитай про реализацию типов, там есть более интересные конструкции, это не критика, это совет, он не блокирует ревью

2023-07-24 18:25 UTC, TorinAsakura commented on ui/card/src/backdrop/backdrop.component.tsx
> +export const Backdrop = styled(Box)(baseBackdropStyles)
откуда у карточки бэкдроп? ничего не понимаю

2023-07-24 18:25 UTC, TorinAsakura commented on ui/card/src/backdrop/backdrop.styles.ts
> +  cursor: 'pointer',
господь! зачем? у тебя просто карточка должна быть обёрнута в ссылку! какой смысл делать поинтер если, скажем, ссылки нет?

2023-07-24 18:33 UTC, Mirved64 commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +              {titleMobile}
Пропсами displayTitle

2023-07-24 18:34 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +              {titleMobile}
> Пропсами displayTitle

так я и спрашиваю - зачем? Если есть condition? Что за костыли-то?

2023-07-24 18:36 UTC, Mirved64 commented on ui/card/src/backdrop/backdrop.styles.ts
> +  cursor: 'pointer',
Ну тут я на этом степе просто добавил в стиль поинтер, чтобы хоть чем-то отличались от бокса

2023-07-25 15:59 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +          <Condition match={!isMobailOnly}>
Mobail -> Mobile

2023-07-25 16:00 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +                {titleMobile}
а тут нормально, втф?) вас там двое чтоли сидит?

2023-07-25 16:04 UTC, TorinAsakura requested changes

2023-07-25 16:04 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +                  gap={126}
что за гапы? все отступы регулируются базисами как и всегда

2023-07-25 16:08 UTC, Mirved64 commented on landing/fragments/landing-courses/src/courses.component.tsx
> +                  gap={126}
@TorinAsakura 

эти пропсы регулируют флексбазисы лейаутов в карточке. переименовать?

2023-07-25 16:10 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +                  gap={126}
нет, это чёрный ящик, базисы должны быть явными как и везде

2023-07-25 16:36 UTC, oxiqod commented on landing/fragments/landing-courses/src/courses.component.tsx
> +                  gap={126}
@Mirved64 
12 пропсов - эт мощно
ненужно передавать в карточку всё подряд, посмотри на макет, на все карточки (у нас их всего 2)) 
в чем их отличие? 
- разве флексБазисы в лэйаутах разные? десктоп 40, мобайл 16 
- а ширина будет зависеть от ширины вьюпорта, если у тебя мало места - то карточка сжимается
- если много - то на всю катушку

2023-07-25 16:42 UTC, oksssvv commented on landing/fragments/landing-courses/src/courses.component.tsx
> +                  gap={126}
@Mirved64 
что вынудило тебя обложить карточку пропсами? верстка не слушалась?
лично я когда делалая этот этап давала бг для карты, что бы было нагляднее ее состояние при рендере 
(т.к. там мало что понятно без цвета, отступ не отступ и т.д)

2023-07-25 16:45 UTC, Mirved64 commented on landing/fragments/landing-courses/src/courses.component.tsx
> +                  gap={126}
> @Mirved64 12 пропсов - эт мощно ненужно передавать в карточку всё подряд, посмотри на макет, на все карточки (у нас их всего 2)) в чем их отличие?
> 
> * разве флексБазисы в лэйаутах разные? десктоп 40, мобайл 16
> * а ширина будет зависеть от ширины вьюпорта, если у тебя мало места - то карточка сжимается
> * если много - то на всю катушку

@oksssvv 

Тут я сделал кастомную карточку, которую можно настроить и для больших (курс, мини-курс), так и маленькие (учебные материалы). В маленьких карточках еще и размеры шрифта в мобильной версии отличается от размеров шрифта мобилки других карточек (курс, мини-курс).

2023-07-25 17:00 UTC, oksssvv commented
@Mirved64 
>Тут я сделал кастомную карточку, которую можно настроить и для больших (курс, мини-курс), так и маленькие (учебные материалы). В маленьких карточках еще и размеры шрифта в мобильной версии отличается от размеров шрифта мобилки других карточек (курс, мини-курс).

да, ее действительно можно настроить хоть из космоса, ведь у нее 12 пропсов
ты даешь ей жесткие установки отступов еще и флексШринки выставляешь
она должна быть адаптивной, а ты прибиваешь ее размеры гвоздями, у тебя есть пример реализации, никто не запрещает подсмотреть туда

у тебя есть примеры
если прям все объяснить нужно - созвон

2023-07-25 17:05 UTC, Mirved64 commented
> @Mirved64
> 
> > Тут я сделал кастомную карточку, которую можно настроить и для больших (курс, мини-курс), так и маленькие (учебные материалы). В маленьких карточках еще и размеры шрифта в мобильной версии отличается от размеров шрифта мобилки других карточек (курс, мини-курс).
> 
> да, ее действительно можно настроить хоть из космоса, ведь у нее 12 пропсов ты даешь ей жесткие установки отступов еще и флексШринки выставляешь она должна быть адаптивной, а ты прибиваешь ее размеры гвоздями, у тебя есть пример реализации, никто не запрещает подсмотреть туда
> 
> у тебя есть примеры если прям все объяснить нужно - созвон

@oksssvv 

шринки задаю для лейаутов, чтобы они вели себя как паддинги, адаптив за счет части с контентом, он может растягиваться (задал гроу) и сжиматься (шринк по умолчанию).

2023-07-25 18:06 UTC, TorinAsakura commented
@Mirved64 так в том-то и проблема - лэйауты не должны вести себя как падинги, они дают гарантию иммутабельности, а ты ломаешь их задавая гибкости

2023-07-25 18:19 UTC, Mirved64 commented
@TorinAsakura 

Ход моих мыслей с лейаутами такой:
Нельзя пользоваться марджинами и паддингами, значит буду вместо них ставить лейауты и запрещать им менять размеры (т.е. они будут иммутабельны). Растягиваться они, как флекс элементы по умолчанию не могут, а сжиматься запрещу им флексшринком.
Адаптивная верстка будет за счёт изменения размеров контентной части (картинок, иконок, текста и т.д.) блока, её я помещаю в бокс и разрешаю расти (ставлю гроу), а сжиматься она может как флекс элемент по-умолчанию.

2023-07-25 18:20 UTC, TorinAsakura commented
@Mirved64 они и так не смогут сжиматься если родитель имеет установленный базис и направляющие…

2023-07-25 18:20 UTC, TorinAsakura commented
@Mirved64 Воспринимай лэйауты как строительные блоки

2023-07-26 22:25 UTC, TorinAsakura requested changes
Почти финал)

2023-07-26 22:25 UTC, TorinAsakura commented on landing/fragments/landing-about/src/about.component.tsx
>    <Box backgroundColor='background.about' width='100%' flexDirection='column' margin='0 auto'>
зачем тебе тут центрирование через margin? Ну обсуждали же

2023-07-26 22:25 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +  gap,
gap нужен для вёрстки (раскладки) родительских компонентов на странице, а не для вёрстки юай компонентов, не используй его тут

2023-07-26 22:25 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/hero.component.tsx
> +              <NextLink path='https://github.com/'>
path должен ссылаться на внутренние ресурсы, почитай спеку

2023-07-26 22:25 UTC, TorinAsakura commented on package.json
> +    "next": "12.3.4"
старайся делать правки по пакетам, а не через резолюшен, не ленись короче) Я бы понял этот ход, будь у тебя, скажем, ну, 100 пакетов! Тогда да, ну а тут - ручками, ручками

2023-07-26 22:25 UTC, TorinAsakura commented on landing/fragments/landing-technologies/src/item/item.component.tsx
> +    <Box width='48px'>
что это опять такое? вас там точно двое чтоли пишет?

2023-07-26 22:25 UTC, TorinAsakura commented on landing/fragments/landing-technologies/src/item/item.component.tsx
> +    <Box>
видимо это была глобальная автозамена) Иди, правь

2023-07-26 22:25 UTC, TorinAsakura commented on landing/fragments/landing-navigation/src/items-list/items-list.component.tsx
> +        <NextLink key={navLink.id} path={navLink.path} width='100%'>
зачем вы постоянно везде выставляете 100% ширину будто у вас её кто-то украдёт?)

2023-07-26 22:25 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/hero.component.tsx
>              display={['flex', 'none']}
эти вещи решаются через condition, так как эти объекты будут нагружать твой DOM просто скрываясь, я бы на твоём месте периодически подсматривал в другие ревью, которые я провожу, Оксана сейчас на те же грабли наступила

2023-07-26 22:25 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +            <Column>
подумай хорошенько над структурой, выглядит гиперкринжово

2023-07-27 07:31 UTC, Mirved64 commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +  gap,
@TorinAsakura 
Под пропсом `gap` я поставил флекс базис лейаута между категорией и тайтлом.
Переименовать, чтобы не путать с параметром `gap` у флексбоксов?

2023-07-27 07:41 UTC, Mirved64 commented on landing/fragments/landing-navigation/src/items-list/items-list.component.tsx
> +        <NextLink key={navLink.id} path={navLink.path} width='100%'>
@TorinAsakura 

Я ставлю для линков 100% ширины, т.к. без этого, ширина будет зависеть от содержимого.

2023-07-27 09:59 UTC, Mirved64 commented on package.json
> +    "next": "12.3.4"
@TorinAsakura 
не получается по пакетам настроить. 

[Здесь](https://github.com/nolimits4web/swiper/issues/5799) пишут что свайпер требует 17 версию `@types/react`, так я уже и в пакете её везде ставил, и в `.yarnrc.yml` проставлял, но при `typecheck` выдаёт ошибки.

Пробовал другие весии свайпера, все равно не проходит `typecheck`.

В документации к [yarn](https://yarnpkg.com/configuration/yarnrc) нашел про резолюшен.

2023-07-28 18:08 UTC, TorinAsakura requested changes

2023-07-28 18:08 UTC, TorinAsakura commented on landing/fragments/landing-about/src/about.component.tsx
> +  <Box
раздели направляющий и стилизатор, чо в один бокс-то всё напихал?

2023-07-28 18:08 UTC, TorinAsakura commented on landing/fragments/landing-about/src/about.component.tsx
> +      <Layout flexBasis={[20, 230]} flexShrink='0' />
зачем ты везде шринки запрещаешь? что происходит-то?) то есть, если будет разрешение на пару пикселей меньше - у меня начнёт ломаться интерфейс?)

2023-07-28 18:08 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
>      <Box
тож самое

2023-07-28 18:08 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/sidebar/sidebar.component.tsx
> +          <Box display={['none', 'flex']} justifyContent='center'>
кондишн

2023-07-29 07:45 UTC, Mirved64 commented on landing/fragments/landing-about/src/about.component.tsx
> +                    <FormattedMessage id='aboutTextIntroFirstDesktop' />
гитхаб показывает изменения в id, т.к. в самом начале я изменил структуру и код съехал. id не менял! и далее фонтсайзы и прочие токены не менял

2023-07-29 07:45 UTC, Mirved64 commented on landing/fragments/landing-courses/src/courses.component.tsx
> +              <NextLink path='/' width='100%'>
тут тоже из-за изменения в начале код съехал, кондишн не убирал.

2023-07-31 23:18 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +                  letter='-2%'
что это за свойство?

2023-07-31 23:19 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +      <Column width='100%'>
я так и не понял зачем тебе всегда ширина на 100% от контента? Почему не разрешить grow?

2023-07-31 23:21 UTC, TorinAsakura approved these changes
Ну, почти)

2023-07-31 23:21 UTC, TorinAsakura commented on landing/fragments/landing-slider/src/slider.component.tsx
> +            <Row justifyContent='space-between' flexBasis={[335, 960]}>
бестолковая вложенность же

2023-07-31 23:22 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +  gap,
да, тем более gap это grid

2023-07-31 23:23 UTC, TorinAsakura commented on package.json
> +    "next": "12.3.4"
Резолюшен просто выставляет принудительно единую версию на все пакеты, если проблема с зависимостью внутри зависимости - используй packageExtension

2023-08-01 16:01 UTC, Mirved64 commented on package.json
> +    "next": "12.3.4"
@TorinAsakura 

**Скоуп**
Не получается настроить `Swiper`

**Описание**
При настройки библиотеки через `packageExtension`, `Typecheck` все равно ругается. 

**Логи:**
```
➤ YN0000: ┌ Typecheck
➤ YN0000: │ .yarn/unplugged/swiper-virtual-a3c211c4c7/node_modules/swiper/react/swiper-react.d.ts
➤ YN0000: │ 
➤ YN0000: │   Erro: Interface 'SwiperProps' incorrectly extends interface 'Omit<HTMLAttributes<HTMLElement>, "onKeyPress" | "onProgress" | "onClick" | 
➤ YN0000: │       "onDoubleClick" | "onTouchEnd" | "onTouchMove" | "onTouchStart" | "onScroll" | "onTransitionEnd">'.
➤ YN0000: │         Types of property 'onResize' are incompatible.
➤ YN0000: │           Type '((swiper: Swiper) => void) | undefined' is not assignable to type 'ReactEventHandler<HTMLElement> | undefined'.
➤ YN0000: │             Type '(swiper: Swiper) => void' is not assignable to type 'ReactEventHandler<HTMLElement>'.
➤ YN0000: │               Types of parameters 'swiper' and 'event' are incompatible.
➤ YN0000: │                 Type 'SyntheticEvent<HTMLElement, Event>' is missing the following properties from type 'Swiper': params, originalParams, $el, 
➤ YN0000: │       el, and 92 more.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: │ .yarn/unplugged/swiper-virtual-a3c211c4c7/node_modules/swiper/react/swiper-react.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Interface 'SwiperSlideProps' incorrectly extends interface 'HTMLAttributes<HTMLElement>'.
➤ YN0000: │          Types of property 'children' are incompatible.
➤ YN0000: │            Type 'ReactNode | ((slideData: SlideData) => ReactNode)' is not assignable to type 'ReactNode'.
➤ YN0000: │              Type '(slideData: SlideData) => ReactNode' is not assignable to type 'ReactNode'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: └ Completed in 4s 601ms
➤ YN0000: Failed with errors in 4s 601ms
```

**Мои действия:**

- Изучал [репозиторий свайпера](https://github.com/nolimits4web/swiper);
- Изучал [документацию свайпера](https://swiperjs.com/react);
- Изучил репозитории примеры, в том числе [драм-ин](https://github.com/torin-asakura/drum-in/blob/master/package.json), во всех примерах используется резолюшен, где указывается `@types/react` 17 версии 
- Указывал `Swiper` через `packageExtension` разные версии `react`.

**Вопрос**

Можно все-таки через резолюшен разрешить ошибки при `Typecheck`? 

Если нужно через `packageExtension`, прошу помочь с решением.

2023-08-01 19:35 UTC, TorinAsakura commented on package.json
> +    "next": "12.3.4"
@Nelfimov ^ pls

2023-08-02 06:20 UTC, Nelfimov commented on package.json
> +    "next": "12.3.4"
В `packageExtension` если добавить:

```yaml
  swiper@*:
    dependencies: 
      '@types/react': '17.0.62'
      react: '17.0.2'
```

То Yarn будет ругаться на дубликаты `@types/react` 17 и 18 версии, например:
```Shell
➤ YN0000: │ ../../../../../.yarn/berry/cache/@types-react-npm-18.2.18-cb58ec5c01-9.zip/node_modules/@types/react
➤ YN0000: │ /ts5.0/index.d.ts
➤ YN0000: │
➤ YN0000: │   Error: Duplicate identifier 'LibraryManagedAttributes'.
```

Пробовал через `Yarn dedupe` пофиксить, но он не видит `@types/react`.

Предлагаю оставить решение Михаила через `resolutions`, тем более в других проектах так делали (`drum-in`, [задание Оксаны](https://github.com/atls-academy/oksssvv.github.io/pull/18#issuecomment-1560838832))

На будущее - надо грейдить `@atls-ui-parts/swiper` до 10 версии, там 18 реакт.

2023-08-03 11:13 UTC, oksssvv requested changes
зайдя в инспектор - увидела что консоль там в шоке, это надо фиксить

2023-08-03 11:13 UTC, oxiqod commented on landing/fragments/landing-about/package.json
> +    "@ui/utils": "workspace:^"
не уверена в использовании кареток, мне в свое время сказали что лучше обойтись четкой версией, это касается всех пакетов, в том числе из npm менеджера

2023-08-03 11:13 UTC, oxiqod commented on landing/fragments/landing-about/src/about.component.tsx
> +                    color='text.about.primary'
к чему такая гипер-вложенность?
цветов текста будет чуть более 10
- и опять же если в остальных фрагментах будут цвета `primary`, то ты будешь создавать их отдельно?

я посмотрела, а у тебя так как и есть:
![Снимок экрана от 2023-08-03 13-06-16](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/40bd1f9a-96a2-457e-b606-0db66b4dfead)

как я это вижу:
![Снимок экрана от 2023-08-03 13-07-38](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/63200352-00ec-4553-ab83-56a026b4c108)

я помню наше разногласие по этому поводу, поэтому думаю решать @TorinAsakura

2023-08-03 11:13 UTC, oxiqod commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +  widthCard,
почему ограничение ширины предполагается? карточка 100%, ширина ее будет зависеть от размера контейнера и свободного пространства

2023-08-03 11:13 UTC, oxiqod commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +  spaceBetweenCategoryAndTitle,
к чему гиперименование? мб просто `gap` или `indent`

2023-08-03 11:13 UTC, oxiqod commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +  text,
скорее `description`

2023-08-03 11:13 UTC, oxiqod commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +            {titleMobile}
интересно, между текстом в мобильной и десктопной версии - разницы не вижу, тогда зачем 2 пропса

- если исОнлиМобайл, то почему значения для нескольких вьюпортов?

2023-08-03 11:13 UTC, oxiqod commented on landing/fragments/landing-courses/src/card/card.component.tsx
`card` как таковой является ui-компонентом, т.к. она уже становится похожа на карточку на данном этапе - её можно переселять в другой слой

2023-08-03 11:13 UTC, oxiqod commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +  path,
по макету в целом не предполагается что она куда то будет перенаправлять пользователя, тем более на данном этапе

просто уже идет явный перегруз пропсов, поэтому каждый на счету

2023-08-03 11:13 UTC, oxiqod commented on landing/fragments/landing-courses/src/courses.component.tsx
> +            <Box width={254} height={72} alignItems='center'>
поч 2 бокса подряд

2023-08-03 11:13 UTC, oxiqod commented on landing/fragments/landing-hero/src/hero.component.tsx
> +      <Column flexGrow='1'>
ненужный Колумн, насколько помню - ему нельзя дать бэкграунд, но можно же предыдущему боксу установить флексДирекшн = Колумн

2023-08-03 11:13 UTC, oxiqod commented on landing/fragments/landing-hero/src/hero.component.tsx
> +    </Box>
взглянув на закрывающие теги - возникает вопрос: тут точно все эти дивы нужны?

2023-08-03 11:13 UTC, oksssvv commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +      <ItemsList navLinksList={navLinkList} />
лично меня эта структура - запутала
перемудрил наверно

![Снимок экрана от 2023-08-03 14-01-59](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/4e2491bb-a33f-4df6-afdd-62b961f83fc0)

2023-08-03 11:13 UTC, oksssvv commented on landing/fragments/landing-process/src/item/item.component.tsx
>    process,
`title` | `name` думаю подходит больше

2023-08-03 11:13 UTC, oksssvv commented on landing/fragments/landing-process/src/item/item.component.tsx
>    text,
`description`

2023-08-03 11:13 UTC, oksssvv commented on landing/fragments/landing-process/src/item/item.component.tsx
> +  displayDivider = true,
просто `divider`?

2023-08-03 11:22 UTC, Mirved64 commented on landing/fragments/landing-hero/src/hero.component.tsx
> +      <Column flexGrow='1'>
Я так и делал, но @TorinAsakura сказал стилизатор отдельно, направляющие отдельно

2023-08-03 11:25 UTC, Mirved64 commented on landing/fragments/landing-about/package.json
> +    "@ui/utils": "workspace:^"
@TorinAsakura с каретками критично или можно оставить?

2023-08-03 11:38 UTC, Mirved64 commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +            {titleMobile}
@oksssvv в макете на втором степе шрифты немного отличаются у заголовков (может в других степах одинаково, но во втором степе и расстояния между левым краем и заголовком у больших и маленьких карточек разное и становится равным только в 4 степе), спрашивал @TorinAsakura, было сказано делать как в макете. 
С количеством вьюпортов - моя ошибка

2023-08-03 11:39 UTC, TorinAsakura commented on landing/fragments/landing-about/src/about.component.tsx
> +                    color='text.about.primary'
гипер-вложенность

2023-08-03 11:47 UTC, Mirved64 commented on landing/fragments/landing-courses/src/card/card.component.tsx
@oksssvv у меня есть ui card. Согласно [конвенции](https://github.com/atls/convention/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-UI#%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-ui), ui компонент не должен быть прибит гвоздями к конкретному месту в проекте.

@TorinAsakura как правильнее сделать?

2023-08-03 11:50 UTC, Mirved64 commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +  path,
@oksssvv мне казалось, что при нажатии переносит в соответствующую страницу в библиотеке?

@TorinAsakura как правильнее?

2023-08-03 11:53 UTC, oksssvv commented on landing/fragments/landing-courses/src/card/card.component.tsx
> +  path,
@Mirved64 
> мне казалось, что при нажатии переносит в соответствующую страницу в библиотеке?

по макету не предусмотрено такого функционала, я вроде бы ничего не упустила

2023-08-03 11:56 UTC, oksssvv commented on landing/fragments/landing-courses/src/card/card.component.tsx
>у меня есть ui card. Согласно [конвенции](https://github.com/atls/convention/wiki/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-UI#%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-ui), ui компонент не должен быть прибит гвоздями к конкретному месту в проекте.

эх, я даже не уловила, потому что ты делал всю верстку внутри фрагмента
![Снимок экрана от 2023-08-03 14-54-36](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/a4a43afc-0b0e-4285-acb0-4939e92a9bc3)

думаю ты слишком буквально воспринял `не прибито гвоздями`)

2023-08-03 13:18 UTC, Mirved64 commented on landing/fragments/landing-hero/src/hero.component.tsx
> +    </Box>
@oksssvv, @TorinAsakura сказал стилизатор отдельно, направляющие отдельно

2023-08-04 08:20 UTC, oksssvv requested changes

2023-08-04 08:20 UTC, oxiqod commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +      <Layout flexBasis={[0, 40]} flexShrink='0' />
флексШринк тут не обязателен, если уберешь у обоих лэйаутов (которые дают отступы по сторонам, для навигации) - то увидишь, что они не сжались, т.к. им достаточно пространства

сейчас объясню зачем это вообще - если вьюпорт пользователя будет меньше чем стандартный FullHD - то твоей навигации необходимо будет адаптироваться под него, и лучше это будет сделано за счет этих лэйаутов, нежели за счет элементов которые друг на друга начнут залезать (это как пример)

я тоже верстала онли на шринках, чтоб все было четко по макету, но когда пришло время проверки адаптивности - все лэйауты с выставленными шринками запретили верстке сжиматься как надо

- я просто делюсь информацией и опытом, т.к. где то их использовать приходится, все зависит от ситуации и решать придется тебе

как пример кол-во применений в твоем проекте:
![Снимок экрана от 2023-08-04 10-33-53](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/14b18761-a16b-4059-8569-00d7a8973bd6)

2023-08-04 08:20 UTC, oxiqod commented on ui/theme/src/theme/index.ts
насчет оформления `fontSizes` и `lineHeights` - значения можно задавать и в числовом виде, так компактнее получается

 *это совет

2023-08-04 08:20 UTC, oksssvv commented on landing/fragments/landing-courses/src/info/info.component.tsx
> +  <Box flexDirection={['column', 'row']} justifyContent='space-between'>
проверяю на адаптивность для меньшего вьюпорта, и вот проблема спейсБитвина:

![Снимок экрана от 2023-08-04 10-54-16](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/23ad02c6-d6e1-4ab7-bee4-abb2d78f2995)

если отступ между текстовыми блоками был реализован за счет лэйаута, то они бы не склеились, и флексВрап - сработал бы как нужно

вот тебе пример с лэйаутом:
![Снимок экрана от 2023-08-04 10-59-02](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/83b9887b-625f-4f88-9177-fad29ae13fb2)

2023-08-04 08:20 UTC, oksssvv commented on landing/fragments/landing-faq/src/faq.component.tsx
>          <Row justifyContent='space-between' alignItems='center'>
такая же ситуация с адаптивностью как и во фрагменте `Курсы`:

![Снимок экрана от 2023-08-04 11-02-57](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/2142b19a-c357-4f7d-830b-e0af8db8d479)

когда `задать вопрос` примит вид более похожий на кнопку - станет видно что они также склеились, если задать лэйаут вместо спейсБитвина - лучше будет отрабатывать перенос текста и расстояние между элементами: 

![Снимок экрана от 2023-08-04 11-06-00](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/00cf573b-45f6-4cc4-9252-0b55723adba0)

2023-08-04 08:20 UTC, oksssvv commented on landing/fragments/landing-about/src/about.component.tsx
> +          <Column flexBasis={[335, 1460]} flexGrow='1' flexShrink={[1, 0]}>
проверка на адаптивность, этот фрагмент единственный вылез за пределы, все остальные +- нормально себя ведут на меньшем вьюпорте

всему бедой ширина 1460 + флексШринк=0

![Снимок экрана от 2023-08-04 11-07-39](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/02060f3d-c05e-4727-9b31-53cdbf3fe501)

если в инспекторе удалить этот див:

![Снимок экрана от 2023-08-04 11-10-24](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/9d6e0e81-44c1-499d-94dc-c2abd128ce3b)

2023-08-04 08:20 UTC, oksssvv commented on landing/fragments/landing-technologies/src/technologies.component.tsx
![Снимок экрана от 2023-08-04 11-15-44](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/4fc951d3-f708-4547-90d5-637a83111c03)

2023-08-04 08:28 UTC, Mirved64 commented on landing/fragments/landing-technologies/src/technologies.component.tsx
@oksssvv 
Тут же нужно будет делать бегущую строку. Пока её нет, может оставить так?

2023-08-04 08:32 UTC, oxiqod commented on landing/fragments/landing-technologies/src/technologies.component.tsx
@Mirved64 
просто удивилась что элемент прям в текст заехал, в целом то да, весь фрагмент потом будет перелопачиваться для бегущей строки

>Пока её нет, может оставить так?

насчет этого ^ - решать точно не мне)

2023-08-04 08:52 UTC, Mirved64 commented on landing/fragments/landing-about/src/about.component.tsx
> +          <Column flexBasis={[335, 1460]} flexGrow='1' flexShrink={[1, 0]}>
@oksssvv 
Скажи пожалуйста, в каких диапазонах вьюпорта смотреть?

Просто у нас мобильная и десктопная версия, промежуточной для планшетов нет.
Мобильная версия хорошо себя ведет при вьюпорте <640px, десктопную версию сделаю от 1460px.

Этого достаточно?

2023-08-04 09:07 UTC, oksssvv commented on landing/fragments/landing-about/src/about.component.tsx
> +          <Column flexBasis={[335, 1460]} flexGrow='1' flexShrink={[1, 0]}>
@Mirved64 
гугл говорит 1200 - 1920

- на самом деле тебе очень мало нужно поменять чтоб верстка хорошо ложилась под указанный на скринах вью (1366x1024), я лично тоже под него ориентировалась

1. у тебя проблема с `About`, там нужно дать тексту переноситься и убрать запрет сжатия
2. в курсах заголовок с кнопкой
3. в faq тоже заголовок с кнопкой

в остальном все хорошо, внеси сначала эти правки, и увидишь что на 1366 верстка станет адаптивной, если что не получится - пиши

2023-08-04 11:50 UTC, oksssvv commented
@Mirved64 

так поправил, что аж стандартная верстка слетела

![Снимок экрана от 2023-08-04 14-48-15](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/0b71f26a-bf8f-4eab-b9e5-90920c23eecb)

2023-08-04 11:51 UTC, oksssvv commented
@Mirved64 

насчет `faq` и `courses` - всё теперь красиво, поправь `About` и перезапроси

2023-08-04 13:51 UTC, oksssvv approved these changes
все правки внес, теперь всё хорошо по макету и адаптивности, поздравляю 👍

2023-08-04 16:32 UTC, TorinAsakura commented on landing/fragments/landing-about/package.json
> +    "@ui/utils": "workspace:^"
> @TorinAsakura с каретками критично или можно оставить?

всегда критично

2023-08-06 15:28 UTC, Nelfimov commented on landing/fragments/landing-technologies/src/technologies.component.tsx
Неообходимо пофиксить.

2023-08-06 15:43 UTC, Nelfimov requested changes
Необходимы доработки.

2023-08-06 15:43 UTC, Nelfimov commented on landing/entrypoints/renderer/package.json
> +    "next": "13.4.4",
Давай унифицируем версию `next` - у тебя все таки выше резолюшн есть.

2023-08-06 15:43 UTC, Nelfimov commented on landing/entrypoints/renderer/package.json
>    "peerDependencies": {
`react` здесь не имеет смысла - у тебя энтрипоинт является точкой входа и он ни у кого не получит `react`.

2023-08-06 15:43 UTC, Nelfimov commented on landing/pages/index-page/package.json
>      "react": "18.2.0"
Ниже `react` есть в пир-зависимостях, а тут он для чего тогда? Для разработки надо добавить `@types/react` в devDependencies.

2023-08-06 15:43 UTC, Nelfimov commented on ui/condition/package.json
> +{
Предлагаю использовать `@atls-ui-parts/condition` и просто его реэкспортировать.

2023-08-06 15:43 UTC, Nelfimov commented on ui/icons/package.json
>      "react": "^18.2.0",
Оставил каретки, а через peerDependencies `react` не хочешь получать в отличие от других ui компонентов.

2023-08-06 15:43 UTC, Nelfimov commented on ui/link/package.json
> +    "next": "13.4.5",
Надо унифицировать `next`

2023-08-06 15:43 UTC, Nelfimov commented on ui/link/package.json
> +    "react-dom": "18.2.0",
`react-dom` тоже можно ведь через peer получать.

2023-08-07 09:11 UTC, Mirved64 commented on ui/condition/package.json
> +{
@Nelfimov
 
**Скоуп**
`@atls-ui-parts/condition`

**Описание**
При использовании и реэкспорте `@atls-ui-parts/condition` `Typecheck` выдаёт ошибку:
```
➤ YN0000: ┌ Typecheck
➤ YN0000: │ .yarn/__virtual__/@atls-ui-parts-condition-virtual-e123f142c2/4/.yarn/berry/cache/@atls-ui-parts-condition-npm-0.0.3-20569027df-9.zip/node_modu
➤ YN0000: │ les/@atls-ui-parts/condition/dist/condition.component.d.ts
➤ YN0000: │ 
➤ YN0000: │   Error: Cannot find name 'PropsWithChildren'.
➤ YN0000: │ 
➤ YN0000: │ 
➤ YN0000: └ Completed in 4s 394ms
➤ YN0000: Failed with errors in 4s 395ms
```
**Мои действия**
Гуглил, нашел [статью](https://bobbyhadz.com/blog/react-typescript-cannot-find-name)
Ставил дополнительно `@types/react`, `@types/react-dom`. 
В `tsconfig.json` менял "jsx": "react" на `react-jsx`.
Смотрел репозитории примеров, там этот `ui` не реэкспортируется из `@atls-ui-parts/condition`.  

**Вопросы**
Как убрать ошибку?
Может это ошибка в `@atls-ui-parts/condition`?

2023-08-07 09:43 UTC, Nelfimov commented on ui/condition/package.json
> +{
Это нестыковка 17 и 18 реакта. Давай вернем как было, замечаний по коду нет. 

А я пофикшу совместимость на досуге.

2023-08-07 10:27 UTC, Mirved64 commented on landing/entrypoints/renderer/package.json
>    "peerDependencies": {
@Nelfimov 

**Скоуп**
`peerDepencies`

**Описание**
Если убрать из `peerDepencies` `react: "*"`, `yarn` выдаёт варнинг:
`➤ YN0060: │ @landing/renderer-entrypoint@workspace:landing/entrypoints/renderer provides react (p58051) with version 18.2.0, which doesn't satisfy what @landing/index-page and some of its descendants request`

С помощью команды `yarn explain peer-requirements p58051` получаем такие логи:
```
➤ YN0000: @atls-ui-parts/button@npm:0.0.12 [d16f3]                                                → ^17.0.1  ✘
➤ YN0000: @atls-ui-parts/conditional-render@npm:0.0.4 [d16f3]                                     → ^17.0.1  ✘
➤ YN0000: @atls-ui-parts/image@npm:0.0.4 [28e56]                                                  → ^17.0.1  ✘
➤ YN0000: @atls-ui-parts/layout@npm:0.0.7 [5d96d]                                                 → ^17.0.1  ✘
➤ YN0000: @atls-ui-parts/layout@npm:0.0.7 [fb305]                                                 → ^17.0.1  ✘
➤ YN0000: @atls-ui-parts/link@npm:0.0.10 [768b9]                                                  → ^17.0.1  ✘
➤ YN0000: @atls-ui-parts/swiper@npm:0.0.3 [8ad65]                                                 → ^17.0.1  ✘
➤ YN0000: @atls-ui-parts/text@npm:0.0.10 [31ea9]                                                  → ^17.0.1  ✘
➤ YN0000: @atls-ui-proto/divider@npm:0.0.6 [5d96d]                                                → ^17.0.1  ✘
➤ YN0000: @emotion/react@npm:11.11.1 [f4f84]                                                      → >=16.8.0 ✓
➤ YN0000: @emotion/styled@npm:11.11.0 [28e56]                                                     → >=16.8.0 ✓
➤ YN0000: @emotion/styled@npm:11.9.3 [f4f84]                                                      → >=16.8.0 ✓
➤ YN0000: @emotion/use-insertion-effect-with-fallbacks@npm:1.0.1 [d230c]                          → >=16.8.0 ✓
➤ YN0000: @landing/fragment-about@workspace:landing/fragments/landing-about [cc78e]               → *        ✓
➤ YN0000: @landing/fragment-courses@workspace:landing/fragments/landing-courses [cc78e]           → *        ✓
➤ YN0000: @landing/fragment-faq@workspace:landing/fragments/landing-faq [cc78e]                   → *        ✓
➤ YN0000: @landing/fragment-hero@workspace:landing/fragments/landing-hero [cc78e]                 → *        ✓
➤ YN0000: @landing/fragment-navigation@workspace:landing/fragments/landing-navigation [cc78e]     → *        ✓
➤ YN0000: @landing/fragment-process@workspace:landing/fragments/landing-process [cc78e]           → *        ✓
➤ YN0000: @landing/fragment-slider@workspace:landing/fragments/landing-slider [cc78e]             → *        ✓
➤ YN0000: @landing/fragment-technologies@workspace:landing/fragments/landing-technologies [cc78e] → *        ✓
➤ YN0000: @landing/index-page@workspace:landing/pages/index-page [653a5]                          → *        ✓
➤ YN0000: @ui/button@workspace:ui/button [054b3]                                                  → *        ✓
➤ YN0000: @ui/card@workspace:ui/card [054b3]                                                      → *        ✓
➤ YN0000: @ui/condition@workspace:ui/condition [0f2f1]                                            → *        ✓
➤ YN0000: @ui/condition@workspace:ui/condition [3bd8d]                                            → *        ✓
➤ YN0000: @ui/divider@workspace:ui/divider [054b3]                                                → *        ✓
➤ YN0000: @ui/icons@workspace:ui/icons [054b3]                                                    → *        ✓
➤ YN0000: @ui/image@workspace:ui/image [3bd8d]                                                    → *        ✓
➤ YN0000: @ui/layout@workspace:ui/layout [3bd8d]                                                  → *        ✓
➤ YN0000: @ui/layout@workspace:ui/layout [d16f3]                                                  → *        ✓
➤ YN0000: @ui/link@workspace:ui/link [054b3]                                                      → *        ✓
➤ YN0000: @ui/swiper@workspace:ui/swiper [054b3]                                                  → *        ✓
➤ YN0000: @ui/text@workspace:ui/text [3bd8d]                                                      → *        ✓
➤ YN0000: @ui/utils@workspace:ui/utils [3bd8d]                                                    → *        ✓
➤ YN0000: framer-motion@npm:10.12.10 [f4f84]                                                      → ^18.0.0  ✓

```
**Мои действия**

Читал про [`peerDepencies`](https://github.com/atls/hyperion/wiki/%D0%A7%D1%82%D0%BE-%D1%82%D0%B0%D0%BA%D0%BE%D0%B5-peerDependencies). 
Понял это так, что при указании `peerDepencies` пакет "смотрит" на зависимости родительского пакета и использует их.
У точки входа нет родительского пакета, из которого получим зависимости - с этим я согласен.

**Вопрос**

Почему, если добавить в энтри поинт `peerDepencies` `react: "*"`, то ворнинг пропадает?

2023-08-07 13:38 UTC, Nelfimov commented on landing/entrypoints/renderer/package.json
>    "peerDependencies": {
Это предупреждение, что `entrypoint` дает реакт версии 18.2.0, а кто то из потомков `index-page` требует меньшей версии, скорее всего 17.

Можно игнорировать.

2023-08-07 16:24 UTC, Mirved64 commented on landing/fragments/landing-technologies/src/technologies.component.tsx
@Nelfimov 

**Скоуп**
`flex-элементы` налезают друг на друга

**Описание**
Элементы налезают друг на друга, даже если у контейнера достаточно места (элементы `Item` налазят друг на друга, даже если у контейнера `Row` есть еще свободное пространство).

Элементы неумещаются в контейнере (контейнер `Item` не хочет растягиваться под размер содержимого, а сжимает дочерние элементы). 

При переполнении родительского контейнера (`Row`), элементы `Item` не хотят выходить за пределы, хотя поставлен `overflow='hidden'`, если поставить `flexWrap='wrap'` элементы сжимаются, но не переходят на новую строку.

Если убрать запрет на сжатие элементов (разделителя и лейаутов по обе стороны), то выглядит нормально, но не соответсвует макету.

**Мои действия**

Выставлял `flexBasis`, `flexGrow='1'`, `flexShrink='1'` для контейнера `Item` - элементы налазиют друг на друга и не хотят выходить за пределы `Row`.
Выставлял `flexBasis`, `flexGrow='1'`, `flexShrink='1'` для `Box` контейнера с текстом - элементы налазиют друг на друга и не хотят выходить за пределы `Row`.

**Вопрос**
Как заставить элементы `Item` выйти за пределы `Row` и скрыть их (чтобы не появился скролл)?

2023-08-07 17:26 UTC, Mirved64 commented on landing/fragments/landing-technologies/src/technologies.component.tsx
> @Nelfimov
> 
> **Скоуп** `flex-элементы` налезают друг на друга
> 
> **Описание** Элементы налезают друг на друга, даже если у контейнера достаточно места (элементы `Item` налазят друг на друга, даже если у контейнера `Row` есть еще свободное пространство).
> 
> Элементы неумещаются в контейнере (контейнер `Item` не хочет растягиваться под размер содержимого, а сжимает дочерние элементы).
> 
> При переполнении родительского контейнера (`Row`), элементы `Item` не хотят выходить за пределы, хотя поставлен `overflow='hidden'`, если поставить `flexWrap='wrap'` элементы сжимаются, но не переходят на новую строку.
> 
> Если убрать запрет на сжатие элементов (разделителя и лейаутов по обе стороны), то выглядит нормально, но не соответсвует макету.
> 
> **Мои действия**
> 
> Выставлял `flexBasis`, `flexGrow='1'`, `flexShrink='1'` для контейнера `Item` - элементы налазиют друг на друга и не хотят выходить за пределы `Row`. Выставлял `flexBasis`, `flexGrow='1'`, `flexShrink='1'` для `Box` контейнера с текстом - элементы налазиют друг на друга и не хотят выходить за пределы `Row`.
> 
> **Вопрос** Как заставить элементы `Item` выйти за пределы `Row` и скрыть их (чтобы не появился скролл)?

Проблему решил. 
Обернул `Layout`, `Divider` и `Layout` в `Box` и задал ему ширину.

2023-08-07 17:35 UTC, Nelfimov approved these changes
Все пофиксил, молоток!

2023-08-17 18:09 UTC, TorinAsakura approved these changes
Мои поздравления

2023-08-17 18:09 UTC, merged