Feat/landing third step
atls-academy/Mirved64.github.io pull request #13
Opened 2023-08-09 06:20 UTC by Mirved64

Close #12

2023-08-11 14:32 UTC, Mirved64 commented
@Nelfimov 

**Скоуп**
Анимация параллакса в проекте

**Описание**
Не могу понять как сделать эффект параллакса как в макете.
Не понимаю до конца саму анимацию параллакса (как секция при прокрутке наезжает на предыдущую секцию).

**Мои действия**
- Смотрел примеры - там нет этой анимации.
- Пробовал использовать `@atls-ui-proto/parallax`, застопорился на настройке провайдера - не получилось разобраться с `ui`, забросил.
- Решил использовать библиотеку [`react-scroll-parallax`](https://react-scroll-parallax.damnthat.tv/docs/intro).
- Подключил библиотеку, обернул `App` в `ParallaxProvider`, использовал компонент `Parallax` - работает.
- Пробовал настроить анимацию, но не до конца понимаю как сделать нужную анимацию.
- Читал [документацию](https://react-scroll-parallax.damnthat.tv/docs/examples/how-it-works) к библиотеке, нагуглил [статью](https://medium.com/stackanatomy/adding-parallax-scroll-animations-to-react-a518889ee547) про библиотеку.
- Не смог найти нужную анимацию (как секция при скролле наезжает на предыдущую секцию).

**Вопросы**
Какие параметры меняются при анимации? (`translateY`? тогда получается, что контент секции наезжает на предыдущую, но потом идет очень большой `gap` до следующей)

Какой механизм анимации?

2023-08-11 17:33 UTC, Nelfimov commented
Давай пока начнем с очевидных фиксов:
1. перейди на % параметры в `translateY`
2. параллакс должен распространяться на элементы внутри `background`
3. параллакс как эффект по дизайну применяется только там, где есть фон - в нашем случае это синий. То есть будто белый наезжает на синий.

2023-08-13 17:23 UTC, oksssvv requested changes

2023-08-13 17:23 UTC, oxiqod commented on landing/fragments/landing-courses/src/courses.component.tsx
> +          <Divider backgroundColor='divider.black' weight='1px' />
уже не `black`

2023-08-13 17:23 UTC, oxiqod commented on landing/fragments/landing-process/src/process.component.tsx
> +            description={intl.formatMessage({ id: 'process.item.text' })}
текст дескрипции изменили, чек макет

2023-08-13 17:23 UTC, oxiqod commented on ui/card/src/card.component.tsx
>    description,
компактнее передавать ({...props}) а затем использовать например `<Layout flexBasis={props.indent} />`

2023-08-13 17:23 UTC, oxiqod commented on landing/fragments/landing-courses/src/courses.component.tsx
> +        </Swiper>
у swiper'а нет отступов слева и справа

![Снимок экрана от 2023-08-13 19-22-10](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/1d67fd3f-21b3-4857-82ab-e413498af952)

2023-08-13 17:23 UTC, oxiqod commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +          <LogoWhiteIcon width={40} height={40} />
ну вообще для `logo` создается отдельный ui компонент, и насчет цвета - его лучше менять через пропсы, ибо зачем создавать две иконки у которых разница только в цветовом варианте

2023-08-13 17:23 UTC, oxiqod commented on landing/fragments/landing-hero/src/hero.component.tsx
> +              fontWeight='normal'
так оно ж по дефолту 400, зачем еще раз передавать

![Снимок экрана от 2023-08-13 19-55-14](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/ebfbde56-a38f-43c6-ac05-b0c75b84ce81)

2023-08-13 17:23 UTC, oksssvv commented on landing/fragments/landing-hero/src/hero.component.tsx
> +                <FormattedMessage id='hero.title.it' />
главный заголовок можно разбить на 2 текстовых части - `Обучаем профессионалов для революции в` и `it` (таким образом код будет компактнее за счет отсутствия повторения одинаковых компонентов для текста)
у тебя 4 части: `Обучаем` `профессионалов` `для революции в` `it`

2023-08-13 17:23 UTC, oksssvv commented on landing/fragments/landing-hero/src/hero.component.tsx
> +          <Divider backgroundColor='divider.white' weight={1} flexShrink='1' />
флексШринк по умолчанию = 1

![Снимок экрана от 2023-08-13 20-06-41](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/b28e2ecd-84e1-4b43-b0ff-32f853c7fb66)

2023-08-13 17:23 UTC, oksssvv commented on landing/fragments/landing-hero/src/hero.component.tsx
> +                <Link href='https://www.google.com/intl/ru/gmail/about/'>
этот код можно вынести в отдельный компонент и переиспользовать, меняется только `href` и `icon`

2023-08-13 17:23 UTC, oksssvv commented on landing/fragments/landing-faq/src/faq.component.tsx
> +        <Item question={intl.formatMessage({ id: 'faq.question' })} divider={1} />
вопросы то ладно, а дивидер зачем передавать, если он всегда толщиной = 1

2023-08-14 14:35 UTC, oksssvv requested changes

2023-08-14 14:35 UTC, oxiqod commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +          <Logo fill='white' logoWidth={40} logoHeight={40} />
тут ни к чему дублирование слова `logo` и так ж понятно что Логотипу ширину / высоту устанавливаем, так и передавай `width`  `height`

2023-08-14 14:35 UTC, oxiqod commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +        <Layout flexBasis={[0, 40]} />
если кондишн = десктоп, то зачем внутри 3 лэйаута с нулевыми значениями для мобильной версии

2023-08-14 14:35 UTC, oksssvv commented on landing/fragments/landing-about/src/about.component.tsx
> +                <FormattedMessage id='about.intro-mobile' />
обрати внимание на макет, там другие переносы

2023-08-14 14:35 UTC, oksssvv commented on landing/fragments/landing-about/src/about.component.tsx
> +                <FormattedMessage id='about.central-idea' />
здесь тоже другие

2023-08-14 14:35 UTC, oksssvv commented on landing/fragments/landing-courses/src/courses.component.tsx
> +          <Swiper spaceBetween={20} slidesPerView={1.23} className='swiper-1'>
![Снимок экрана от 2023-08-14 17-10-00](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/841c9798-1213-40c1-a942-4b4cc3afcc46)

слева отступ - сделал, а справа?

2023-08-14 14:35 UTC, oksssvv commented on landing/fragments/landing-slider/src/slider.component.tsx
> +          <ImageBlock src='./image/mockup.png' />
по макету в мобильной версии высота слайдера 323px, у тебя получается 344px

2023-08-14 14:35 UTC, oksssvv commented on ui/button/src/button.interfaces.ts
>    active?: boolean
у тебя ж вроде пока состояний нет

2023-08-14 18:05 UTC, Mirved64 commented on landing/fragments/landing-courses/src/courses.component.tsx
> +          <Swiper spaceBetween={20} slidesPerView={1.23} className='swiper-1'>
@oksssvv 
в макете нет отступа справа
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/05a14622-30f6-4919-9835-7d70464b8afb)

у меня отступ справа только так получается
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/484fc3ca-2c98-4e6a-b7cf-0d239758cf7c)

не по макету

2023-08-15 06:20 UTC, Mirved64 commented on landing/fragments/landing-slider/src/slider.component.tsx
> +          <ImageBlock src='./image/mockup.png' />
@oksssvv 
В четвертом степе уже переработал слайдер полностью.
Когда делал третий степ, не понял что там в слайдере меняется

2023-08-15 08:39 UTC, oksssvv approved these changes

2023-08-15 10:24 UTC, Nelfimov requested changes
Есть UI баги:
1. верхний навбор ушел за вьюпорт:

<details>

<img width="1374" alt="Screenshot 2023-08-15 at 13 16 49" src="https://github.com/atls-academy/Mirved64.github.io/assets/44067768/41db1f39-56bf-4aac-a513-c1a91c40d734">

</details>

2. Карточки не адаптивны - текст выходит за пределы:

<details>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/44067768/3439af71-0eed-488a-b760-46ee82ed9659)

</details>

3. Список не выравнен по центру вертикали:

<details>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/44067768/0c88a64f-9309-41ac-b7a9-327c20bd4fe7)

</details>

4. Карточки, которые в мобильном виде прокручиваются свайпом, вплотную прилегают к вьюпорту слева и справа. Должны быть выровнены по верхним статичным

<details>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/44067768/cb88e54c-1019-4d7a-8e0f-1a7e3bd4675a)

</details>

2023-08-15 16:16 UTC, Mirved64 commented
@Nelfimov 

Странно, у меня кроме адаптивности карточек всё хорошо. Смотрел в хроме и мозиле, точно ветка третьего степа.
- навбар на месте
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/f4cb9087-e56b-4316-80c9-301a25bbd088)

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/de2fea86-a4d2-4c4f-ae01-09c08e1c4ef3)
</p>
</details> 

- список правильно отображается
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/5bbb5b1c-23c2-4562-93a7-011e9058c706)

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/51e207b2-6613-41a9-8851-1d36a4da057b)

</p>
</details> 

- Карточки, которые в мобильном виде прокручиваются свайпом с зазорами по бокам
<details><summary>Details</summary>
<p>

[Screencast from 15.08.2023 19:59:59.webm](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/4a62e53f-9559-4407-9f75-3641a640b966)

[Screencast from 15.08.2023 20:00:39.webm](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/cbd933aa-2cdf-4745-8adc-d862086f8b39)

</p>
</details>

2023-08-15 17:27 UTC, Nelfimov requested changes
Необходимы правки.

2023-08-15 17:27 UTC, Nelfimov commented on landing/entrypoints/renderer/package.json
>      "@formatjs/cli": "6.1.3",
`typescirpt` должен быть не выше 4.6.2. Меняй тут и желательно в `resolutions` в корне.

2023-08-15 17:27 UTC, Nelfimov commented on landing/fragments/landing-courses/src/courses.component.tsx
> +              <Card
Давай все карточки перепишем через `.map`. Создаешь список/объект из данных карточек, и его мапишь с `return (<Card ... />)`. Иначе ты под каждую карточку повторяешь код.

2023-08-15 17:27 UTC, Nelfimov commented on landing/fragments/landing-faq/src/faq.component.tsx
> +        <Item question={intl.formatMessage({ id: 'faq.question' })} />
Давай сделаем отдельно выше список из 6 элементов, его размапим и вернем `<Item ... />`.

2023-08-15 17:27 UTC, Nelfimov commented on tsconfig.json
> +  "include": ["auth/**/*", "landing/**/**/*", "ui/**/**/**/**/*"]
А зачем такая вложенность в паттерне?

2023-08-15 18:55 UTC, TorinAsakura commented on landing/entrypoints/renderer/package.json
>      "@formatjs/cli": "6.1.3",
от resolutions лучше вообще избавляться и хорошенько пройтись по зависимостям проекта

2023-08-16 05:42 UTC, Mirved64 commented on landing/entrypoints/renderer/package.json
>      "@formatjs/cli": "6.1.3",
`resolutions` использую, т.к. если убрать, то `Typecheck` выдаёт ошибки из-за зависимостей некоторых библиотек из `Hyperion UI-Kit`. 

С зависимостями вроде все норм, только блиотеки `@atls-ui-parts/layout`и `@atls-ui-proto/divider` запрашивают `react` версии `"^17.0.1"` в `peerDependencies`. Убрать это с помощью `packageExtensions` не получается.

2023-08-17 07:24 UTC, Nelfimov approved these changes

2023-08-17 12:28 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +import { CardsLearning }    from './cards'
я, как и ранее - не рекомендовал бы косметические отличия выдавать за новую сущность, на 7 этапе будет бобо)

2023-08-17 12:37 UTC, TorinAsakura approved these changes

2023-08-17 12:37 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/info/info.component.tsx
> +        display='inline'
зачем тут везде инлайны выставленны?

2023-08-17 12:37 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/faq-list/faq-list.ts
> +    id: 5,
к чему копипаста? можно ведь прогнать через цикл один объект

2023-08-17 12:37 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/social-link/social-link.interface.ts
> +  icon: JSX.Element
👍

2023-08-17 12:37 UTC, TorinAsakura commented on landing/fragments/landing-process/src/item/item.component.tsx
> +        <Box alignItems='center' flexBasis={[28, 367]} flexShrink='0' flexGrow='1'>
объясни конструкцию

2023-08-17 13:52 UTC, oksssvv commented
@Mirved64 .

2023-08-21 07:33 UTC, Mirved64 commented on landing/fragments/landing-courses/src/courses.component.tsx
> +import { CardsLearning }    from './cards'
У меня тут три разных компановки карточек. 

Т.е. сущность одна - карточка, просто в одном случае показывает карточки с категорией `учебный материал`, в другом карточки собираются в свайпер, в третьем  карточки с категорией `обучение` или `мини-курс`.

2023-08-21 07:58 UTC, Mirved64 commented on landing/fragments/landing-process/src/item/item.component.tsx
> +        <Box alignItems='center' flexBasis={[28, 367]} flexShrink='0' flexGrow='1'>
@TorinAsakura 

Обертка бокс нужна для разных значений `flexDirection` на мобилке и декстопе, `flexGrow` у обертки - разрешаем расти. Внутри обертки у бокса `flexGrow`, чтобы он рос и рос медленнее чем элемент `Layout` (у которого `flexGrow` задан 3) между именем и описанием. Тогда верстка не ломается на разных разрешениях вьюпорта.

2023-08-21 10:18 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +import { CardsLearning }    from './cards'
а должна быть одна карточка, которая где-либо расширяется и переиспользуется

2023-08-21 10:18 UTC, merged