feat/landing-fourth-step
atls-academy/Mirved64.github.io pull request #15
Opened 2023-08-12 14:03 UTC by Mirved64

Close #14

2023-08-15 09:10 UTC, Mirved64 commented
@Nelfimov 

**Скоуп**
`Figma`

**Описание**
Получить из `Figma` данные о точках градиента (их расположение) и угле градиента

**Мои действия**
- Гуглил. Нашел информацию для дизайнеров - как построить градиент. Нет информации как из макета достать данные о сложных градиентах (линейный под углом, радиальный).
- Нашел как получить данные цвета в точках градиента.
- Знаю, что градиент в `CSS` можно делать под любым углом. В `Figma` вижу наклон линии градиента, но как получить данные о наклоне угла не знаю.
- Пока не делал, но знаю о радиальном градиенте в `Figma` и `CSS`.

**Вопросы**
Как получить из `Figma` данные о точках градиента (их расположение) и угле градиента?

Чтобы построить градиенты как в первой секции (синей) нужно использовать несколько элементов `Background`?

2023-08-15 10:15 UTC, Nelfimov commented
> @Nelfimov
> 
> **Скоуп** `Figma`
> 
> **Описание** Получить из `Figma` данные о точках градиента (их расположение) и угле градиента
> 
> **Мои действия**
> 
> * Гуглил. Нашел информацию для дизайнеров - как построить градиент. Нет информации как из макета достать данные о сложных градиентах (линейный под углом, радиальный).
> * Нашел как получить данные цвета в точках градиента.
> * Знаю, что градиент в `CSS` можно делать под любым углом. В `Figma` вижу наклон линии градиента, но как получить данные о наклоне угла не знаю.
> * Пока не делал, но знаю о радиальном градиенте в `Figma` и `CSS`.
> 
> **Вопросы** Как получить из `Figma` данные о точках градиента (их расположение) и угле градиента?
> 
> Чтобы построить градиенты как в первой секции (синей) нужно использовать несколько элементов `Background`?

У блоков с фоном есть такое инфо. Пример:

<details>

<img width="1552" alt="image" src="https://github.com/atls-academy/Mirved64.github.io/assets/44067768/c3266b1e-993b-4a6a-ab28-d7a4ed8c629f">

</details>

2023-08-15 10:21 UTC, Mirved64 commented
@Nelfimov 

Как открыть такое меню?
У меня в фигме так:
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/ba6ac71b-961e-421f-a26d-d499306920e7)

И в копии макета такое:
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/c24b00c3-cdec-4024-a637-5c85f3c686b6)

2023-08-15 10:27 UTC, Nelfimov commented
Надо включить режим разработчика:

<details>

<img width="1552" alt="image" src="https://github.com/atls-academy/Mirved64.github.io/assets/44067768/b3ce2c03-ac81-4a39-a06e-3c4827aa1c37">

</details>

2023-08-15 14:47 UTC, Mirved64 commented
@Nelfimov 

**Скоуп**
Изменение положения секции

**Описание**

Не получается сделать как в макете, чтобы секции с закругленными углами "налезали" друг на друга
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/867e2392-2c3c-4a02-8f6a-a7270763d842)

**Мои действия**
- Закруглил углы у секции, получилось так:
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/a0bb1e0e-fe93-4bbd-a7e5-491925ded6bb)
- Пробовал задавать `translateY={['-64px', '-80px']}` для `Background` и компоненту `Courses`
- Менял `zIndex` для `Background` и компонента `Courses`, все равно не как в макете.

**Вопросы**
Как поднять секцию по `Y` и по `Z`, чтобы получилось как в макете?
Или это по другому делается?

ПР сделал, ветка актуальна

2023-08-15 19:14 UTC, Nelfimov commented
Можно через присвоение родителю `position: relative`, а детям `position: absolute` . Тогда детей можно будет двигать в рамках родителя.

2023-08-28 19:12 UTC, oksssvv requested changes

2023-08-28 19:12 UTC, oxiqod commented on landing/fragments/landing-about/src/about.component.tsx
> +      <Layout flexBasis={[64, 80]} />
к чему 2 лэйаута подряд?

2023-08-28 19:12 UTC, oxiqod commented on ui/theme/src/theme/colors.ts
>    divider: {
зайди в ui-kit академии и увидишь что дивидер это просто `Box`, дак зачем ему тогда отдельный объект с цветами, если выше есть `background`

2023-08-28 19:12 UTC, oxiqod commented on landing/fragments/landing-process/src/slider/slider.component.tsx
> +        <Slider images={imagesMobile} />
как то странно у тебя отображается здесь наложение

![Снимок экрана от 2023-08-28 21-30-36](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/8e7cc865-c814-4494-851e-d5afaccb2e85)

2023-08-28 19:12 UTC, oxiqod commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +        </Condition>
обрати внимание на переносы в макете

2023-08-28 19:12 UTC, oxiqod commented on landing/fragments/landing-hero/src/hero.component.tsx
> +                backgroundColor='ghostTransparentGradient'
цвет не по макету

2023-08-28 19:12 UTC, oxiqod commented on ui/accordion/src/accordion.component.tsx
> +                  lineHeight={['little', 'normal']}
`color` и `lineHeight`  не соответствуют макету

2023-08-28 19:12 UTC, oxiqod commented on ui/theme/src/theme/line-heights.ts
>  const lineHeights = {
эт чово такое, к чему эта писанина

в макете ж всегда прописывается межстрочный в процентах, так гораздо проще:
![Снимок экрана от 2023-08-28 21-51-55](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/f6c850fc-13c8-4733-9e2e-ed2ca8815a51)


вот как пример ск вышло у меня за все 7 степов: 
![Снимок экрана от 2023-08-28 21-48-44](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/4c844b1b-b074-4baf-b35c-d826b891448c)

2023-08-28 19:12 UTC, oxiqod commented on ui/accordion/src/accordion.component.tsx
> +                  lineHeight={['little', 'normal']}
а еще перенос `ответа` в десктопной версии

2023-08-28 19:12 UTC, oxiqod commented on ui/condition/package.json
зашла в `Condition` и интерфейс для него, а тебе точно нужен весь функционал который там находится?
например в проекте ни разу не использовались `smooth` и `smoothOptions`

попробуй ради любопытства зачистить полностью файл `condition.component.tsx`, и добавь туда вместо 75 строк кода одну - `export const Condition = ({match,children}) => match === true? children : null
`

2023-08-29 06:16 UTC, Mirved64 commented on landing/fragments/landing-process/src/slider/slider.component.tsx
> +        <Slider images={imagesMobile} />
@oksssvv 

Исправил в 5 степе

2023-08-29 07:39 UTC, Mirved64 commented on ui/accordion/src/accordion.component.tsx
> +                  lineHeight={['little', 'normal']}
> `color` и `lineHeight` не соответствуют макету

@oksssvv 

Проверил цвета. Цвет вопроса и цвет ответа в макете разные (как у меня). 
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/53742f1a-2f68-49ec-a50b-5d4504e056ba)

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/ddb3cde5-ad7c-4256-a706-9466639ba4d6)

</p>
</details>

2023-08-29 09:11 UTC, oksssvv commented on ui/accordion/src/accordion.component.tsx
> +                  lineHeight={['little', 'normal']}
@Mirved64 
![Снимок экрана от 2023-08-29 12-10-23](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/0ae442bd-31ae-4dc7-8d38-535f374755dc)

2023-08-29 12:15 UTC, oksssvv requested changes

2023-08-29 12:15 UTC, oksssvv commented on landing/fragments/landing-hero/src/hero.component.tsx
> +                backgroundColor='ghostTransparentGradient'
@Mirved64 ?

2023-08-29 12:15 UTC, oksssvv commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +        </Condition>
@Mirved64 ?

2023-08-29 12:15 UTC, oksssvv commented on ui/accordion/src/accordion.component.tsx
> +                  color='text.primaryText'
цвет ответа в моб. версии https://github.com/atls-academy/Mirved64.github.io/pull/15#discussion_r1308463455

2023-08-29 15:36 UTC, Mirved64 commented on landing/fragments/landing-hero/src/hero.component.tsx
> +                backgroundColor='ghostTransparentGradient'
> @Mirved64
> 
> > цвет не по макету
> 
> ?

@oksssvv 

Там же по макету градиет уже вместо простого цвета?

<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/6f4b80ca-5e00-4857-b079-2f3b36da496b)

</p>
</details>

2023-08-29 15:38 UTC, Mirved64 commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +        </Condition>
> @Mirved64
> 
> > обрати внимание на переносы в макете
> 
> ?

@oksssvv 

Если я правильно понимаю, то у меня был не правильный перенос в описании (буква и не перносилась), я это усправил в `ui/card`, уменьшив ширину. Или не так понял?

2023-08-30 08:17 UTC, oxiqod commented on landing/fragments/landing-hero/src/hero.component.tsx
> +                backgroundColor='ghostTransparentGradient'
@Mirved64 
твоя версия:
![Снимок экрана от 2023-08-30 11-12-49](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/737d8a12-d240-468f-ab8a-9dc6603b0951)

макет:
![Снимок экрана от 2023-08-30 11-12-55](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/be9b0ad9-3af4-4255-add9-f2b929bf448a)

возможно такое отображение из-за заднего фона, у тебя немного темнее, а цвет бокса прозрачный, но не думаю что это критично

- но глядя на скрины заметен разный размер букв  `IT` , надо поправить

2023-08-30 08:24 UTC, oksssvv commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +        </Condition>
@Mirved64 
твоя версия:
![Снимок экрана от 2023-08-30 11-19-21](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/f6c3eba8-aab4-4356-aea1-8d733a55518e)

макет:
![Снимок экрана от 2023-08-30 11-19-09](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/9ca3f86c-9502-4795-b2c7-e2e459f418c4)

отличия:
1. перенос
2. цвет дескрипции

2023-08-30 13:32 UTC, Mirved64 commented on landing/fragments/landing-hero/src/hero.component.tsx
> +                backgroundColor='ghostTransparentGradient'
@oksssvv 

Может хром так отрисовывает градиент? 

По параметрам `background` градиент как в макете. Если заменить в градиенте цвета на более контрастный (красный или зеленый), то виден переход.

2023-08-30 15:55 UTC, oksssvv approved these changes

2023-08-31 06:41 UTC, Mirved64 commented on landing/fragments/landing-courses/src/info/info.component.tsx
> +      </Box>
@TorinAsakura 

Исправил замечание про `inline` из третьего шага. 
Чтобы не ломалась верстка на промежуточных вьюпортах, пришлось разбивать фразу чуть ли не по словам. 
`inline` проще использовать, он лучше справляется с задачей на малых вьюпортах и меньше кода выходит.

2023-08-31 10:29 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/info/info.component.tsx
> +      </Box>
проблема в том, что у тебя не должна ломаться вёрстка из-за текста
покажи фрагмент дизайна который ты реализовывал

2023-08-31 10:35 UTC, Mirved64 commented on landing/fragments/landing-courses/src/info/info.component.tsx
> +      </Box>
@TorinAsakura 

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/0069c82a-6b36-4924-aa9b-fc88a3f0c077)

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/7b433b21-cb4f-4a83-9024-ec4563f53472)

2023-08-31 13:05 UTC, Nelfimov requested changes
Особенно обрати внимание на версии - например `@emotion/react` ге то используется в `peer`, где-то нет. Запусти для пример `yarn why @emotion/react` - именно столько версий у тебя плодит приложение. Можешь пройтись так же по остальным пакетам, напр. `react`, `framer-motion`.

2023-08-31 13:05 UTC, Nelfimov commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +        (card) => card.category === 'обучение' || card.category === 'мини-курс'
Лучше конечно же 'обучение' и пр. сделать `enum`. А иначе выходит мы закодировали в явном виде локализацию.

2023-08-31 13:05 UTC, Nelfimov commented on ui/navbar/src/navbar.component.tsx
> +export const Navbar = ({ sectionRefs }) => {
Не прописан интерфейс пропсов.

2023-08-31 13:05 UTC, Nelfimov commented on ui/drawer/src/renderer/renderer.component.tsx
> +const Renderer = ({ children, active }) => {
Нет интерфейса пропсов.

2023-08-31 13:05 UTC, Nelfimov commented on ui/accordion/src/accordion.component.tsx
> +export const Accordion = ({ answer, question, isDivider = true }) => {
Нет интерфейса пропсов.

2023-08-31 13:05 UTC, Nelfimov commented on landing/fragments/landing-technologies/src/technologies.component.tsx
> +  <Column width='100%'>
`fill`

2023-08-31 13:05 UTC, Nelfimov commented on landing/fragments/landing-steps/src/steps.component.tsx
> +export const Steps = () => {
Нет интерфейса пропсов

2023-08-31 13:05 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +export const Navigation = ({ sectionRefs }) => {
Нет интерфейса пропсов.

2023-08-31 13:05 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +      <Drawer active={active} onClose={() => setActive(false)} sectionRefs={sectionRefs} />
Вынеси `() => setActive(false)` в тело компонента и объяви для него функцию.

2023-08-31 13:05 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/drawer/drawer.component.tsx
> +export const Drawer = ({ active, onClose, sectionRefs }) => {
Нет интерфейса пропсов.

2023-08-31 13:05 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/drawer/drawer.component.tsx
> +  const cardsList = () =>
Мне кажется здесь можно обойтись константой а не функцией.

2023-08-31 13:05 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/data/data-navlinks.ts
> +export const NavLinks = [
Сделай простенький интерфейс сюда.

2023-08-31 13:05 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/data/data-card.ts
> +export const CardDataDesktop = {
Так же можно сделать интерфейс

2023-08-31 13:05 UTC, Nelfimov commented on landing/fragments/landing-faq/src/faq.component.tsx
> +  const Items = () =>
Нужна ли здесь именно функция?

2023-09-01 07:14 UTC, Mirved64 commented on landing/fragments/landing-steps/src/steps.component.tsx
> +export const Steps = () => {
@Nelfimov 

Но ведь у компонента Steps нет пропсов, а компоненту Item прописан интерфейс. 
Или я не так понял?

2023-09-01 07:24 UTC, Nelfimov commented on landing/fragments/landing-steps/src/steps.component.tsx
> +export const Steps = () => {
Да, ошибся.

2023-09-01 11:13 UTC, Mirved64 commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +        (card) => card.category === 'обучение' || card.category === 'мини-курс'
@Nelfimov 

**Скоуп**
работа с `enum`

**Описание**
Как правильно использовать `enum`

**Мои действия**

Я создаю `enum`:
```
enum Category {
  Teach = 'обучение',
  MiniCourse = 'мини-курс',
  EducationalMaterial = 'учебный материал',
}
```
Теперь в ключе `category` интерфейса `CardProps` ставлю `Category`: 
```
interface CardProps {
  id: number
  isMobileOnly?: boolean
  category: Category
  title: string
  descriptionMobile?: string
  descriptionDesktop?: string
}
```

Соответсвенно в массиве карточек, в `category` пишу `Category.Teach`, либо `Category.MiniCourse` или `Category.EducationalMaterial`.

А в условии `filter` оставляю как есть на обозначенном куске кода.

**Вопрос**

Правильно ли я использую `enum`?

2023-09-04 09:39 UTC, Nelfimov commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +        (card) => card.category === 'обучение' || card.category === 'мини-курс'
В фильтре тоже надо прописать через `Category.Teach` и т.д.

2023-09-04 09:41 UTC, Nelfimov requested changes
Доделать `enum`

2023-09-04 11:21 UTC, Nelfimov approved these changes

2023-09-05 22:13 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/info/info.component.tsx
> +      </Box>
так и в чём тут проблема? для чего тебе инлайн? 
- ограничиваешь ширину блока
- разрешаешь перенос слов
- = вы великолепны

2023-09-06 21:55 UTC, TorinAsakura requested changes

2023-09-06 21:55 UTC, TorinAsakura commented on landing/fragments/landing-navigation/src/drawer/drawer.component.tsx
> +  const cardsList = Array.from({ length: 3 }, () => CardDataDesktop).map((el, index) => ({
1. `Condition` удобен, но слишком много их может запутать. Подумай о разбиении на подкомпоненты
2. `CardDataDesktop` и `CardDataMobile` лучше вынести в константы, если они не меняются.
3. В `DrawerProps` уточни тип для `sectionRefs`.
4. В коде есть повторяющиеся блоки. Подумай в сторону DRY

2023-09-06 21:55 UTC, TorinAsakura commented on landing/fragments/landing-navigation/src/navigation.component.tsx
> +import { FC }               from 'react'
1. `handleClose` и `handleOpen` можно объединить в одну функцию, которая переключает состояние `active`
2. `isMobile` и `isDesktop` используются в `Condition`. Если у тебя только два состояния (мобильный/десктоп), можно обойтись одной переменной
3. `NavLinks.map` — хорошо, но учти, что если `NavLinks` будет динамическим, лучше использовать `useMemo` для оптимизации

2023-09-07 23:40 UTC, TorinAsakura requested changes
почти

2023-09-07 23:40 UTC, TorinAsakura commented on landing/fragments/landing-navigation/src/drawer/drawer.component.tsx
> +export const DrawerMobile: FC<MobileDrawerProps> = ({ active, onClose }: MobileDrawerProps) => (
это точно в отдельный компонент, не делай таких огромных компонентов

2023-09-08 16:30 UTC, TorinAsakura requested changes

2023-09-08 16:30 UTC, TorinAsakura commented on landing/fragments/landing-navigation/src/item/item-drawer.component.tsx
> +export const ItemDrawer: FC<ItemDrawerProps> = ({
что такое item? не понятна топология:
navigation -> drawer
navigation -> item ~> DrawerItem
…

2023-09-11 23:49 UTC, TorinAsakura approved these changes

2023-09-11 23:49 UTC, merged