feat/landing-fifth-step
atls-academy/Mirved64.github.io pull request #17
Opened 2023-08-25 06:51 UTC by Mirved64

Close #16

2023-08-28 05:56 UTC, Mirved64 commented
@Nelfimov 

**Скоуп**
Отображение `image` в `background` 

**Описание**
Не отображается картинка на фоне на странице `library`, хотя в браузере в свойстве `backgrownd` картинка есть

**Мои действия**
- Обернул в компонент `Background` нужные компоненты, задал пропсы как в `IndexPage` - на главной странице всё хорошо, в странице библиотеки картинка не отображается, хотя цвет `Background`а отображается (синий сложный градиент);
- Менял путь к картинке в `/theme/backgrounds.ts`, ориентируясь на положение папки `library` к корневой папке приложения - результат как в предыдущем;
- Перемещал картинки из папки `/public/image` в папку `/public`, менял путь - результат как в предыдущем;

**Вопрос**
- В чем может быть ошибка? Может я что-то упустил при добавлении в `LibraryPage`. Хотя стиль градиента применился и проблема только в отображении фоновых картинок.

ПР сделал, ветка актуальна

2023-08-28 07:43 UTC, Nelfimov commented
У тебя картинка подгружается, просто ты в нее обернул:

```
<Navigation/>
<Library/>
```

Попробуй оберни только <Navigtaion/> и увидишь свой фон. Далее надо переформатировать фрагменты в <Library/>.

2023-09-06 12:42 UTC, oxiqod requested changes

2023-09-06 12:42 UTC, oksssvv commented on landing/fragments/landing-library/src/library.component.tsx
> +  const searcButton = (
search*

2023-09-06 12:42 UTC, oksssvv commented on ui/button/src/attachment/attachment.interfaces.ts
> +  icon?: any
можно типизировать

2023-09-06 12:42 UTC, oksssvv commented on ui/input/src/attachment/attachment.interfaces.ts
> +  icon?: any
можно типизировать

2023-09-06 12:42 UTC, oksssvv commented on ui/input/src/input.interfaces.ts
> +  filled?: boolean | string | undefined
он ж и так необязательный, `undefined` можно не указывать

2023-09-06 12:42 UTC, oksssvv commented on ui/navbar/package.json
насчет самого навбар компонента:

- у тебя там как то странно моргают элементы при переходе между секциями
(вот на скрин успела поймать)
![Снимок экрана от 2023-09-06 15-38-04](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/552d1b20-f886-4329-8a70-02cf1b3d58f6)

- и как поняла, круглый элемент не на переднем плане, `zIndex` поможет

![Снимок экрана от 2023-09-06 15-37-42](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/faa4b906-dd0d-42f7-9a5e-9569f7142b19)

2023-09-07 05:25 UTC, Nelfimov requested changes
Баги в UI:

1. Параллакс работает только в первой секции 
2. Кнопка "Все материалы" не скроллит в нужную секцию
3. "IT" улетело

<details>

<img width="1381" alt="image" src="https://github.com/atls-academy/Mirved64.github.io/assets/44067768/7aee86c9-69f9-4461-9b0e-d63d48361528">

</details>

2023-09-07 13:57 UTC, Mirved64 commented
> 2. Кнопка "Все материалы" не скроллит в нужную секцию

@Nelfimov 

Кнопка же перекидывает на страницу библиотеки.
Или я не так понял функционал кнопки?

2023-09-07 15:16 UTC, Nelfimov commented
> > 3\. Кнопка "Все материалы" не скроллит в нужную секцию
> 
> @Nelfimov
> 
> Кнопка же перекидывает на страницу библиотеки. Или я не так понял функционал кнопки?

Виноват - имел в виду "Процесс поступления" - https://www.figma.com/file/SHoss54mn2SZLnI0e3OiJj/Practice?node-id=2068%3A3569&mode=dev

2023-09-08 09:57 UTC, Nelfimov requested changes
- [ ] IT по прежнему улетает
- [ ] Параллакс первой секции очень рано начинается, не видно текста. Приложил скрин с разрешением:

<details>

<img width="1381" alt="image" src="https://github.com/atls-academy/Mirved64.github.io/assets/44067768/cbe5207a-ae86-4a37-9657-64fb87d68dd8">

</details>

2023-09-08 10:57 UTC, Mirved64 commented
> * [ ]  IT по прежнему улетает

@Nelfimov 

С `IT` очень странное поведение. 

У меня нет такого даже на меньших вьюпортах.
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/63584169-4589-4310-9d50-9ecbbf386cc2)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/6f3237f6-dd35-48e0-a33b-8231e70a521a)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/e2951c47-d5d5-4758-a8d5-0533ee90144b)

</p>
</details> 

Возможно шрифт отображается по другому. 

А параллакс так сбился, скорее всего из-за дополнительной строчки вследствие переноса в слогане.

2023-09-08 11:32 UTC, Nelfimov requested changes
В некоторых местах дублриуешь интерфейс компонент - почему так?

2023-09-08 11:32 UTC, Nelfimov commented on ui/button/src/attachment/attachment.interfaces.ts
> +  icon?: object
`object` = `any` - нехорошо. Тебе же ожидаешь JSX элемент. Можно хоть `ReactNode` попробовать.

2023-09-08 11:32 UTC, Nelfimov commented on landing/fragments/landing-faq/src/question-modal/question-modal.component.tsx
> +                      {name}, спасибо!
Хардкод локали.

2023-09-08 11:32 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/navigation-index.component.tsx
> +export const NavigationIndex: FC<NavigationProps> = ({ sectionRefs }: NavigationProps) => {
`{ sectionRefs }: NavigtaionProps` - не нужно. Ты в `FC<NavigationProps>` уже все указал.

2023-09-08 11:32 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/item/item.component.tsx
> +export const Item: FC<ItemProps> = ({ name, path }: ItemProps) => {
Дублирование интерфейсов

2023-09-08 11:32 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/item/item-drawer.component.tsx
> +}: ItemDrawerProps) => {
Дублирование интерфейсов

2023-09-08 11:32 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/item/item-navlinks.component.tsx
> +export const ItemNavLink: FC<ItemProps> = ({ name, path, active }: ItemProps) => {
Дублирование интерфейсов.

2023-09-08 11:57 UTC, Mirved64 commented
> В некоторых местах дублриуешь интерфейс компонент - почему так?

@Nelfimov 
Если не применять к пропсам интерфейс, то они высвечиваются как `any`.

2023-09-08 12:01 UTC, Nelfimov commented
> > В некоторых местах дублриуешь интерфейс компонент - почему так?
> 
> @Nelfimov Если не применять к пропсам интерфейс, то они высвечиваются как `any`.

Очень странно. Какая версия IDE? Можешь дать скрин компонента где `any`?

2023-09-08 12:04 UTC, Mirved64 commented
> > > В некоторых местах дублриуешь интерфейс компонент - почему так?
> > 
> > 
> > @Nelfimov Если не применять к пропсам интерфейс, то они высвечиваются как `any`.
> 
> Очень странно. Какая версия IDE? Можешь дать скрин компонента где `any`?

@Nelfimov 
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/4cc0bb01-ef0d-42e8-a9a8-a3d426ae7188)

</p>
</details> 

IDE - VSCode v.1.82.0

2023-09-08 16:22 UTC, Mirved64 commented
> > > В некоторых местах дублриуешь интерфейс компонент - почему так?
> > 
> > 
> > @Nelfimov Если не применять к пропсам интерфейс, то они высвечиваются как `any`.
> 
> Очень странно. Какая версия IDE? Можешь дать скрин компонента где `any`?

@Nelfimov 

`WS` тоже без интерфейса не пропсах пишет `any`
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/5f6aa370-a5c7-49f7-9b94-f260f25bc160)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/34786e0d-ec9c-4ae9-8e65-ae496c121034)

</p>
</details>

2023-09-11 15:53 UTC, Nelfimov commented
> `WS` тоже без интерфейса не пропсах пишет `any`

 У меня есть:

<details>

<img width="1440" alt="Screenshot 2023-09-11 at 18 51 25" src="https://github.com/atls-academy/Mirved64.github.io/assets/44067768/60e8aa6f-f151-431d-8701-7f97b6f16f25">

</details>

Проверь настройки, у тебя даже для стейта нет интерфеса `initialState`

2023-09-12 11:55 UTC, Nelfimov approved these changes

2023-09-23 17:45 UTC, oksssvv approved these changes
по проекту сплошное покрытие типизацией, мне есть чему у тебя поучиться) молодец!

2023-09-23 17:45 UTC, oxiqod commented on ui/accordion/src/accordion.component.tsx
а чего у тебя там иконки рядом с этим файлом лежат? для них же есть отдельная ui директория

2023-09-23 17:45 UTC, oksssvv commented on ui/drawer/src/renderer/renderer.component.tsx
> +const Renderer: FC<RendererProps> = ({ children, active }) => {
children : ReactNode

2023-09-23 17:45 UTC, oksssvv commented on ui/logo/src/logo.component.tsx
у тебя в директории src лежит 2 компонента и 2 интерфейса, т.к. ты экспортируешь только лого для использования, то правильнее было для иконки с ее интерфейсом выделить отдельную папку

2023-09-25 17:04 UTC, TorinAsakura requested changes
отпадно! воистину!! чуть-чуть прям дотыкать

2023-09-25 17:04 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/question-modal/question-modal.component.tsx
> +import { QuestionModalProps } from './question-modal.intarfaces'
typo

2023-09-25 17:04 UTC, TorinAsakura commented on landing/fragments/landing-library/src/card/card.component.tsx
> +    if (hover) return 'accentPurpur'
что такое purpur?

2023-09-25 17:04 UTC, TorinAsakura commented on landing/fragments/landing-library/src/card/card.component.tsx
> +                  padding='10px 12px 10px 12px'
в тему

2023-09-25 17:04 UTC, TorinAsakura commented on landing/pages/index-page/src/index.page.tsx
> +              backgroundSize='4400px 800px'
полагаю и это должно жить в теме?

2023-09-25 17:04 UTC, TorinAsakura commented on ui/form/src/form.interfaces.ts
> +  onClose: () => void
почем войд? это ведь такое же событие как и онКлик

2023-09-25 17:04 UTC, TorinAsakura commented on ui/modal/src/backdrop/backdrop.styles.ts
> +  backgroundColor: 'rgba(0, 0, 0, 0.5)',
тема?

2023-09-27 12:56 UTC, TorinAsakura approved these changes

2023-09-27 12:56 UTC, merged