feat/landing-sixth-step
atls-academy/Mirved64.github.io pull request #19
Opened 2023-08-31 10:21 UTC by Mirved64

Close #18

2023-08-31 16:34 UTC, Mirved64 commented
@Nelfimov 

**Скоуп**
кастомные брейкпоинты

**Описание**
Если использовать кастомные брейкпоинты, то пропс, к которому они применяются не работает.

**Мои действия**

Создал `breakpoints.ts` добавил в `index.ts` в `ui/theme`. 

Сделал на главной странице красный `Box` с `height={{standard: 500, wide: 600, ultra:700}}`. В `DOM` бокс не отображается, пишет `height="[object Object]"`.

Читал доку к `styled-system`, чат Академии. В чате Вы писали, что нужно указывать для кастомных брейкпоинтов значения в виде объекта. Но так работать не хочет.

**Вопрос**
Что я упустил при настройки и использованию кастомных брейкпоинтов?

ПР сделал, ветка актуальна.

2023-08-31 18:09 UTC, oksssvv commented
@Mirved64 Покажи пожалуйста файл ‘breakpoints.ts’ из темы, и то как ты применяешь брейкпоинты в ‘display’, непосредственно в компонентах

2023-08-31 18:15 UTC, TorinAsakura commented
@oksssvv Он же написал, что ветка актуальна

2023-08-31 18:40 UTC, oksssvv commented
@Mirved64 

в общем дело такое:

`small` как ты назвал, я так понимаю это мобильное устройство? 
- если так - то его брейкпоинт я не вводила, он априори менее обычного `Standard` / `FullHD` поэтому его можно не прописывать, да и версия для планшика в макете не предусматривается 

- т.е. у тебя условно идут такие точки останова - `[ '80em', '160em', '240em']`
где `80em - standard`, `160em - wide` и `240em - ultra`, а то что менее первого бейкпоинта - мобилка

- указывая значения в виде объекта всё будет работать, + мобильную версию прописывай символом `_` (можешь поиграться с другими вариантами - не пробовала)

попробуй завтра, если не получится - пиши, + сразу скажу, после изменения значений брейкпоинта в теме -  отображения по новым брейкпоинтам на странице не будет, даж если стр перезагрузить, нужно перезапускать локалхост

2023-09-01 05:37 UTC, Mirved64 commented
> @Mirved64
> 
> в общем дело такое:
> 
> `small` как ты назвал, я так понимаю это мобильное устройство?
> 
> * если так - то его брейкпоинт я не вводила, он априори менее обычного `Standard` / `FullHD` поэтому его можно не прописывать, да и версия для планшика в макете не предусматривается
> * т.е. у тебя условно идут такие точки останова - `[ '80em', '160em', '240em']`
>   где `80em - standard`, `160em - wide` и `240em - ultra`, а то что менее первого бейкпоинта - мобилка
> * указывая значения в виде объекта всё будет работать, + мобильную версию прописывай символом `_` (можешь поиграться с другими вариантами - не пробовала)
> 
> попробуй завтра, если не получится - пиши, + сразу скажу, после изменения значений брейкпоинта в теме - отображения по новым брейкпоинтам на странице не будет, даж если стр перезагрузить, нужно перезапускать локалхост

@oksssvv 

После рестарта локалхоста бокс отображается с высотой как прописано  в `ultra`, т.е. `700px`. А вот при изменении вьюпорта брейкпоинт не срабатывает и высота не меняется.

Пробовал брейкпоинты задавать в `em`, `px`, просто числом и перезапускал локалхост - результат отрицательный.
Пробовал высоту задавать в `em`, `px`, просто числом и перезапускал локалхост - результат отрицательный.

2023-09-01 06:17 UTC, oksssvv commented
@Mirved64 
последний коммит - актуальное состояние? 
всё еще вижу там `small` в брейкпоинтах

2023-09-01 06:22 UTC, Mirved64 commented
@oksssvv 

актуальное
убирал `small`, так же результат отрицательный

2023-09-01 06:31 UTC, oksssvv commented
@Mirved64 Ну как оно актуальное, если в брейкпоинтах я вижу small? 

я ж писала в данном случае достаточно указать standard, wide & ultra  и разберись сначала с брейкпоинтами, а затем, зная что они работают правильно, будешь делать useWindowWidth

2023-09-01 06:34 UTC, Mirved64 commented
@oksssvv 

В ближайшее время внесу правки с учетом замечаний.

2023-09-01 07:06 UTC, Mirved64 commented
@oksssvv 

Твой файл брейкпоинтов сработал. Благодарю за оперативную помощь.

Только смущает что линт отключать нужно при деструктуризации массива (когда присваиваем ключам объекта `breakpoints` значения элементов массива). Но при разрешенных способах деструктуризации брейкпоинты ломаются.

Еще раз спасибо!

2023-09-19 08:15 UTC, Mirved64 commented
@Nelfimov 

**Скоуп**
Анимация по нажатию

**Описание**
Реализовать анимацию `HEADER` в проекте

**Мои действия**
- сделал хук [useDimensions](https://www.reddit.com/r/reactjs/comments/b0oh20/usedimensions_a_react_hook_to_measure_dom_nodes/), чтобы получать `height`, `top`, `y` у секций сайта - не могу получить доступ к полям `height`, `top`, `y`, `IDE` пишет что нет таких полей, хотя я указал `type`;
- задал [controls](https://www.framer.com/motion/use-animation-controls/#dynamic-start), для контроля анимации (запуска по клику на ссылку в хедере) - не понимаю как прокинуть `controls` в хедер, чтобы по клику запустить анимацию;
- думаю как указать промежуточные фреймы в анимации (поднять секцию на .25, .5 и .75 от высоты первой секции), чтобы анимация работала и на `wide` и на `ultra` вьюпортах.

**Вопросы**
- Правильно ли я рассуждаю о том как реализовать анимацию?
- Как использовать `useDimensions` если уже задан `ref` домузлу?
- Как реализовать запуск анимации по клику? (Прокинуть `controls` и написать функцию)
- Правильно ли я понимаю значения анимации на промежуточных фреймах?

ПР сделал, ветка актуальна.

2023-09-19 09:08 UTC, Nelfimov commented
> * Правильно ли я рассуждаю о том как реализовать анимацию?

Отвечу на этот вопрос так чтобы остальные тоже не остались без ответа 😁

Тебе достаточно сверстать элемент, который в изначальном состоянии находится за вьюпортом вверху, то есть `top: -100%`.

Этому компоненту надо передавать буленовский пропс, по которому он будет определять - показываться/выезжать или прятаться/заезжать. Анимация сводится к простому перемещению по оси Y.

Буленовский пропс будет у тебя стейтом, который изменяется по нажатию кнопки. Соответственно ты можешь:
- либо обозначить этот стейт в общем родителе у кнопки и анимированного компонента
- либо создать контекст и из него получать пропс

2023-09-19 09:24 UTC, Mirved64 commented
> > * Правильно ли я рассуждаю о том как реализовать анимацию?
> 
> Отвечу на этот вопрос так чтобы остальные тоже не остались без ответа 😁
> 
> Тебе достаточно сверстать элемент, который в изначальном состоянии находится за вьюпортом вверху, то есть `top: -100%`.
> 
> Этому компоненту надо передавать буленовский пропс, по которому он будет определять - показываться/выезжать или прятаться/заезжать. Анимация сводится к простому перемещению по оси Y.
> 
> Буленовский пропс будет у тебя стейтом, который изменяется по нажатию кнопки. Соответственно ты можешь:
> 
> * либо обозначить этот стейт в общем родителе у кнопки и анимированного компонента
> * либо создать контекст и из него получать пропс

Я ошибся с названием анимации. 
Нужно анимацию `header-nav-1` реализовать

2023-09-19 10:48 UTC, Nelfimov commented
> > > * Правильно ли я рассуждаю о том как реализовать анимацию?
> > 
> > 
> > Отвечу на этот вопрос так чтобы остальные тоже не остались без ответа 😁
> > Тебе достаточно сверстать элемент, который в изначальном состоянии находится за вьюпортом вверху, то есть `top: -100%`.
> > Этому компоненту надо передавать буленовский пропс, по которому он будет определять - показываться/выезжать или прятаться/заезжать. Анимация сводится к простому перемещению по оси Y.
> > Буленовский пропс будет у тебя стейтом, который изменяется по нажатию кнопки. Соответственно ты можешь:
> > 
> > * либо обозначить этот стейт в общем родителе у кнопки и анимированного компонента
> > * либо создать контекст и из него получать пропс
> 
> Я ошибся с названием анимации. Нужно анимацию `header-nav-1` реализовать

@oksssvv призываю тебя

2023-09-19 13:11 UTC, oxiqod commented
@Mirved64 оч мало что поняла, ты написал реализовать анимацию хедера в проекте, какая именно анимация? (на сколько помню там с анимацией связанны 2 вещи, drawer и скролл до секции ), можно контекст в дизайне, в коде? 
краткое описание что для чего должно быть сделано и как выглядеть в итоге?
пока не понимаю даж зачем тебе кастомный хук делать

2023-09-19 13:29 UTC, Mirved64 commented
@oksssvv
В макете, в 6 степе есть фрейм `header-nav-1`.  

Вот её не получается реализовать.

Там при клике по ссылке `ACADEMY` когда в самом низу страницы проигрывает я анимация - секции поднимаются до определённой точки (у каждой секции своя) и спускаются. 

Вот для задания этих точек каждой секции пишу хук, он пока не работает. 

Как по клику сделать анимацию я разобрался.

2023-09-19 16:15 UTC, oksssvv commented
@Mirved64
правильно ли поняла, что при клике по `ACADEMY` в навигации, вьюпорт должен прокуртится по конца `Hero`?
всё остальное у тебя работает?

2023-09-19 16:29 UTC, Mirved64 commented
@oksssvv

Не уверен что правильно понял реализацию анимации. 
Не могу из хука получить высоту элемента. 
В хуке нужно указать реф на элемент - не разберусь как правильно сделать: хочу получать высоту секции `academy`, но на ней уже есть реф

2023-09-23 22:33 UTC, oksssvv requested changes
ну и напоследок по внешке:

#### standard
  - слишком рано перекрывается секция курсов
<details>

![Снимок экрана от 2023-09-24 01-03-41](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/b2367512-cb0f-4414-b9eb-9fcc6e026bf1)
</details>

#### wide
  - отступ справа у карт учебного материала и высота самих карточек не 320
  - высота бокса категории
  - секция слишком рано перекрывается следующей
<details>

![Снимок экрана от 2023-09-24 01-07-14](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/4427370f-7a7d-4d11-be88-e52d36cf5ab6)
emy/Mirved64.github.io/assets/126156026/7243dfbe-2eed-45ef-af5d-89ba9ca59253)
</details>

#### ultra
  - драйвер не на всю ширину страницы
  - ширина бокса категорий в драйвере
  - фоновая декорация в степах
  - материалы в library, разве дизайном предусмотрено изменение верстки в библиотеке под широкие экраны? смотрится странно
<details>

![Снимок экрана от 2023-09-24 01-11-07](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/bd8abff5-c380-4c90-8eab-b8f6c9a2d3ae)

![image](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/31a4e805-b9e6-4548-a229-6174e6e404ad)

![Снимок экрана от 2023-09-24 01-26-27](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/2fd1c495-2bf0-4386-bb04-ebd503ea5e93)


</details>

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-about/src/about.component.tsx
> +            <Text color='text.white' fontSize='small' lineHeight='huge'>
заметила что одинаковая часть верстки используется 7 раз, можно вынести `Box` и `Text` в отдельный компонент и далее переиспользовать

<details>

![Снимок экрана от 2023-09-23 20-58-18](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/a32ddb48-0d5f-4763-b74d-ebe6c13196ef)
</details>

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +  const { isWideDesktop, isTV } = useWindowWidth()
`isTV`?)
нет, эт просто большая диагональ монитора, с большей плотностью пикселей)

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-courses/src/cards/cards.component.tsx
> +}
такс, почему здесь 4 экспортируемых компонента? давай дели ответственность файла на несколько директорий)

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-courses/src/info/info.component.tsx
> +        >
ситуация как и в `about`,  11 одинаковых кусков верстки, если переиспользовать `Box` и `Text` то выйдет  строк на 60 меньше кода в файле 

<details>

![Снимок экрана от 2023-09-23 21-20-11](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/9265e270-1139-43ea-ae36-3bf84ded1417)
</details>

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-header/src/header-index.component.tsx
> +export const HeaderIndex: FC<HeaderIndexProps> = ({
так дела не делаются компонент слишком раздутый, нужна хоть какая то модульность, как минимум вынеси `drawerCards` отдельно

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-header/src/header.component.tsx
> +  const drawerCards = cardsList.map((card, index, array) => {
тоже самое, они ж вроде одинаковые с тем `drawerCards` который в `header-index.component.tsx`, в любом случае его нужно вынести отдельно и применить тогда уже в двух компонентах

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-header/src/header.component.tsx
> +          {visible ? (
`Condition`

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-header/src/header-index.component.tsx
> +          {visible ? (
`Condition`

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-hero/src/hero-wide.component.tsx
зачем нужен отдельный компонент для широкого экрана? все можно реализовать в `hero.component.tsx`,  к чему дублировать верстку в данном случае?

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-hero/src/social-link/social-link.component.tsx
> +export const SocialLinkUltra: FC<SocialLinkProps> = ({ icon, href }) => (
в этом случае, например, вместо 3х компонентов можно сделать один, использовать  `enum` для определения значений `Mobile`,`Desktop` и `Ultra`, и при помощи `Condition` возвращать нужные кнопки

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-library/src/card/card.component.tsx
>    const getColor = (): string => {
вынеси отдельно

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-library/src/library.component.tsx
>    const searchButton = (
нужно вынести

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-library/src/library.component.tsx
>    const getColor = (): string => {
нужно вынести

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-library/src/library.component.tsx
>    const [searchQuery, setSearchQuery] = useState('')
стрейты тоже можно типизировать

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-library/src/library-mobile.component.tsx
какая необходимость делать отдельный компонент для мобильной версии? у тебя для того что бы воплотить всё в одном компоненте есть инструменты: кондишн и брейкпоинты

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-library/src/card/card.component.tsx
по логике если компонентом `card` пользуется только компонент `cards`, то и директория должна располагаться в `cards` а не в `src`

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-navigation/src/index.ts
> +export * from './data'
шо происходит, куда тебе столько всего? поч для мобилки отдельный компонент? почему `navigation-index.component` не в отдельной директории

если я что то не догнала, то объясни

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-navigation/src/navlink-item/navlink-item-index.component.tsx
почему в директории `navlink-item` 4 компонента? тут нужно думать над сменой структуры

![Снимок экрана от 2023-09-23 23-41-08](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/815afefb-3c6b-446e-b72f-fd8d59f10705)

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-process/src/process.component.tsx
> +      <Condition match={isWideDesktop || isTV}>
color, fontSize, lineHeight и все остальные тоже их принимают брейкпоинты, зачем дублировать текст 

посмотри реализацию этого же компонента: [process](https://github.com/atls-academy/oksssvv.github.io/blob/master/landing/fragments/landing-process/src/process.component.tsx)

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-steps/src/step/step.component.tsx
в интерфейсе у тебя для всех пропсов указан `?`, хотя как я посмотрела действительно необязательный только `divider`
на выходе получается вот такой вот интерфейс:
```

export interface StepProps {
  sequenceNumber: string | undefined
  name?: string | undefined
  description?: string | undefined
  divider?: boolean | undefined
}
```

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-steps/src/steps.component.tsx
> +        <Condition match={isTV}>
тоже можно переиспользовать, меняется только `width` `height` и брейкпоинт

пример компонента:

```

<Condition match={ breakpoint }>
          <Box
            width={ width }
            height={ height }
            position='absolute'
            zIndex={10}
            margin='auto'
            top='0'
            left='0'
            bottom='0'
            right='0'
          >
            <Image src='./image/Cubics.png' width={ width } height={ height } />
          </Box>
        </Condition>
```

( есть еще другой вид реализации, можешь подсмотреть [Steps](https://github.com/atls-academy/oksssvv.github.io/blob/master/landing/fragments/landing-steps/src/steps.component.tsx#L40-L46) )

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-steps/src/steps.component.tsx
>        <Layout flexBasis={[24, 160]} />
зачем кондишн если максимальный лэйаут уже 160? 
поняла, тебе удвоить нужно, дак: `<Layout flexBasis={{_:24, standard:160, ultra:320}} />`

2023-09-23 22:33 UTC, oxiqod commented on landing/fragments/landing-technologies/src/technologies.component.tsx
>        <Layout flexBasis={[32, 64]} />
`<Layout flexBasis={{_:32, standard:64, wide:128, ultra:64}} />` ?

2023-09-23 22:33 UTC, oxiqod commented on landing/pages/library-page/src/library.page.tsx
> +  const { isMobile, isDesktop, isWideDesktop, isTV } = useWindowWidth()
ну для начала, зачем повторять слово десктоп в `isWideDesktop`, у тебя ж уже есть подходящие имена для ширин экранов: mobile, desktop, wide и ultra

2023-09-23 22:33 UTC, oxiqod commented on landing/pages/library-page/src/library.page.tsx
>    return (
что начинается дальше, я даж не вкурила, дай ссылку на анимацию в фигме, у меня видимо чет глючит, я вижу только скролл до хедера и не более, а уж тем более не вижу анимаций на странице библиотеки

2023-09-23 22:33 UTC, oksssvv commented on landing/fragments/landing-hero/src/social-link/social-link.component.tsx
> +    <Link href={href}>
сделай открытие ссылок в новой вкладке

2023-09-27 11:32 UTC, Mirved64 commented
@oksssvv, @Nelfimov 

**Скоуп**

Отображение градиента как `backgroundImage`

**Описание**

В `ui/slider` не отображается градиент фона слайдера, в компоненте `courses` не отображается градиент фона карточки-ссылки на библиотеку.
Не работают градиенты в `theme/backgrounds.ts` под ключами:

1. `navyGradient`
2. `purpleGradient`
3. `darkPurpleGradient`

в браузере пишет `invalid property value`

**Мои действия**
- гуглил - советуют поставить прификсы к градиенту, но это не помогает;
- Проверял значения градиентов, опечатки в ключах, опечатки в значении пропса `backgroundImage`;
- Если подставить вместо обозначенных выше градиентов такие значения как `navyBlueGradient` или `darkPurpleGradientFlash` - градиенты отображаются;
- Если в браузере вместо пропса `background-image` задать `background`, то градиенты отображается;
- Если хард кодом вставить в пропс `backgroundImage` строку градиента, например `darkPurpleGradient` - градиент не отображается.
- Если хард кодом вставить в пропс `background` строку градиента, например `darkPurpleGradient` - градиент отображается.
- Все остальные градиенты в проекте отображаются как надо, через пропс `backgroundImage` - т.е. не понятна причина почему именно эти три не хотят работать.

**Вопросы** 
Что я мог упустить в этой ситуации? Вроде всё проверил-перепробовал, но причину не обнаружил.
Какие могут быть пути решения?

ПР сделал, ветка актуальна

2023-09-27 14:06 UTC, oxiqod commented
@Mirved64 
>Отображение градиента как backgroundImage

речь об этих градиентах?
![Снимок экрана от 2023-09-27 17-07-24](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/d1e94d67-88d9-41a4-9dd6-f6ef57781120)

![Снимок экрана от 2023-09-27 17-05-15](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/f81fbc4c-77bc-4731-9391-841bf9e4aca1)

это скрины с запущенного локалхоста, у меня всё отображается

2023-09-27 14:10 UTC, Mirved64 commented
> @Mirved64
> 
> > Отображение градиента как backgroundImage
> 
> речь об этих градиентах? ![Снимок экрана от 2023-09-27 17-04-55](https://user-images.githubusercontent.com/126156026/271005831-85a7ae19-8b0b-41b7-8a58-2f95ee1cd193.png) ![Снимок экрана от 2023-09-27 17-05-15](https://user-images.githubusercontent.com/126156026/271005876-f81fbc4c-77bc-4731-9391-841bf9e4aca1.png)

@oksssvv 
Я нашел в чем проблема.

В градиенте указан еще цвет бекграунда, т.е. я в проп `backgroundImage` записываю пропсы `backgroundImage` и `backgroundColor`. Разделил проп из фигмы на части и часть с параметром градиента записал в `backgroundImage`, а часть с цветом в `backgroundColor` и всё заработало.

2023-09-28 05:17 UTC, Mirved64 commented on landing/pages/library-page/src/library.page.tsx
>    return (
> что начинается дальше, я даж не вкурила, дай ссылку на анимацию в фигме, у меня видимо чет глючит, я вижу только скролл до хедера и не более, а уж тем более не вижу анимаций на странице библиотеки

@oksssvv 

Анимации и верстка для `wide` и `ultra` на странице библиотеки я сделал сам по аналогии с `index page`. Решил так сделать, чтобы проект был более завершен.

2023-09-29 06:32 UTC, Mirved64 commented on landing/fragments/landing-navigation/src/index.ts
> +export * from './data'
> шо происходит, куда тебе столько всего? поч для мобилки отдельный компонент? почему `navigation-index.component` не в отдельной директории
> 
> если я что то не догнала, то объясни

@oksssvv 

Когда делал в одном компоненте, я путался в верстке и решил разделить на мобилку и десктоп (т.к. верстка сильно отличается), а так же на компоненты для главной и других страниц

2023-10-02 00:28 UTC, oksssvv requested changes

2023-10-02 00:28 UTC, oksssvv commented on landing/fragments/landing-header/src/header-index.component.tsx
> +export const HeaderIndex: FC<HeaderIndexProps> = ({
что б добраться до начала верстки нужно крутануть более 3х раз, у тебя там есть крупная функция с анимацией, ей можно сделать отдельный файл, и по смыслу правильно и код чище смотрится

2023-10-02 00:28 UTC, oksssvv commented on landing/fragments/landing-courses/src/courses.component.tsx
мальца слиплось

![Снимок экрана от 2023-10-02 03-21-08](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/22219a79-02dd-4a9c-a8cd-de6f34c66594)

2023-10-02 00:28 UTC, oksssvv commented on landing/fragments/landing-courses/src/courses.component.tsx
не по макету

![Снимок экрана от 2023-10-02 03-23-49](https://github.com/atls-academy/Mirved64.github.io/assets/126156026/38331acf-bbbc-4978-b268-412122c6e852)

2023-10-02 11:20 UTC, oksssvv approved these changes

2023-10-02 14:47 UTC, Nelfimov requested changes

2023-10-02 14:47 UTC, Nelfimov commented on landing/fragments/landing-header/src/header.component.tsx
> +              <Logo fill='rgba(58, 55, 93, 1)' width={56} height={50} />
цвета перенести в тему

2023-10-02 14:47 UTC, Nelfimov commented on landing/fragments/landing-header/src/header-index.component.tsx
> +              <Logo fill='rgba(58, 55, 93, 1)' width={56} height={50} />
Цвета в тему

2023-10-02 14:47 UTC, Nelfimov commented on landing/fragments/landing-hero/src/hero.component.tsx
> +  <Box flexDirection='column' flexGrow='1'>
Вынести в отдельный `Column`

2023-10-02 14:47 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/drawer/drawer-card/drawer-card-mobile.tsx
> +      width={card.category === 'базовый' ? 87 : 122}
Хардкод локали

2023-10-03 10:23 UTC, Nelfimov requested changes

2023-10-03 10:23 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/drawer/drawer-card/drawer-card.interfaces.ts
> +  Base = 'базовый',
Локаль нельзя хардкодить. Используем только латиницу в коде.

2023-10-03 10:23 UTC, Nelfimov commented on landing/pages/index-page/src/index.page.tsx
>  const IndexPage = () => {
Выше здоровенный компонент который сложно будет поддерживать. Разбей его на логические части рядом.

2023-10-03 10:23 UTC, Nelfimov commented on landing/pages/library-page/src/library.page.tsx
>  const LibraryPage = () => {
Такая же проблема огромного компонента.

2023-10-04 07:12 UTC, Nelfimov approved these changes

2023-10-10 21:03 UTC, TorinAsakura requested changes

2023-10-10 21:03 UTC, TorinAsakura commented on landing/fragments/landing-about/src/about.component.tsx
> +          <Delimiter />
ты уже как его только не обозвал, ещё раз - это, долбанный - DIVIDER! https://mui.com/material-ui/react-divider/

2023-10-10 21:03 UTC, TorinAsakura commented on landing/fragments/landing-about/src/about.component.tsx
> +          <MobileTextBlock id='about.intro-digital-mobile' />
если у тебя мобильная сущность настолько ломает гибридное переиспользование компонентов - выноси это в отдельный компонент, если тебе приходится копипастить сущности из-за view - это хреновая практика, возможно я плохо понимаю предназначения этих вещей, но, выглядит как артефакт

2023-10-10 21:03 UTC, TorinAsakura commented on landing/fragments/landing-header/src/header-index.component.tsx
> +export const HeaderIndex: FC<HeaderIndexProps> = ({
что за headerIndex?

2023-10-10 21:03 UTC, TorinAsakura commented on landing/fragments/landing-library/src/helpers/get-color-icon.ts
> +export const getColorIcon = (hover: boolean, active: boolean): string => {
это хреновый хелпер, своим неймингом ты декларируешь что он необходим для получения цвета иконки, а сам внутри производишь манипуляции с цветами с проверкой на цвета

либо переименуй либо избавься

2023-10-10 21:03 UTC, TorinAsakura commented on landing/fragments/landing-library/src/helpers/get-color-search-icon.ts
> +  if (searchQuery) return 'darkestPurple'
эти хелперы по своей сути чёрные ящики, то есть, абсолютно не понятно как ими управлять и если полагаться лишь на нейминг то можно обосраться

2023-10-10 21:03 UTC, TorinAsakura commented on landing/fragments/landing-navigation/src/drawer/drawer-card/indent/indent.component.tsx
> +export const Indent: FC<IndentProps> = ({ index, array }) => (
что это за айндент компоненты? для чего они?? @nelfimov

2023-10-10 21:03 UTC, TorinAsakura commented on landing/fragments/landing-process/src/text-block/index.ts
> +export * from './text-block.component'
почему у тебя это везде текстовый блок? а если там будет кнопка? или изображение? побежишь тут же по всей цепи производить переименования?

2023-10-11 05:21 UTC, Mirved64 commented on landing/fragments/landing-about/src/about.component.tsx
> +          <Delimiter />
@TorinAsakura 
`Delimiter` в проекте это другой `UI` компонент. 
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/81036395-53f7-4f28-ae46-f24010b56ee9)

</p>
</details> 

`Divider` уже есть в `UI`.
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/734d0ce6-d274-46bb-a79a-76135e519aad)

</p>
</details>

2023-10-11 05:32 UTC, Mirved64 commented on landing/fragments/landing-about/src/about.component.tsx
> +          <MobileTextBlock id='about.intro-digital-mobile' />
@TorinAsakura 

Здесь я разделил текстовые блоки на мобильный и десктопный, т.к. в мобилке, для соответсвия дизайну, приходится дробить предложение на отдельные фразы, и в мобилке на конце предложения точка, а в десктопе иконка. 

В седьмом степе текстблок сделан под десктоп, т.к. с сервера получаю данные, которые без проблем использую в простом `Text` для мобилки.

2023-10-11 05:38 UTC, Mirved64 commented on landing/fragments/landing-header/src/header-index.component.tsx
> +export const HeaderIndex: FC<HeaderIndexProps> = ({
@TorinAsakura 

Все компоненты с `Index` в имени предназначены для использования на главной странице. 

Без `Index` в имени для остальных страниц (для странице библиотеки).

В данном случае, хедер с индексом использует линки из библиотеки `react-scroll`, а без индекса линки из `ui/link`

2023-10-11 06:18 UTC, Mirved64 commented on landing/fragments/landing-process/src/text-block/index.ts
> +export * from './text-block.component'
@TorinAsakura 

Это попытка в `DRY`, я делю фразу на блоки текста, отличающиеся цветами текста. 
Так код чище выглядит.

2023-10-12 23:32 UTC, TorinAsakura commented on landing/fragments/landing-header/src/header-index.component.tsx
> +export const HeaderIndex: FC<HeaderIndexProps> = ({
вообще не понимаю что за логика

2023-10-12 23:32 UTC, TorinAsakura commented on landing/fragments/landing-process/src/text-block/index.ts
> +export * from './text-block.component'
это неправильный драй который больше отдаёт сломанным солидом)

2023-10-13 00:40 UTC, TorinAsakura requested changes

2023-10-13 00:40 UTC, TorinAsakura commented on landing/fragments/landing-library/src/helpers/change-color-icon.ts
> +export const changeColorIcon = (hover: boolean, active: boolean): string => {
ты походу не понимаешь…не должно быть зашитой бизнес-логики никакой в названии "поменятьЦветИконки"

2023-10-15 21:52 UTC, TorinAsakura approved these changes
В общем, с хелперами ты так ничего и не понял походу…

НЕЛЬЗЯ, создавай метод/функцию которая исходя из названия должна "менять цвет" зашивая при этом логику вида: а если у нас серый - то будет бурмалиновый, а, если у нас бурмалиновый то будет серый
иначе
не будет никакого цвета

ты тогда так и называй свои функции, зачем ты людей в заблуждение вводишь?

2023-10-15 21:52 UTC, merged