feat/landing-seventh-step
atls-academy/Mirved64.github.io pull request #21
Opened 2023-10-02 13:22 UTC by Mirved64

Close #20

2023-10-06 13:14 UTC, oksssvv requested changes

2023-10-06 13:14 UTC, oxiqod commented on landing/fragments/landing-courses/src/sidebar/sidebar.component.tsx
>              <Button
текст в этой кнопке берется через react-intl

2023-10-06 13:14 UTC, oxiqod commented on globals/data/src/helpers/get-client.helper.ts
> +    uri: 'https://wp.api.atls.academy/graphql',
лучше использовать .env файл, что-бы изолировать информацию о URI от публичного доступа

2023-10-06 13:14 UTC, oxiqod commented on landing/entrypoints/renderer/locales/ru.json
ну если доводить до идеала, то можно эти 3 оставшиеся месседжа тоже с сервера получать)
react-intl тогда совсем не нужон будет по-сути

2023-10-06 13:14 UTC, oxiqod commented on landing/fragments/landing-faq/src/faq.component.tsx
> +  const question: string = faq?.data?.allFAQ?.nodes[0].faq.question
в случае когда данные нужно получать из массива с объектами - не хорошая практика жестко выставлять номер индекса нужного тебе объекта из представленных

если смоделировать ситуацию в которой необходимо будет добавить еще один объект с другими вариантами вопроса и ответа, то нынешний может сдвинуться и на рендере будет не то, что ожидалось

в таком случае можно воспользоваться привязкой к id, (которого у тебя нет в структуре запроса), а там использовать `.find()` например

2023-10-06 14:02 UTC, Mirved64 commented on landing/entrypoints/renderer/locales/ru.json
@oksssvv 
Я не смог найти оставшиеся данные на сервере, долго шерстил.

@Nelfimov 
Прошу помощи с бэком. Не могу найти где получить текст на кнопке
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/795eda2f-81aa-47ca-993f-dc7ba9369e37)

</p>
</details> 
на кнопке поиска на странице библиотеки
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/2e1385f0-fb28-4672-a5b2-aa9cb6cf6808)

</p>
</details> 
`Имя, спасибо!` в модалке при отправке формы
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/70a35aad-6244-46ca-a65c-f92a2ec758aa)

</p>
</details> 

Остальное нашел

2023-10-06 14:49 UTC, oksssvv commented on landing/entrypoints/renderer/locales/ru.json
@Mirved64 да, возможно их просто  не докинули

и думаю как issue к этому пр можно прикрепить `Знакомство с GraphQL #20`

2023-10-07 11:31 UTC, oksssvv approved these changes
насчет остатка месседжей, внеси тогда когда Никита добавит
а так, больше придраться не к чему, молодец)

2023-10-07 15:17 UTC, Nelfimov commented on landing/entrypoints/renderer/locales/ru.json
> @Nelfimov Прошу помощи с бэком. Не могу найти где получить текст на кнопке
> 

Добавил в навигацию

> на кнопке поиска на странице библиотеки

Добавил в формы кнопку и плейсхолдер.

> `Имя, спасибо!` в модалке при отправке формы

Добавил в формы. "Имя" тебе надо брать из модалки.

2023-10-07 15:30 UTC, Nelfimov requested changes
Добить оставшиеся запросы

2023-10-09 08:09 UTC, Nelfimov requested changes
Баг с анимацией параллакса, заголовки не "едут" вместе с блоком:

<details>

https://github.com/atls-academy/Mirved64.github.io/assets/44067768/92566fc4-bd84-4202-82e7-59bb0934ce26


</details>

2023-10-09 11:34 UTC, Nelfimov requested changes

2023-10-09 11:34 UTC, Nelfimov commented on landing/entrypoints/renderer/src/.env
> +GQL_URI = 'https://wp.api.atls.academy/graphql'
Эта переменная будет видна только на сервере:

https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

Чтобы она была видна и у клиента, см. ссылку выше - надо править нейминг.

2023-10-09 11:34 UTC, Nelfimov commented on landing/entrypoints/renderer/src/next.config.js
> +  env: {
Это тебе не нужно будет если подключишь библиотеку для загрузки переменных среды https://www.npmjs.com/package/@next/env

Помни что тебе нужна версия 12.3.4.

Пример использования:

```ts
const bootstrap = async () => {
  const app = next({
    dev: process.env.NODE_ENV !== 'production',
    dir: process.env.NODE_ENV !== 'production' ? path.join(__dirname, '../src') : __dirname,
  })
  loadEnvConfig(__dirname)
  
  server.get('*', (req, res) => handle(req, res))

  server.listen(process.env.PORT || 3001)
}

```

2023-10-09 11:34 UTC, Nelfimov commented on ui/navbar/src/navbar.component.tsx
> +  const nodeIdList = ['cG9zdDoyMjE=', 'cG9zdDoyMjI=', 'cG9zdDoyMjQ=', 'cG9zdDoyMjU=']
Вынеси в отдельный файл, как ты сделал в других местах `helpers`

2023-10-09 11:34 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/data/data-card.ts
> +export enum DrawerCardType { // eslint-disable-line
Добавил на сервер в курсах `(navbar)`

2023-10-09 12:25 UTC, Mirved64 commented on landing/entrypoints/renderer/src/.env
> +GQL_URI = 'https://wp.api.atls.academy/graphql'
@Nelfimov 
Я тут не правильно сделал. 
Этот файл не должен ведь попасть в общественный доступ?
В гит игнор добавил .env, не заметил что этот файл добавился в репозиторий

2023-10-09 12:50 UTC, Mirved64 commented on landing/fragments/landing-navigation/src/data/data-card.ts
> +export enum DrawerCardType { // eslint-disable-line
@Nelfimov 
Нет тайтла у продвинутого фронтэнда. У базовых фронта и бэка есть
<details><summary>Details</summary>
<p>

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/170c5687-e01e-4feb-b7df-706bf2d195e3)

</p>
</details>

2023-10-09 12:59 UTC, Nelfimov commented on landing/fragments/landing-navigation/src/data/data-card.ts
> +export enum DrawerCardType { // eslint-disable-line
Добавил.

2023-10-09 13:01 UTC, Nelfimov commented on landing/entrypoints/renderer/src/.env
> +GQL_URI = 'https://wp.api.atls.academy/graphql'
Зависит от ситуации. Обычно `.env` не заливают в репу, однако если репозиторий закрытый - то ничего страшного. Опять же зависит и от наполнения файла - если там пути, которые и так будут использоваться при отправке запросов - то ок. А вот если там внезапно ключи, пароли, секреты - то беда.

2023-10-10 06:02 UTC, Nelfimov approved these changes

2023-10-15 21:53 UTC, TorinAsakura approved these changes

2023-10-15 21:57 UTC, TorinAsakura commented
пофикси конфликты и 👍

2023-10-16 12:48 UTC, merged