Feat/typescript auth
atls-academy/Mirved64.github.io pull request #4
Opened 2023-05-18 06:07 UTC by Mirved64

Closes #3.

2023-05-18 08:47 UTC, TorinAsakura requested changes

2023-05-18 08:47 UTC, TorinAsakura commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.5.1.cjs
этим действием ты сломал текущую систему в которой был установлен наш собственный ярн, дальше работать ничего не будет

2023-05-18 08:47 UTC, TorinAsakura commented on package.json
> +    "@types/eslint": "8"
почему типы не в дев?

2023-05-18 08:47 UTC, TorinAsakura commented on tsconfig.json
> +    /* JavaScript Support */
????

2023-05-18 08:47 UTC, TorinAsakura commented on typescript-auth/index.ts
> +    const existUser = credentials.find(
Почему ты используешь тут find? Аргументируй пожалуйста

2023-05-18 08:47 UTC, TorinAsakura commented on typescript-auth/index.ts
> +      throw new Error("Incorrect username or password, try again");
А почему throw?

2023-05-18 09:11 UTC, Mirved64 commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.5.1.cjs
Клонировать проект из мастера поможет? и вставить файлы с задачей?

2023-05-18 09:13 UTC, Mirved64 commented on tsconfig.json
> +    /* JavaScript Support */
сгенерировал файл, а закоменченное не стал пока удалять

2023-05-18 09:25 UTC, Mirved64 commented on typescript-auth/index.ts
> +    const existUser = credentials.find(
ищем пользователя в массиве объектов пользователей. find возвращает первого найденного пользователя по условию в колбеке. Если подразумевается, что username у каждого пользователя уникальный, то find нам и нужен. Нужно еще проверку сделать, что есть ли пользователи с одинаковыми данными...

2023-05-18 09:29 UTC, Mirved64 commented on typescript-auth/index.ts
> +      throw new Error("Incorrect username or password, try again");
если условие выполняется, то выполнение кода останавливается и мы прокидываем ошибку в блок catch, где она обрабатывается (в нашем случае выводится поле message в ошибке)

2023-05-18 09:31 UTC, Mirved64 commented on package.json
> +    "@types/eslint": "8"
не понял вопроса

2023-05-18 09:32 UTC, TorinAsakura commented on tsconfig.json
> +    /* JavaScript Support */
> сгенерировал файл, а закоменченное не стал пока удалять
если отправляешь ПР на ревью - мусора в коде быть не должно

2023-05-18 09:33 UTC, TorinAsakura commented on typescript-auth/index.ts
> +    const existUser = credentials.find(
> ищем пользователя в массиве объектов пользователей. find возвращает первого найденного пользователя по условию в колбеке. Если подразумевается, что username у каждого пользователя уникальный, то find нам и нужен. Нужно еще проверку сделать, что есть ли пользователи с одинаковыми данными...

почему не some?

2023-05-18 09:33 UTC, TorinAsakura commented on typescript-auth/index.ts
> +      throw new Error("Incorrect username or password, try again");
> если условие выполняется, то выполнение кода останавливается и мы прокидываем ошибку в блок catch, где она обрабатывается (в нашем случае выводится поле message в ошибке)

а зачем ты копипастишь её постоянно?

2023-05-18 09:34 UTC, TorinAsakura commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.5.1.cjs
yarn set version https://raw.githubusercontent.com/atls/tools/master/yarn/cli/bundles/yarn.js

2023-05-18 09:41 UTC, Mirved64 commented on typescript-auth/index.ts
> +    const existUser = credentials.find(
В принцыпе, в нашем случае можно и some использовать. Нам же важно узнать есть ли в массиве совпадение по значениям полей. Я в практике чаще find использую, про some даже не подумал

2023-05-18 09:43 UTC, Mirved64 commented on typescript-auth/index.ts
> +      throw new Error("Incorrect username or password, try again");
соглашусь, что принцыпа DRY нужно держаться, но, увы, в этот раз не придумал как исправить

2023-05-18 10:10 UTC, Mirved64 commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.5.1.cjs
Логи:
```
❯ yarn set version https://raw.githubusercontent.com/atls/tools/master/yarn/cli/bundles/yarn.js
➤ YN0000: Retrieving https://raw.githubusercontent.com/atls/tools/master/yarn/cli/bundles/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-0.0.1-git.20230514.hash-af4cf64.cjs
➤ YN0000: Done in 5s 847ms
❯ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @atls/config-jest@npm:0.0.5 doesn't provide jest (pafefc), requested by ts-jest
➤ YN0002: │ @atls/config-jest@npm:0.0.5 doesn't provide typescript (p8a67a), requested by ts-jest
➤ YN0002: │ @atls/webpack-proto-imports-loader@npm:0.0.9 doesn't provide webpack (p6860c), requested by file-loader
➤ YN0060: │ @yarnpkg/plugin-interactive-tools@npm:4.0.0-rc.43 [8a4b7] provides react (p66a4e) with version 16.14.0, which doesn't satisfy what ink and some of its descendants request
➤ YN0060: │ @yarnpkg/plugin-version@npm:4.0.0-rc.43 [8a4b7] provides react (peea85) with version 16.14.0, which doesn't satisfy what ink and some of its descendants request
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 205ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 0s 509ms
❯ yarn lint
Usage Error: Couldn't find a script named "lint".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
```

2023-05-18 10:13 UTC, Mirved64 commented on tsconfig.json
> +    /* JavaScript Support */
понял, исправлю

2023-05-18 10:14 UTC, TorinAsakura commented on package.json
> +    "@types/eslint": "8"
ну так разберись в нём, почему у тебя типы еслинта в dependencies, а не в devDependencies

2023-05-18 10:15 UTC, TorinAsakura commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.5.1.cjs
> Логи:
> 
> ```
> ❯ yarn set version https://raw.githubusercontent.com/atls/tools/master/yarn/cli/bundles/yarn.js
> ➤ YN0000: Retrieving https://raw.githubusercontent.com/atls/tools/master/yarn/cli/bundles/yarn.js
> ➤ YN0000: Saving the new release in .yarn/releases/yarn-0.0.1-git.20230514.hash-af4cf64.cjs
> ➤ YN0000: Done in 5s 847ms
> ❯ yarn install
> ➤ YN0000: ┌ Resolution step
> ➤ YN0002: │ @atls/config-jest@npm:0.0.5 doesn't provide jest (pafefc), requested by ts-jest
> ➤ YN0002: │ @atls/config-jest@npm:0.0.5 doesn't provide typescript (p8a67a), requested by ts-jest
> ➤ YN0002: │ @atls/webpack-proto-imports-loader@npm:0.0.9 doesn't provide webpack (p6860c), requested by file-loader
> ➤ YN0060: │ @yarnpkg/plugin-interactive-tools@npm:4.0.0-rc.43 [8a4b7] provides react (p66a4e) with version 16.14.0, which doesn't satisfy what ink and some of its descendants request
> ➤ YN0060: │ @yarnpkg/plugin-version@npm:4.0.0-rc.43 [8a4b7] provides react (peea85) with version 16.14.0, which doesn't satisfy what ink and some of its descendants request
> ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
> ➤ YN0000: └ Completed in 0s 205ms
> ➤ YN0000: ┌ Fetch step
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Link step
> ➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
> ➤ YN0000: └ Completed
> ➤ YN0000: Done with warnings in 0s 509ms
> ❯ yarn lint
> Usage Error: Couldn't find a script named "lint".
> 
> $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
> ```

Проверяй окружение. У других линтер работает.

2023-05-18 10:15 UTC, TorinAsakura commented on typescript-auth/index.ts
> +      throw new Error("Incorrect username or password, try again");
> 

так придумай

2023-05-18 10:32 UTC, Mirved64 commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.5.1.cjs
Почему то yarn не хочет версию показывать. 
```
 node --version
v18.13.0
 yarn --version
(node:33486) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
0.0.1-git.20230514.hash-af4cf64
 tsc --version
Version 5.0.4
```
Глобально я его ставил

2023-05-18 14:34 UTC, TorinAsakura commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.5.1.cjs
> 0.0.1-git.20230514.hash-af4cf64

?

2023-05-18 16:57 UTC, Mirved64 commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.5.1.cjs
Можно я откачусь к мастеру, и всё заново сделаю?
Не получилось с первого раза у меня, весь день сижу, а толку нет

2023-05-19 08:13 UTC, Mirved64 commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.5.1.cjs
> > Логи:
> > ```
> > ❯ yarn set version https://raw.githubusercontent.com/atls/tools/master/yarn/cli/bundles/yarn.js
> > ➤ YN0000: Retrieving https://raw.githubusercontent.com/atls/tools/master/yarn/cli/bundles/yarn.js
> > ➤ YN0000: Saving the new release in .yarn/releases/yarn-0.0.1-git.20230514.hash-af4cf64.cjs
> > ➤ YN0000: Done in 5s 847ms
> > ❯ yarn install
> > ➤ YN0000: ┌ Resolution step
> > ➤ YN0002: │ @atls/config-jest@npm:0.0.5 doesn't provide jest (pafefc), requested by ts-jest
> > ➤ YN0002: │ @atls/config-jest@npm:0.0.5 doesn't provide typescript (p8a67a), requested by ts-jest
> > ➤ YN0002: │ @atls/webpack-proto-imports-loader@npm:0.0.9 doesn't provide webpack (p6860c), requested by file-loader
> > ➤ YN0060: │ @yarnpkg/plugin-interactive-tools@npm:4.0.0-rc.43 [8a4b7] provides react (p66a4e) with version 16.14.0, which doesn't satisfy what ink and some of its descendants request
> > ➤ YN0060: │ @yarnpkg/plugin-version@npm:4.0.0-rc.43 [8a4b7] provides react (peea85) with version 16.14.0, which doesn't satisfy what ink and some of its descendants request
> > ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
> > ➤ YN0000: └ Completed in 0s 205ms
> > ➤ YN0000: ┌ Fetch step
> > ➤ YN0000: └ Completed
> > ➤ YN0000: ┌ Link step
> > ➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
> > ➤ YN0000: └ Completed
> > ➤ YN0000: Done with warnings in 0s 509ms
> > ❯ yarn lint
> > Usage Error: Couldn't find a script named "lint".
> > 
> > $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
> > ```
> 
> Проверяй окружение. У других линтер работает.

Настроил окружение:
```
❯ node --version
v18.13.0
❯ yarn --version
3.5.1
❯ tsc --version
Version 5.0.4
```
Скажите, пожалуйста, смогу ли я начать заново проект если сделаю как сказано в [этой статье](https://dangitgit.com/ru#%D0%BA-%D1%87%D1%91%D1%80%D1%82%D1%83-%D0%B2%D1%81%D1%91)?

> > Логи:
> > ```
> > ❯ yarn set version https://raw.githubusercontent.com/atls/tools/master/yarn/cli/bundles/yarn.js
> > ➤ YN0000: Retrieving https://raw.githubusercontent.com/atls/tools/master/yarn/cli/bundles/yarn.js
> > ➤ YN0000: Saving the new release in .yarn/releases/yarn-0.0.1-git.20230514.hash-af4cf64.cjs
> > ➤ YN0000: Done in 5s 847ms
> > ❯ yarn install
> > ➤ YN0000: ┌ Resolution step
> > ➤ YN0002: │ @atls/config-jest@npm:0.0.5 doesn't provide jest (pafefc), requested by ts-jest
> > ➤ YN0002: │ @atls/config-jest@npm:0.0.5 doesn't provide typescript (p8a67a), requested by ts-jest
> > ➤ YN0002: │ @atls/webpack-proto-imports-loader@npm:0.0.9 doesn't provide webpack (p6860c), requested by file-loader
> > ➤ YN0060: │ @yarnpkg/plugin-interactive-tools@npm:4.0.0-rc.43 [8a4b7] provides react (p66a4e) with version 16.14.0, which doesn't satisfy what ink and some of its descendants request
> > ➤ YN0060: │ @yarnpkg/plugin-version@npm:4.0.0-rc.43 [8a4b7] provides react (peea85) with version 16.14.0, which doesn't satisfy what ink and some of its descendants request
> > ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
> > ➤ YN0000: └ Completed in 0s 205ms
> > ➤ YN0000: ┌ Fetch step
> > ➤ YN0000: └ Completed
> > ➤ YN0000: ┌ Link step
> > ➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
> > ➤ YN0000: └ Completed
> > ➤ YN0000: Done with warnings in 0s 509ms
> > ❯ yarn lint
> > Usage Error: Couldn't find a script named "lint".
> > 
> > $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
> > ```
> 
> Проверяй окружение. У других линтер работает.

Окружение настроил:

```
❯ node --version
v18.13.0
❯ yarn --version
3.5.1
❯ tsc --version
Version 5.0.4
```
Скажите, пожалуйста, может стоит сделать как написано в этой [статье](https://dangitgit.com/ru#%D0%BA-%D1%87%D1%91%D1%80%D1%82%D1%83-%D0%B2%D1%81%D1%91)?
Я запутался с `yarn` и не справляюсь.

2023-05-19 08:26 UTC, Mirved64 commented on package.json
> +    "@types/eslint": "8"
> ну так разберись в нём, почему у тебя типы еслинта в dependencies, а не в devDependencies

забыл добавить --dev когда добавлял(( Исправлю

2023-05-19 09:23 UTC, TorinAsakura commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.5.1.cjs
Много читаешь статей. Никто не запрещает всё начать с нуля. Делай конечно. Зачем ты вообще полез в ярн я не понимаю.

2023-05-19 09:23 UTC, closed without merging