Feat/simple auth
atls-academy/Mirved64.github.io pull request #5
Opened 2023-05-22 07:19 UTC by Mirved64

Close #3.

2023-05-22 17:46 UTC, TorinAsakura requested changes

2023-05-22 17:46 UTC, TorinAsakura commented on simple-auth/index.html
> +<!DOCTYPE html>
хтмл не обязателен

2023-05-22 17:46 UTC, TorinAsakura commented on simple-auth/index.js
> +let user = {
зачем ты залил жс версию?

2023-05-22 17:46 UTC, TorinAsakura commented on tsconfig.json
> +}
следи за последними строками

2023-05-22 17:46 UTC, TorinAsakura commented on simple-auth/index.ts
> +/*  eslint-enable @typescript-eslint/no-unused-vars */
зачем в конце этот коммент?

2023-05-22 17:46 UTC, TorinAsakura commented on simple-auth/index.ts
> +function loginUser(): void {
хорошей практикой в нашем случае - является модульность, попробуй разбить свой монолит на модули

2023-05-22 17:47 UTC, Mirved64 commented on simple-auth/index.ts
> +function loginUser(): void {
> хорошей практикой в нашем случае - является модульность, попробуй разбить свой монолит на модули

хорошо, сделаю

2023-05-22 17:49 UTC, Mirved64 commented on simple-auth/index.ts
> +/*  eslint-enable @typescript-eslint/no-unused-vars */
> зачем в конце этот коммент?

запарился отключать в нужных местах eslint и глаз замылился, пропустил

2023-05-22 17:50 UTC, Mirved64 commented on simple-auth/index.js
> +let user = {
> зачем ты залил жс версию?

уберу

2023-05-23 17:43 UTC, TorinAsakura approved these changes
В целом, код хорошо структурирован и легко читается. Однако, можно было бы использовать более декларативный подход и разбить функции на более мелкие для улучшения читаемости. Также, вместо console.log в функции handleError можно было бы использовать console.error.

Расскажи пожалуйста о том, что у тебя написанно в tsconfig

2023-05-23 17:43 UTC, TorinAsakura commented on tsconfig.json
> +    "target": "ES2019",
сейчас 2019?

2023-05-24 21:14 UTC, TorinAsakura requested changes
Окей, модули ты наделал, а где точка входа? Где модуль с которого будет начинаться работа?

2023-05-26 08:02 UTC, Mirved64 commented
> Окей, модули ты наделал, а где точка входа? Где модуль с которого будет начинаться работа?

В моем понимании нужно сделать модуль, который будет подключаться к html, и через liveserver можно будет работать. Я правильно понимаю?

2023-05-26 08:13 UTC, TorinAsakura commented
@Mirved64 Нет. Почитай про модульность в тайпскрипт.

2023-05-26 22:55 UTC, TorinAsakura approved these changes

2023-05-26 22:56 UTC, merged