migration to tools
atls-academy/Mirved64.github.io pull request #7
Opened 2023-05-29 15:48 UTC by Mirved64

Первые правки в структуру файлов и папок для миграции

2023-05-31 10:18 UTC, TorinAsakura commented
Если ты запросил ревью ПР переводится в режим только-чтения. Ты же продолжаешь пушить. Так мне проводить ревью или нет?

2023-05-31 10:20 UTC, Mirved64 commented
> Если ты запросил ревью ПР переводится в режим только-чтения. Ты же продолжаешь пушить. Так мне проводить ревью или нет?

прошу проверить, всё недочеты что увидел исправил

2023-05-31 10:21 UTC, TorinAsakura requested changes

2023-05-31 10:21 UTC, TorinAsakura commented on auth/package.json
> +    "bcryptjs": "^2.4.3"
разве bcryptjs не нужен для работы приложения?

2023-05-31 10:21 UTC, TorinAsakura commented on auth/src/login/index.ts
> +export async function login(
зачем ты экспортируешь функцию да ещё таким странным образом?

2023-05-31 11:53 UTC, TorinAsakura requested changes

2023-05-31 11:53 UTC, TorinAsakura commented on auth/src/login/index.ts
> +export const login = async (
я не понимаю - зачем тебе тут асинхронная функция? У тебя что-то параллельно может/будет происходить? Ты вообще понимаешь смысл асинхронности?

2023-05-31 11:53 UTC, TorinAsakura commented on auth/src/login/login.unhash-password.ts
> +export const unhashPassword = async (
что такое анхэш? хэширование - процесс, которого может и не быть, тесно связывать свои сущности с окружением - моветон, читай SOLID, опять же

2023-05-31 11:58 UTC, Mirved64 commented on auth/src/login/index.ts
> +export const login = async (
> я не понимаю - зачем тебе тут асинхронная функция? У тебя что-то параллельно может/будет происходить? Ты вообще понимаешь смысл асинхронности?

Ну у меня может быть ситуация, когда функция обрабатывает очень большой массив учетных записей. Что бы не прерывать выполнение остальных скриптов, я добавил в код асинхронности.
Или, всё-таки, убрать асинхронность?

2023-05-31 21:28 UTC, TorinAsakura requested changes

2023-05-31 21:28 UTC, TorinAsakura commented on auth/src/login/index.ts
> +        user.username === username && comparePassword(password, user.password)
что ты всё там пытаешься делать с паролём? не должна у тебя сущность быть зависима ни от каких обстоятельств. compare - это действие на крайняк состояние, если тебе нужно что-то сделать с паролём вынеси это в отдельную функцию но не миксуй это

2023-05-31 21:28 UTC, TorinAsakura commented on auth/src/login/index.ts
>  import { handleError }    from "../support-modules";
меня беспокоит, что ты не пользуешься командой yarn check

2023-05-31 21:28 UTC, TorinAsakura commented on auth/src/logout/index.ts
>      // eslint-disable-next-line no-param-reassign
зачем ты снова убиваешь линт?

2023-06-02 12:43 UTC, TorinAsakura requested changes

2023-06-02 12:43 UTC, TorinAsakura commented on auth/src/index.ts
> +export * from './simple-auth.interfaces'
а зачем ты импортируешь тут интерфейсы в модуле? ты собираешься их провайдить куда-то дальше?

2023-06-02 12:43 UTC, TorinAsakura commented on auth/src/login/index.ts
> +import { handleError }    from '../support-modules'
что такое support-modules?

2023-06-02 12:43 UTC, TorinAsakura commented on auth/src/login/index.ts
> +    console.log(`You are welcome, ${username}!`)
Зачем тебе тут вывод в лог?

2023-06-02 12:43 UTC, TorinAsakura commented on auth/src/logout/index.ts
> +import { User }               from '../simple-auth.interfaces'
приведи уже нейминг в порядок, что такое simple-auth?А что, есть hardly-auth?

2023-06-02 12:43 UTC, TorinAsakura commented on auth/src/logout/index.ts
> +  try {
зачем ты обернул выход в трай?

2023-06-04 21:11 UTC, TorinAsakura requested changes

2023-06-04 21:11 UTC, TorinAsakura commented on auth/src/helpers/index.ts
> +export * from './helpers.check-auth-user-index'
паттерн хелперов у нас принято считать анти-паттерном, так как на самом деле он сильно захламляет процессы, что касаемо твоего кода:
- handle-error это никак не хелпер, вывод ошибки это обязательная часть любого приложения, если ты хочешь использовать это именно так - задействуй паттерн exception
- check-* - тоже никакой не хелпер, это просто функция, которую ты реализуешь в рамках решения бизнес-задачи, она такой же хелпер как console.log…
- всегда проверяй на здравый смысл своё деление, например, что такое check-auth-user я ещё могу понять, а вот что такое check-auth-user-index - уже с трудом…

2023-06-04 21:11 UTC, TorinAsakura commented on auth/src/logout/index.ts
> +  try {
вопрос остался тем же…

2023-06-05 05:58 UTC, Mirved64 commented on auth/src/logout/index.ts
> +  try {
> зачем ты обернул выход в трай?

в задании к реализации авторизации было указано:
> * При попытке сделать логаут без активной сессии - должна выбрасываться ошибка

соответственно, чтобы обработать такой сценарий, я обернул код функции в try/catch, где в блоке try выбрасывается ошибка в блок catch, и уже в блоке catch ошибка обрабатывается.

2023-06-05 11:21 UTC, Mirved64 commented on auth/src/helpers/index.ts
> +export * from './helpers.check-auth-user-index'
> * handle-error это никак не хелпер, вывод ошибки это обязательная часть любого приложения, если ты хочешь использовать это именно так - задействуй паттерн exception

Никак не могу найти описание паттерна exception. Подскажите, пожалуйста, где о нем почитать?

Если поместить вместо папки helpers в utils, то это тоже анти-паттерн?

2023-06-05 15:03 UTC, Mirved64 commented on auth/src/helpers/index.ts
> +export * from './helpers.check-auth-user-index'
> паттерн хелперов у нас принято считать анти-паттерном, так как на самом деле он сильно захламляет процессы, что касаемо твоего кода:
> 
> * handle-error это никак не хелпер, вывод ошибки это обязательная часть любого приложения, если ты хочешь использовать это именно так - задействуй паттерн exception
> * check-* - тоже никакой не хелпер, это просто функция, которую ты реализуешь в рамках решения бизнес-задачи, она такой же хелпер как console.log…
> * всегда проверяй на здравый смысл своё деление, например, что такое check-auth-user я ещё могу понять, а вот что такое check-auth-user-index - уже с трудом…

можно нарушить принцып DRY, и не выносить в отдельные функции проверку на активного пользователя и поиск индекса отдельного пользователя. Как лучше в этом случае поступить?

2023-06-06 08:35 UTC, TorinAsakura commented on auth/src/helpers/index.ts
> +export * from './helpers.check-auth-user-index'
> > * handle-error это никак не хелпер, вывод ошибки это обязательная часть любого приложения, если ты хочешь использовать это именно так - задействуй паттерн exception
> 
> Никак не могу найти описание паттерна exception. Подскажите, пожалуйста, где о нем почитать?
> 
> Если поместить вместо папки helpers в utils, то это тоже анти-паттерн?

https://learn.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions

2023-06-06 08:45 UTC, TorinAsakura requested changes

2023-06-06 08:45 UTC, TorinAsakura commented on auth/src/handle-error.ts
> +export const handleError = (error: unknown): void => {
использование паттерна определяется ещё и через нейминги, в твоём случае это будет выглядеть как error.handler.ts

2023-06-06 08:45 UTC, TorinAsakura commented on auth/src/login.ts
> +    if (usersList.some((user) => user.isAuth === true)) {
очень большая конструкция, будут явные проблемы с памятью

2023-06-06 08:45 UTC, TorinAsakura commented on auth/src/logout.ts
> +  try {
зачем ты всё оборачиваешь в трай? нужны ошибки? хендли их и выбрасывай через консоль.еррор

2023-06-06 18:13 UTC, TorinAsakura approved these changes

2023-06-06 18:13 UTC, merged