Feat/landing first step
atls-academy/Mirved64.github.io pull request #9
Opened 2023-06-07 16:48 UTC by Mirved64

2023-06-09 07:56 UTC, Mirved64 commented
@TorinAsakura  
 
Скоуп 
как сделать стартовую структуру проекта
 
Описание 
не могу найти команду (по типу `create-react-app`) для создания стартовой папки проекта
 
Мои действия
- изучил репозиторий (https://github.com/atls/tools)
- изучил (https://github.com/atls/tools/wiki)
- смотрел (https://github.com/atls/tools/blob/master/yarn/plugin-schematics/src/generate-project.command.tsx)
- изучил репозиторий (https://github.com/atls/project-starter)
 
Вопрос 
какой командой генерировать стартовую структуру проекта сайта?

2023-06-09 08:00 UTC, TorinAsakura commented
Никакой. Её нет. Руками. Ты потратил день на чтение, вместо того, чтобы начать делать. Браво.

2023-06-09 12:04 UTC, Mirved64 commented
@TorinAsakura

Скоуп
не может найти модули при записи  `@landing/имя модуля`
не может найти модуль `'react'`

Описание
выдаёт ошибку при импорте данных из модуля, при записи, например `import { IndexPage } from '@landing/index-page'`
в IDE подчеркивает красным `@landing/index-page`
в IDE подчеркивает красным `react`

Мои действия

- Проект разбил на модули, каждая секция лендинга отдельный модуль.
- Прописал в каждом модуле `package.json`, создал папку `src` с соответствующими файлами.
- Запустил `yarn install`
- При командах `yarn check` выдаёт ошибку: 
```
landing/entrypoints/renderer/src/pages/index.tsx:3:26
➤ YN0000: │ 
➤ YN0000: │   Error: Cannot find module '@landing/index-page' or its corresponding type declarations.
```
`package.json` index-page:
```
{
  "name": "@landing/index-page",
  "version": "0.0.1",
  "license": "BSD-3-Clause",
  "main": "src/index.tsx",
  "dependencies": {
    "@landing/courses-fragment": "workspace:0.0.1",
    "@landing/faq-fragment": "workspace:0.0.1",
    "@landing/main-section-fragment": "workspace:0.0.1",
    "@landing/navigation-fragment": "workspace:0.0.1",
    "@landing/process-fragment": "workspace:0.0.1"
  },
  "devDependencies": {
    "react": "18.2.0"
  },
  "peerDependencies": {
    "react": "*",
    "react-dom": "*",
    "react-intl": "*"
  }
}
```
- Так же не видит модуль `react`. Пытался пофиксить как в [этой статье](https://bobbyhadz.com/blog/typescript-cannot-find-module-react) и [этой статье](https://bobbyhadz.com/blog/typescript-cannot-find-module). Не получилось.

Вопрос:
Как сделать, чтобы можно было подключать модули через `@landing/имя модуля` и подключить `react`?

2023-06-09 12:06 UTC, TorinAsakura commented
> @TorinAsakura
> 
> Скоуп не может найти модули при записи `@landing/имя модуля` не может найти модуль `'react'`
> 
> Описание выдаёт ошибку при импорте данных из модуля, при записи, например `import { IndexPage } from '@landing/index-page'` в IDE подчеркивает красным `@landing/index-page` в IDE подчеркивает красным `react`
> 
> Мои действия
> 
> * Проект разбил на модули, каждая секция лендинга отдельный модуль.
> * Прописал в каждом модуле `package.json`, создал папку `src` с соответствующими файлами.
> * Запустил `yarn install`
> * При командах `yarn check` выдаёт ошибку:
> 
> ```
> landing/entrypoints/renderer/src/pages/index.tsx:3:26
> ➤ YN0000: │ 
> ➤ YN0000: │   Error: Cannot find module '@landing/index-page' or its corresponding type declarations.
> ```
> 
> `package.json` index-page:
> 
> ```
> {
>   "name": "@landing/index-page",
>   "version": "0.0.1",
>   "license": "BSD-3-Clause",
>   "main": "src/index.tsx",
>   "dependencies": {
>     "@landing/courses-fragment": "workspace:0.0.1",
>     "@landing/faq-fragment": "workspace:0.0.1",
>     "@landing/main-section-fragment": "workspace:0.0.1",
>     "@landing/navigation-fragment": "workspace:0.0.1",
>     "@landing/process-fragment": "workspace:0.0.1"
>   },
>   "devDependencies": {
>     "react": "18.2.0"
>   },
>   "peerDependencies": {
>     "react": "*",
>     "react-dom": "*",
>     "react-intl": "*"
>   }
> }
> ```
> 
>  * Так же не видит модуль `react`. Пытался пофиксить как в [этой статье](https://bobbyhadz.com/blog/typescript-cannot-find-module-react) и [этой статье](https://bobbyhadz.com/blog/typescript-cannot-find-module). Не получилось.
> 
> Вопрос: Как сделать, чтобы можно было подключать модули через `@landing/имя модуля` и подключить `react`?

у тебя всё перепутано…тебе реакт нужен чтобы запустить приложение? видимо да, но, тогда почему он в девДепсах? Тебе фрагменты нужны для работы после билда? Полагаю нет…тогда почему они у тебя являются основными зависимостями? Тебе IDE всё правильно говорит. Не там ищешь.

Далее, ты воркспейс новый добавил в корневой пекедж?

2023-06-09 12:10 UTC, Mirved64 commented
> Далее, ты воркспейс новый добавил в корневой пекедж?

воркспейс добавил, сейчас с зависимостями разбераться буду

2023-06-09 12:17 UTC, Mirved64 commented
> у тебя всё перепутано…тебе реакт нужен чтобы запустить приложение? видимо да, но, тогда почему он в девДепсах? Тебе фрагменты нужны для работы после билда? Полагаю нет…тогда почему они у тебя являются основными зависимостями? Тебе IDE всё правильно говорит. Не там ищешь.

Зависимости поменял, не помогло

> Далее, ты воркспейс новый добавил в корневой пекедж?

Вот корневой `package.json`:
```
{
  "name": "template",
  "private": true,
  "license": "BSD 3-Clause",
  "workspaces": [
    "auth",
    "ui/**/*",
    "landing/**/*"
  ],
  "resolutions": {
    "@types/react": "17.0.39",
    "next": "12.3.4"
  },
  "devDependencies": {
    "@atls/code-service": "^0.0.18",
    "@atls/config-jest": "^0.0.5",
    "@atls/config-typescript": "^0.0.2",
    "@atls/schematics": "^0.0.13",
    "@jest/core": "^27.4.5",
    "@types/eslint": "8",
    "@types/node": "^20.2.3",
    "@types/react": "^17.0.37",
    "eslint": "8.18.0",
    "husky": "^8.0.3",
    "typescript": "^4.6.2"
  },
  "packageManager": "yarn@3.5.1"
}
```

2023-06-09 16:12 UTC, Mirved64 commented
> > @TorinAsakura

>  Тебе IDE всё правильно говорит. Не там ищешь.

Никак не получается решить проблему с реакт модулем. Подскажите, пожалуйста, как исправить или где искать?

2023-06-10 17:01 UTC, TorinAsakura commented
> @TorinAsakura
> 
> Скоуп не может найти модули при записи `@landing/имя модуля` не может найти модуль `'react'`
> 
> Описание выдаёт ошибку при импорте данных из модуля, при записи, например `import { IndexPage } from '@landing/index-page'` в IDE подчеркивает красным `@landing/index-page` в IDE подчеркивает красным `react`
> 
> Мои действия
> 
> * Проект разбил на модули, каждая секция лендинга отдельный модуль.
> * Прописал в каждом модуле `package.json`, создал папку `src` с соответствующими файлами.
> * Запустил `yarn install`
> * При командах `yarn check` выдаёт ошибку:
> 
> ```
> landing/entrypoints/renderer/src/pages/index.tsx:3:26
> ➤ YN0000: │ 
> ➤ YN0000: │   Error: Cannot find module '@landing/index-page' or its corresponding type declarations.
> ```
> 
> `package.json` index-page:
> 
> ```
> {
>   "name": "@landing/index-page",
>   "version": "0.0.1",
>   "license": "BSD-3-Clause",
>   "main": "src/index.tsx",
>   "dependencies": {
>     "@landing/courses-fragment": "workspace:0.0.1",
>     "@landing/faq-fragment": "workspace:0.0.1",
>     "@landing/main-section-fragment": "workspace:0.0.1",
>     "@landing/navigation-fragment": "workspace:0.0.1",
>     "@landing/process-fragment": "workspace:0.0.1"
>   },
>   "devDependencies": {
>     "react": "18.2.0"
>   },
>   "peerDependencies": {
>     "react": "*",
>     "react-dom": "*",
>     "react-intl": "*"
>   }
> }
> ```
> 
>  * Так же не видит модуль `react`. Пытался пофиксить как в [этой статье](https://bobbyhadz.com/blog/typescript-cannot-find-module-react) и [этой статье](https://bobbyhadz.com/blog/typescript-cannot-find-module). Не получилось.
> 
> Вопрос: Как сделать, чтобы можно было подключать модули через `@landing/имя модуля` и подключить `react`?

Либо пиши шаги воспроизведения либо разбирайся с локальным окружением. Установка зависимостей прошла. Все импорты рабочие.

![Снимок экрана 2023-06-10 в 20 00 49](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/cb5779f5-3429-475b-abaf-4d56a3b69aa5)

2023-06-12 08:55 UTC, Mirved64 commented
@TorinAsakura

Скоуп
как подключить [Библиотеку компонентов](https://github.com/atls/hyperion)

Описание
не понимаю как подключить к проекту [Библиотека компонентов](https://github.com/atls/hyperion)

Мои действия

- изучил репозиторий (https://github.com/atls/hyperion);
- изучил (https://github.com/atls/hyperion/wiki);
- скачал репозиторий [Библиотека компонентов](https://github.com/atls/hyperion);
- создал в проекте папку ui;
- добавил в неё папки layout, text, link из директории ui-proto скачанного репозитория;
- при команде `yarn install` выдаёт ошибку:
` YN0001: │ Error: @atls-ui-parts/layout@workspace:0.0.7: Workspace not found (@atls-ui-parts/layout@workspace:0.0.7)`;

Вопрос
Как правильно подключить нужные элементы из [Библиотеки компонентов](https://github.com/atls/hyperion)?

2023-06-12 09:06 UTC, Nelfimov commented
> добавил в неё папки layout, text, link из директории ui-proto скачанного репозитория;

На этом шаге у тебя проблема - надо не копировать папки из репы, а устанавливать зависимости - yarn add @atls-ui-proto/layout например. 

А так надо:
1. Инициализировать пакет @ui/layout в папке yo/layout. 
2. В нем добавить зависимость как написал выше и экспортировать ее из src/index.ts

2023-06-12 09:19 UTC, Mirved64 commented
> > добавил в неё папки layout, text, link из директории ui-proto скачанного репозитория;
> 
> На этом шаге у тебя проблема - надо не копировать папки из репы, а устанавливать зависимости - yarn add @atls-ui-proto/layout например.
> 
> А так надо:
> 
> 1. Инициализировать пакет @ui/layout в папке ui/layout.
> 2. В нем добавить зависимость как написал выше и экспортировать ее из src/index.ts

Скопированные папки удалил. Создал и перешел в директорию ui/layout. Ввожу `yarn init `, потом `yarn add @atls-ui-proto/layout`, зависимость не устанавливается, выдаёт ошибку:
`YN0001: │ Error: @atls-ui-parts/text@workspace:0.0.10: Workspace not found (@atls-ui-parts/text@workspace:0.0.10)`

2023-06-12 09:25 UTC, TorinAsakura commented
@Mirved64 Как зависимости.

2023-06-13 12:39 UTC, Mirved64 commented
@TorinAsakura

Скоуп
настройка ui/theme

Описание
- создал дирректорию `ui/theme`, инициализировал модуль `@ui/theme`;
- подключил зависимости. `package.json`:
```
{
  "name": "@ui/theme",
  "version": "0.0.1",
  "license": "BSD-3-Clause",
  "main": "src/index.ts",
  "dependencies": {
    "@atls-ui-proto/theme": "^0.0.9",
    "@emotion/css": "^11.11.0"
  },
  "devDependencies": {
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@types/react": "^18.2.9",
    "@types/react-dom": "^18.2.4",
    "@types/styled-system": "^5.1.16",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}
```
- в папке `src/theme` сделал файлы с конфигурациями для темы (`fonts`, `font-sizes`, `font-weight` и т.д.);
- создал файл `global.styles` и указал там глобальные стили (обнулил марджини, задал шрифт хельветика);
- создал файл theme.provider как описано [здесь](https://github.com/atls/hyperion/blob/master/ui-proto/theme/README.md)
- IDE ругается на код в theme.provider 

Вопрос:
как настроить ui/theme, как исправить ошибки в файле theme.provider?
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/58e761cd-56e6-4b17-a550-2c5e8eb73aa4)

2023-06-13 18:29 UTC, TorinAsakura commented
@Mirved64 К таким реквестам обычно нужно прикладвыать ссылку на коммит, или сообщить о том, что ветка актуальна и можно проверять прямо в ней. Ветка актуальна? ПР сделан?

2023-06-13 21:24 UTC, TorinAsakura commented
> @TorinAsakura
> 
> Скоуп настройка ui/theme
> 
> Описание
> 
> * создал дирректорию `ui/theme`, инициализировал модуль `@ui/theme`;
> * подключил зависимости. `package.json`:
> 
> ```
> {
>   "name": "@ui/theme",
>   "version": "0.0.1",
>   "license": "BSD-3-Clause",
>   "main": "src/index.ts",
>   "dependencies": {
>     "@atls-ui-proto/theme": "^0.0.9",
>     "@emotion/css": "^11.11.0"
>   },
>   "devDependencies": {
>     "@emotion/react": "^11.11.1",
>     "@emotion/styled": "^11.11.0",
>     "@types/react": "^18.2.9",
>     "@types/react-dom": "^18.2.4",
>     "@types/styled-system": "^5.1.16",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0"
>   }
> }
> ```
> 
>  * в папке `src/theme` сделал файлы с конфигурациями для темы (`fonts`, `font-sizes`, `font-weight` и т.д.);
> * создал файл `global.styles` и указал там глобальные стили (обнулил марджини, задал шрифт хельветика);
> * создал файл theme.provider как описано [здесь](https://github.com/atls/hyperion/blob/master/ui-proto/theme/README.md)
> * IDE ругается на код в theme.provider
> 
> Вопрос: как настроить ui/theme, как исправить ошибки в файле theme.provider? ![image](https://user-images.githubusercontent.com/99605124/245477091-58e761cd-56e6-4b17-a550-2c5e8eb73aa4.png)

ну, так может быть у тебя тип файла неправильный? У тебя там jsx структура, а файл у тебя тупо ts. Не?

2023-06-14 15:49 UTC, Mirved64 commented
@TorinAsakura

**Скоуп**
вставка в проект иконок

**Описание**
не могу до конца понять, как добавлять иконки (соц. сети, лого) в проект

**Мои действия**
- изучил папку `ui/icons` репозитория [примера 1](https://github.com/torin-asakura/shdvor/tree/master/ui/icons)
- изучил папку `ui/icons` репозитория [примера 2](https://github.com/torin-asakura/dream-team/tree/master/ui/icons)
- как экспортировать из фигмы `svg` иконку из фигмы знаю
- где взять информацию в виде кода `svg` изображения, чтобы вписать её в компонент, не знаю.

**Вопрос:**
Какой алгоритм действий с `svg` изображением, чтобы на его основе сделать компонент и потом экспортировать в проект?

2023-06-15 08:18 UTC, Mirved64 commented
@TorinAsakura

**Скоуп**
генераторы (в частности генератор иконок)

**Описание**
не могу до конца понять, как пользоваться генераторм иконок

**Мои действия**
- экспортировал с макета иконки в формате `svg` в директорию `ui/icons/icons`;
- иницировал модуль, подключил зависимости, добавил скрипт. `package.json`: 
```
{
  "name": "@ui/icons",
  "version": "0.0.1",
  "license": "BSD-3-Clause",
  "main": "src/index.ts",
  "scripts": {
    "generate-icons": "generate-icons src/ -i ./icons"
  },
  "devDependencies": {
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@types/glob": "^8.1.0",
    "@types/react": "^18.2.9",
    "@types/react-dom": "^18.2.4",
    "glob": "^10.2.7",
    "glob-promise": "^6.0.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "dependencies": {
    "@atls-ui-generators/icons": "^0.0.2"
  }
}
```
- при команде `yarn generate-icons` выдаёт ошибку:
`Error: glob-promise tried to access glob (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.`

Вопросы:
Правильная команда на генерацию? Как избавиться от ошибки и сгенерить `.tsx`?

2023-06-15 08:19 UTC, TorinAsakura commented
@Mirved64 Команда правильная. Избавиться от ошибки и сгенерить .tsx можно…ПРОЧИТАВ ОШИБКУ и исправив её…

2023-06-15 10:22 UTC, Mirved64 commented
> @Mirved64 Команда правильная. Избавиться от ошибки и сгенерить .tsx можно…ПРОЧИТАВ ОШИБКУ и исправив её…

**Скоуп:**
`glob-promise` никак не хочет находить `glob`. 

**Действия:**
- Изучил [репозиторий glob-promise](https://github.com/ahmadnassri/node-glob-promise), где сказано, что [необходимо добавить `glob` в `peerDepencies`](https://github.com/ahmadnassri/node-glob-promise#note);
- Добавлял `glob` в , `peerDepencies`, `decencies`, `devDepencies`, всё-равно пишет ошибку  `Error: glob-promise tried to access glob (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.`
- Загрузил актуальную ветку в ПР

**Вопрос**:
В чем может быть проблема? Как правильно организовать зависимости в этом модуле?

2023-06-15 13:12 UTC, oksssvv commented
@Mirved64 

>Скоуп:
glob-promise никак не хочет находить glob.

>Действия:

>Изучил [репозиторий glob-promise](https://github.com/ahmadnassri/node-glob-promise), где сказано, что [необходимо добавить glob в peerDepencies](https://github.com/ahmadnassri/node-glob-promise#note);
Добавлял glob в , peerDepencies, decencies, devDepencies, всё-равно пишет ошибку Error: glob-promise tried to access glob (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
Загрузил актуальную ветку в ПР
Вопрос:
В чем может быть проблема? Как правильно организовать зависимости в этом модуле?

Пакета `glob` не хватает не в твоем package.json, а зависимостях генератора (моя догадка, что раньше glob был не нужен для нормального функционирования данного генератора, а сейчас необходим)
загляни в файл `.yarnrc.yml` тех проектов, в которых используется генератор иконок, думаю там ты найдешь ответ на свой вопрос

2023-06-15 13:13 UTC, TorinAsakura commented
@Mirved64 Нужно почитать что такое yarn packageExtension

2023-06-15 13:16 UTC, TorinAsakura commented
@Mirved64 Пора начать учиться разделять ошибки в коде и ошибки пакетного менеджера

2023-06-16 18:11 UTC, TorinAsakura commented
Если твой ПР готов - выведи его из драфта

2023-06-20 07:28 UTC, Mirved64 commented
@TorinAsakura

**Скоуп**
адаптивная верстка в проекте

**Описание**
не могу понять где выставлять брейкпоинты на ширину экрана.

Мои действия

- изучил репозитории примеров
- из них я понял, что задавать значения свойств можно такими конструкциями:
display={['none', 'none', 'flex']} - на двух разрешениях скрываем элемент, на третьем он становится флекс контейнером

**Вопросы**
Я правильно понял как задавать значения свойств?
Где в проекте задаются брейкпоинты для верстки? В нашем случае ширина экрана

2023-06-20 16:53 UTC, TorinAsakura commented
@Mirved64 https://styled-system.com/theme-specification/

2023-06-21 13:26 UTC, Mirved64 commented
@TorinAsakura

**Скоуп**
svg иконки

**Описание**
не отображаются svg иконки на мобильной версии

**Мои действия**
- скопировал кусок кода с иконкой-заглушкой;
- вставил в нужном месте;
- поставил нужные размеры;
- все иконки-заглушки на мобильной версии не показываются;
- лого и иконки соц. сетей отображаются;

**Вопрос**
Что нужно сделать чтобы отобразились иконки-заглушки?

**ПР сделал, ветка актуальна**
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/a0e39557-e847-4225-aa21-7907587b9760)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/c77d986d-40cb-4d48-82be-94b17f1f8fbe)

2023-06-22 15:21 UTC, TorinAsakura commented
> @TorinAsakura
> 
> **Скоуп** svg иконки
> 
> **Описание** не отображаются svg иконки на мобильной версии
> 
> **Мои действия**
> 
> * скопировал кусок кода с иконкой-заглушкой, которую использую для десктопной версии;
> * вставил в нужном месте кода (фрагмент один и тот же);
> * поставил нужные размеры;
> * все иконки-заглушки на мобильной версии не показываются;
> * лого и иконки соц. сетей отображаются как надо;
> * иконки-заглушки на десктопной версии отображаются как надо;
> 
> **Вопрос** Что нужно сделать чтобы отобразились иконки-заглушки в мобильной версии?
> 
> **ПР сделал, ветка актуальна** ![image](https://user-images.githubusercontent.com/99605124/247563833-a0e39557-e847-4225-aa21-7907587b9760.png) ![image](https://user-images.githubusercontent.com/99605124/247563998-c77d986d-40cb-4d48-82be-94b17f1f8fbe.png)

а какого цвета иконки?

2023-06-22 15:42 UTC, Mirved64 commented
> > @TorinAsakura
> > **Скоуп** svg иконки
> > **Описание** не отображаются svg иконки на мобильной версии
> > **Мои действия**
> > 
> > * скопировал кусок кода с иконкой-заглушкой, которую использую для десктопной версии;
> > * вставил в нужном месте кода (фрагмент один и тот же);
> > * поставил нужные размеры;
> > * все иконки-заглушки на мобильной версии не показываются;
> > * лого и иконки соц. сетей отображаются как надо;
> > * иконки-заглушки на десктопной версии отображаются как надо;
> > 
> > **Вопрос** Что нужно сделать чтобы отобразились иконки-заглушки в мобильной версии?
> > **ПР сделал, ветка актуальна** ![image](https://user-images.githubusercontent.com/99605124/247563833-a0e39557-e847-4225-aa21-7907587b9760.png) ![image](https://user-images.githubusercontent.com/99605124/247563998-c77d986d-40cb-4d48-82be-94b17f1f8fbe.png)
> 
> а какого цвета иконки?

- ставил fill='black' - не помогло;
- если эту иконку отображать в десктопной версии (поставить display={['flex', 'flex']}), то она нормально отображается;
- не могу понять почему иконки, у которых разница только в width и height, по разному ведут себя

2023-06-22 15:52 UTC, TorinAsakura commented
@Mirved64 Чтож, полагаю тебе стоит ознакомиться с устройством svg https://developer.mozilla.org/ru/docs/Web/SVG/Attribute/viewBox

2023-06-22 17:04 UTC, Mirved64 commented
> @Mirved64 Чтож, полагаю тебе стоит ознакомиться с устройством svg https://developer.mozilla.org/ru/docs/Web/SVG/Attribute/viewBox

Читаю, меняю параметры и свойства svg. Пока результата нет.

Может дело не в svg? Заглушка отображается в десктопе, а в мобилке не хочет.
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/808a4a13-b564-41b3-a85a-88a2fc915af9)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/4768c6b6-2881-474c-b8c5-1a74680d8185)

2023-06-22 17:05 UTC, TorinAsakura commented
@Mirved64 Так может тогда проблема в том, какие аттрибуты ты задаёшь мобильной версии этого блока?

2023-06-22 17:33 UTC, Mirved64 commented
> @Mirved64 Так может тогда проблема в том, какие аттрибуты ты задаёшь мобильной версии этого блока?

В блоке не должно быть ошибок. Всё попробовал, менял-возвращал. Результата пока нет. Не знаю, что может быть. Буду думать.
В остальном всё готово для ревью.

2023-06-23 08:00 UTC, oxiqod commented
@Mirved64 

> Читаю, меняю параметры и свойства svg. Пока результата нет.
 Может дело не в svg? Заглушка отображается в десктопе, а в мобилке не хочет.
 
Сравни файлы уже сгенерированных иконок с этой заглушкой, у них есть одно отличие (сама сейчас кстати эту проблему решаю)
Как поняла я изначально эта заглушка не предназначалась как SVG формат, и ее не нужно было создавать через генератор иконок, а вставлять как обычный PNG (потому что на следующих этапах она будет заменена). 

я сконвертировала заново эту заглушку, и теперь у нее есть свойства `path`, выглядит так:
`
 <path
        fill='#000000'
        d='M -0.5,-0.5 C 32.8333,-0.5 66.1667,-0.5 99.5,-0.5C 99.5,32.8333 99.5,66.1667 99.5,99.5C 66.1667,99.5 32.8333,99.5 -0.5,99.5C -0.5,66.1667 -0.5,32.8333 -0.5,-0.5 Z'
      />
      <path
        fill='#fefffe'
        d='M 99.5,-0.5 C 132.833,-0.5 166.167,-0.5 199.5,-0.5C 199.5,32.8333 199.5,66.1667 199.5,99.5C 166.167,99.5 132.833,99.5 99.5,99.5C 99.5,66.1667 99.5,32.8333 99.5,-0.5 Z'
      />
      <path
        fill='#000000'
        d='M 199.5,-0.5 C 232.833,-0.5 266.167,-0.5 299.5,-0.5C 299.5,32.8333 299.5,66.1667 299.5,99.5C 266.167,99.5 232.833,99.5 199.5,99.5C 199.5,66.1667 199.5,32.8333 199.5,-0.5 Z'
      />
      <path
        fill='#fefffe'
        d='M 299.5,-0.5 C 332.833,-0.5 366.167,-0.5 399.5,-0.5C 399.5,32.8333 399.5,66.1667 399.5,99.5C 366.167,99.5 332.833,99.5 299.5,99.5C 299.5,66.1667 299.5,32.8333 299.5,-0.5 Z'
      />
      <path
        fill='#fefffe'
        d='M -0.5,99.5 C 32.8333,99.5 66.1667,99.5 99.5,99.5C 99.5,132.833 99.5,166.167 99.5,199.5C 66.1667,199.5 32.8333,199.5 -0.5,199.5C -0.5,166.167 -0.5,132.833 -0.5,99.5 Z'
      />
      <path
        fill='#000000'
        d='M 99.5,99.5 C 132.833,99.5 166.167,99.5 199.5,99.5C 199.5,132.833 199.5,166.167 199.5,199.5C 166.167,199.5 132.833,199.5 99.5,199.5C 99.5,166.167 99.5,132.833 99.5,99.5 Z'
      />
      <path
        fill='#fefffe'
        d='M 199.5,99.5 C 232.833,99.5 266.167,99.5 299.5,99.5C 299.5,132.833 299.5,166.167 299.5,199.5C 266.167,199.5 232.833,199.5 199.5,199.5C 199.5,166.167 199.5,132.833 199.5,99.5 Z'
      />
      <path
        fill='#000000'
        d='M 299.5,99.5 C 332.833,99.5 366.167,99.5 399.5,99.5C 399.5,132.833 399.5,166.167 399.5,199.5C 366.167,199.5 332.833,199.5 299.5,199.5C 299.5,166.167 299.5,132.833 299.5,99.5 Z'
      />
      <path
        fill='#000000'
        d='M -0.5,199.5 C 32.8333,199.5 66.1667,199.5 99.5,199.5C 99.5,232.833 99.5,266.167 99.5,299.5C 66.1667,299.5 32.8333,299.5 -0.5,299.5C -0.5,266.167 -0.5,232.833 -0.5,199.5 Z'
      />
      <path
        fill='#fefffe'
        d='M 99.5,199.5 C 132.833,199.5 166.167,199.5 199.5,199.5C 199.5,232.833 199.5,266.167 199.5,299.5C 166.167,299.5 132.833,299.5 99.5,299.5C 99.5,266.167 99.5,232.833 99.5,199.5 Z'
      />
      <path
        fill='#000000'
        d='M 199.5,199.5 C 232.833,199.5 266.167,199.5 299.5,199.5C 299.5,232.833 299.5,266.167 299.5,299.5C 266.167,299.5 232.833,299.5 199.5,299.5C 199.5,266.167 199.5,232.833 199.5,199.5 Z'
      />
      <path
        fill='#fefffe'
        d='M 299.5,199.5 C 332.833,199.5 366.167,199.5 399.5,199.5C 399.5,232.833 399.5,266.167 399.5,299.5C 366.167,299.5 332.833,299.5 299.5,299.5C 299.5,266.167 299.5,232.833 299.5,199.5 Z'
      />
      <path
        fill='#fefffe'
        d='M -0.5,299.5 C 32.8333,299.5 66.1667,299.5 99.5,299.5C 99.5,332.833 99.5,366.167 99.5,399.5C 66.1667,399.5 32.8333,399.5 -0.5,399.5C -0.5,366.167 -0.5,332.833 -0.5,299.5 Z'
      />
      <path
        fill='#000000'
        d='M 99.5,299.5 C 132.833,299.5 166.167,299.5 199.5,299.5C 199.5,332.833 199.5,366.167 199.5,399.5C 166.167,399.5 132.833,399.5 99.5,399.5C 99.5,366.167 99.5,332.833 99.5,299.5 Z'
      />
      <path
        fill='#fefffe'
        d='M 199.5,299.5 C 232.833,299.5 266.167,299.5 299.5,299.5C 299.5,332.833 299.5,366.167 299.5,399.5C 266.167,399.5 232.833,399.5 199.5,399.5C 199.5,366.167 199.5,332.833 199.5,299.5 Z'
      />
      <path
        fill='#000000'
        d='M 299.5,299.5 C 332.833,299.5 366.167,299.5 399.5,299.5C 399.5,332.833 399.5,366.167 399.5,399.5C 366.167,399.5 332.833,399.5 299.5,399.5C 299.5,366.167 299.5,332.833 299.5,299.5 Z'
      />
`

Она стала отображаться и на десктопной и на мобильной версии, но проще наверное использовать эту заглушку в формате PNG ))

2023-06-23 09:22 UTC, Mirved64 commented
> 
@TorinAsakura 

Я нашел баг, но не знаю как его исправить.

**Алгоритм повторения**
- запускаем `yarn dev`;
- в браузере открываем инструменты разработчика;
- находим иконку;
- в тэге `<svg>`, открываем `<rect>` и в поле `fill="url(#pattern0)"` переименновываем, например `fill="url(#pattern)"`;
- в тэге `<svg><def><pattern> `меняем поле id="pattern0" на id="pattern";
Если обновить страницу, естественно, всё слетает.

Почему остальные такие же иконки работают нормально, а проблемы только в секции `courses` и `process` в мобильной версии

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/6b4baeae-1911-4209-975d-4404036207c1)

2023-06-23 09:23 UTC, Mirved64 commented
> > 
> 
> @TorinAsakura
> 
> Я нашел баг с отображением заглушки на мобильной версии, но не знаю как его исправить.
> 
> **Алгоритм повторения**
> 
> * запускаем `yarn dev`;
> * в браузере открываем инструменты разработчика;
> * находим иконку;
> * в тэге `<svg>`, открываем `<rect>` и в поле `fill="url(#pattern0)"` переименновываем, например `fill="url(#pattern)"`;
> * в тэге `<svg><def><pattern> `меняем поле id="pattern0" на id="pattern";
>   Если обновить страницу, естественно, всё слетает.
> 
> Почему остальные такие же иконки работают нормально, а проблемы только в секции `courses` и `process` в мобильной версии
> 
> ![image](https://user-images.githubusercontent.com/99605124/248228061-6b4baeae-1911-4209-975d-4404036207c1.png)

2023-06-23 09:24 UTC, TorinAsakura commented
@Mirved64 Я что-то не понял, а баг-то в чём?

2023-06-23 09:26 UTC, Mirved64 commented
> @Mirved64 Я что-то не понял, а баг-то в чём?

не хочет отображать заглушку на мобильной версии сайта, если не делать как я выше писал
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/8dc6ab0e-4dbb-4adb-9f79-436aa700c641)

2023-06-23 09:30 UTC, TorinAsakura commented
Погоди-те ка, так это не иконка, это растровое изображение, вы чо?

2023-06-26 11:53 UTC, TorinAsakura requested changes
Визуально выглядит неплохо, однако, у тебя есть серьёзный сдвиг: слева отступ больше чем справа
Фундаментальные проблемы налицо
![Снимок экрана 2023-06-26 в 14 53 33](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/5926ccaf-c971-4582-9412-c021789e5b6b)

2023-06-26 11:53 UTC, TorinAsakura commented on landing/entrypoints/renderer/next.config.js
> +  // TODO check webpack config settings
если запрашиваешь ревью на слияние закомментированных строк быть не должно

2023-06-26 11:53 UTC, TorinAsakura commented on .gitignore
> +.next
последняя строка

2023-06-26 11:53 UTC, TorinAsakura commented on landing/entrypoints/renderer/src/tsconfig.json
> +  "compilerOptions": {
рекомендую использовать директиву extend

2023-06-26 11:53 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +  <Box backgroundColor='#ffffff' width='100%' margin='0 auto'>
цвета, размеры и все токены должны быть получены из темы, это обязательно

2023-06-26 11:53 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +    <Column margin={['64px 20px', '160px 80px 240px 230px']}>
мы не используем марджины, они на дают гарантии индепонентной консистентности единого видения и кроссплатформенности

2023-06-26 11:53 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +            Курсы и материалы
переводы должны быть вынесены в json посредством react-intl, смотри на репозитории-примеры

2023-06-26 11:53 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +        <Box flexWrap='wrap' flexBasis='45%' marginBottom={['20px', '0']}>
а как ты высчитал 45%? А если размер экрана будет отличным от того, на котором ты верстал?

2023-06-26 12:00 UTC, Mirved64 commented
> Визуально выглядит неплохо, однако, у тебя есть серьёзный сдвиг: слева отступ больше чем справа Фундаментальные проблемы налицо ![Снимок экрана 2023-06-26 в 14 53 33](https://user-images.githubusercontent.com/3940885/248786125-5926ccaf-c971-4582-9412-c021789e5b6b.png)

Но ведь в макете в секции **Курсы и материалы** и **Вопросы и ответы** на десктопной версии отступы слева и справа различаются. 
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/e5e0f515-e62b-4797-8569-bb1a5a5d25c6)

2023-06-26 15:43 UTC, Mirved64 commented on landing/fragments/landing-courses/src/courses.component.tsx
> +            Курсы и материалы
уточните, пожалуйста. Это в папке globals/messages файлы как [этот](https://github.com/torin-asakura/dream-team/blob/master/globals/messages/src/messages.ts)? Честно, я не очень понял где файл с объектом данных, в котором текст сайта забит

2023-06-26 16:05 UTC, Mirved64 commented on landing/fragments/landing-courses/src/courses.component.tsx
> +    <Column margin={['64px 20px', '160px 80px 240px 230px']}>
Уточните, пожалуйста. Вместо `margin` вставлять элемент `Layout` и задавать ему `flexBasis` в качестве размеров?

2023-06-28 07:38 UTC, Mirved64 commented on landing/fragments/landing-courses/src/courses.component.tsx
> +            Курсы и материалы
@TorinAsakura 

уточните, пожалуйста. Это в папке globals/messages файлы как [этот](https://github.com/torin-asakura/dream-team/blob/master/globals/messages/src/messages.ts)? Честно, я не очень понял где файл с объектом данных, в котором текст сайта забит

2023-06-28 15:07 UTC, Mirved64 commented
@TorinAsakura

**Скоуп**
настройка react-intl

**Описание**
При запуске в режиме разработки выдаёт ошибку: 
```
Server Error
Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
```
Мои действия:
- подключил библиотеку к `landing/entrypoints/renderer `;
- обернул `App` в `IntlProvider`, прописал основные пропсы;
- во все теги `Text` вставил `<FormattedMessage id='#' defaultMessage='ТО ЧТО БЫЛО В TEXT' />`;

Проблему гуглил, читал доку к библиотеке, к `next.js`. 
**Если каждый фрагмент обернуть в `IntlProvider`и прописать основные пропсы, то ошибка пропадает!**
**Если в файле `_app.ts` прописать как в примере из [официальной документации](https://formatjs.io/docs/getting-started/installation#minimal-application), то всё работает.**

**Вопросы:**
Если пишет `Server Error` то проблема не в библиотеке? 
Где может быть ошибка и как её исправить? Куда ещё можно заглянуть?

ПР сделал, ветка актуальная

2023-06-28 15:15 UTC, TorinAsakura commented
@Mirved64 Нет. Проблема ТОЧНО не в библиотеке, а в том, как ты подключаешь интл в проект. Также, рекомендую использовать версии, сопоставимые с нашими

2023-06-28 18:11 UTC, TorinAsakura requested changes

2023-06-28 18:11 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +            <FormattedMessage id='#' defaultMessage='Курсы и материалы' />
как у тебя сообщение будет рендериться без айди? я что-то не понимаю

2023-06-28 18:11 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +            lineHeight={['large', 'biggest']}
откуда именования позаимствовал?

2023-06-28 18:11 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/faq.component.tsx
> +  <Box backgroundColor='background.faq' width='100%' margin='0 auto'>
нельзя использовать спец. символы в именовании пропсов и неймингов темы

2023-06-28 18:11 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/faq.component.tsx
> +            fontSize={['xl', 'biggest']}
что такое х1?

2023-06-28 18:11 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/faq.component.tsx
> +        borderColor='divider.second'
почему на бордере дивайдер? и почему second? не понимаю…

2023-06-28 18:11 UTC, TorinAsakura commented on landing/fragments/landing-navigation/src/navigation-list/navigation.list.ts
> +]
ты создаёшь проблемы для управления текстом данным подходом, тут ты императивно задаёшь стилизацию текста, в то время как это должно происходить из вне за счёт стилизации

2023-06-28 18:11 UTC, TorinAsakura commented on landing/fragments/landing-process/src/process.component.tsx
> +        if (index !== processList.length - 1) {
это огромный монолитный кусок, его нужно вынести в отдельный компонент, это очень плохая практика

2023-07-03 11:32 UTC, Mirved64 commented on landing/fragments/landing-faq/src/faq.component.tsx
> +  <Box backgroundColor='background.faq' width='100%' margin='0 auto'>
@TorinAsakura 

Прошу уточнить, как надо сделать. 
- Я создал ui/theme, создал файл colors.ts;
- В нём сделал объект colors, где есть поле (объект) background;
- Обращаюсь к этому полю в пропсе backgroundColor, а точнее к полю faq, в котором у меня забит цвет. 

Так же сделано в [примере сайта](https://github.com/torin-asakura/dream-team/blob/master/landing/fragments/landing-hero/src/landing-hero.component.tsx), в файле [colors.ts](https://github.com/torin-asakura/dream-team/blob/master/ui/theme/src/theme/colors.ts)

2023-07-03 13:16 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/faq.component.tsx
> +  <Box backgroundColor='background.faq' width='100%' margin='0 auto'>
Сорян, мой факап

2023-07-03 16:40 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +              <FormattedMessage id='coursesButtonDesctop' defaultMessage='Все материалы' />
опечатка в ud

2023-07-03 16:41 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +              id='coursesTextFirst'
старайся не привязываться к именованиям иначе через пару степов ты запутаешься - старайся приводить нейминги в соответствие с контекстом

2023-07-03 16:54 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +                      defaultMessage='Основы разработки'
вообще, defaultMessage стоит указывать только при наличии нескольких языков, а так как язык только один - достаточно указывать ID

2023-07-03 17:29 UTC, TorinAsakura requested changes
Вёрстка выполнена достаточно неряшливо. Множественное несоблюдение отступов, размеров, будто фигму вообще не смотрел, а делал на глаз.
![IMG_4298](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/7813b342-764b-4c76-b84d-c4f62b692686)

![IMG_4299](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/151e16ff-58d4-4040-bceb-e3cf66ddfd47)

![IMG_0152](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/88cb1489-d24d-4adc-98ac-6e39656e6e4c)

![IMG_0153](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/a49ac965-654d-492f-938e-db696b70ffd7)

![IMG_0154](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/8a32c4d7-f87e-4802-9b14-915f6d3e3c86)

![IMG_0156](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/03ae6297-7024-4e2f-ba45-9cefafd61fb3)

![Снимок экрана 2023-07-03 в 20 14 08](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/a8472288-97a1-48da-bba0-299a4b053e6e)

![IMG_0157](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/0bea8fb6-9964-40e3-bc0e-0aa777069265)

![Снимок экрана 2023-07-03 в 20 15 06](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/adebc2ea-1d95-4841-9cde-a90197d14a14)

![IMG_0158](https://github.com/atls-academy/Mirved64.github.io/assets/3940885/9af24daa-f8bf-4e63-a029-21d1369356a8)

2023-07-03 17:29 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/faq.component.tsx
> +                  <FormattedMessage id={`+ ${String(index)}`} defaultMessage='+' />
а вот это ОЧЕНЬ плохая практика подменять юникодом UI элементы, это критично

2023-07-03 17:29 UTC, TorinAsakura commented on landing/fragments/landing-process/src/process-list/process.list.ts
>    },
А это что вообще такое?

2023-07-03 17:29 UTC, TorinAsakura commented on landing/fragments/landing-process/src/process.component.tsx
>          if (index !== processList.length - 1) {
для таких вещей есть паттерн conditions, и, соответствующий компонент в нашей обширной библиотеке

2023-07-03 17:29 UTC, TorinAsakura commented on landing/fragments/landing-process/src/process.component.tsx
>                  <Box alignItems={['start', 'center']}>
а что за flexBasis без значений? не понимаю и зачем тебе понадобился отдельный див для выравнвания?
basis - это значение напрямую зависящее от дизайна, оно не выносится в переменные и в целом в среду, обрати внимание, на, любимые тобой примеры

2023-07-03 17:29 UTC, TorinAsakura commented on landing/fragments/landing-process/src/process.component.tsx
> +        if (index !== processList.length - 1) {
Это намеренное игнорирование или сделаем вид, что ты не заметил?

2023-07-03 17:29 UTC, TorinAsakura commented on landing/fragments/landing-technologies/package.json
> +  "name": "@landing/technologies-fragment",
именования лучше делать по следующему паттерну:
- @namespace/context-entity - в нашем случае это будет выглядеть примерно так: @langing/fragment-technologies

2023-07-03 17:29 UTC, TorinAsakura commented on ui/link/src/link.component.tsx
> +  const NextLinkRenderer: any = createNextLink(BaseLink)
any - хреновый паттерн как и null, уж лучше потребовать string, но, хотя бы знать, что это будет строка, а не эфемерный any

2023-07-04 10:15 UTC, Mirved64 commented
> Вёрстка выполнена достаточно неряшливо. Множественное несоблюдение отступов, размеров, будто фигму вообще не смотрел, а делал на глаз. ![IMG_4298](https://user-images.githubusercontent.com/3940885/250628638-7813b342-764b-4c76-b84d-c4f62b692686.png)
> 
> ![IMG_4299](https://user-images.githubusercontent.com/3940885/250628635-151e16ff-58d4-4040-bceb-e3cf66ddfd47.png)
> 

@TorinAsakura 

В макете отступы в секциях как у меня. На разрешениях 1920px и 375px верстал с помощью плагина PerfectPixel. 

На промежуточных разрешениях верстку поправлю.

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/b3733faa-a10a-408b-9c54-ad4a612de058)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/a6fa2206-3bcb-4f45-8de1-ea76d0c7bc2a)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/b42d889d-8c98-4321-9043-66f41ff7b9f4)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/0955960f-1609-4711-8e5a-3b80d1d720a1)

2023-07-04 10:23 UTC, Mirved64 commented on landing/fragments/landing-process/src/process.component.tsx
>                  <Box alignItems={['start', 'center']}>
@TorinAsakura 

Про значение `content` читал в этой [статье](https://developer.mozilla.org/ru/docs/Web/CSS/flex-basis).
`Content `в этом случае ключевое слово, а не переменная.

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/77da3cca-99bc-4286-82b0-8e923ffa0304)

Мне показалось, что это наоборот удачная фича во флексах.

2023-07-04 11:14 UTC, TorinAsakura commented
@Mirved64 Зачем тебе плагин? Бери все размеры из фигмы

2023-07-04 11:20 UTC, Mirved64 commented
> @Mirved64 Зачем тебе плагин? Бери все размеры из фигмы

@TorinAsakura 

Я и брал, а плагин для быстрого контроля верстки на разрешениях из макета. Т.е. задал отступы и размеры из макета, чекнул секцию, сразу видно если накосячил. Правда для других версий экрана не проверить. 

Уточните, пожалуйста, верстку делать адаптивной или отзывчивой (адаптивная + резиновая верстка)?

2023-07-04 11:21 UTC, TorinAsakura commented
@Mirved64 Для разрешений, не указанных в макете элемент не должен ломаться. Это простой ответ.

2023-07-06 23:38 UTC, TorinAsakura requested changes
Налицо явное непонимание семантической разметки и то, как должен строиться сайт. Будем продолжать

2023-07-06 23:38 UTC, TorinAsakura commented on landing/entrypoints/renderer/src/i18n/messages.ts
> -    faqCross: '+',
а почему у тебя папка называется i18n? ты разве его используешь? или я чего-то не понимаю?

2023-07-06 23:38 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/item/item.component.tsx
> +        <CrossIcon width='100%' height='100%' />
а что это за конструкция такая? это ты таким образом сделал размер для иконки?

2023-07-06 23:38 UTC, TorinAsakura commented on landing/fragments/landing-process/src/item/item.component.tsx
> +      <Box flexBasis={[23, 56]}>
почему тут бокс а не лэйаут?

2023-07-06 23:38 UTC, TorinAsakura commented on landing/fragments/landing-process/src/item/item.component.tsx
> +    <Box>
зачем тут пустой бокс?

2023-07-06 23:38 UTC, TorinAsakura commented on landing/fragments/landing-process/src/item/item.component.tsx
> +          <Box alignItems='center'>
объясни конструкцию

2023-07-06 23:38 UTC, TorinAsakura commented on landing/fragments/landing-process/src/process.component.tsx
> +          </Box>
объяснишь?

2023-07-06 23:42 UTC, TorinAsakura commented on landing/fragments/landing-process/src/process.component.tsx
>                  <Box alignItems={['start', 'center']}>
Удача никому не поможет. Наша задача - контроль каждого субатома приложения. Автоматические величины размазывают картину.

2023-07-06 23:43 UTC, TorinAsakura commented
Не надо запрашивать ревью до резрешения всех замечаний. У тебя ещё осталась пачка с прошлого раза.

2023-07-07 05:00 UTC, Mirved64 commented on landing/fragments/landing-process/src/process.component.tsx
> +          </Box>
> объяснишь?

@TorinAsakura 

Свойства maxWidth, maxHeight, width='auto', height='auto' делают изображение "эластичныйм". 
zIndex выводит на передний план по оси z. 
Свойства  margin='auto', top='0', left='0', bottom='0', right='0' позиционирует изображение по центру родительского блока, когда у блока изображения position='absolute'.

2023-07-07 05:39 UTC, Mirved64 commented on landing/fragments/landing-process/src/item/item.component.tsx
> +          <Box alignItems='center'>
@TorinAsakura 

лишнюю обертку сделал

2023-07-07 05:41 UTC, Mirved64 commented on landing/fragments/landing-faq/src/item/item.component.tsx
> +        <CrossIcon width='100%' height='100%' />
> а что это за конструкция такая? это ты таким образом сделал размер для иконки?

Да, задаем размер иконки размером родительского бокса

2023-07-07 11:50 UTC, Mirved64 commented on landing/fragments/landing-process/src/item/item.component.tsx
> +    <Box>
@TorinAsakura 

Я обернул содержимое в `Box`, чтобы у содержимого базис задавал ширину. Это я не правильно сделал?

2023-07-07 11:51 UTC, TorinAsakura commented on landing/fragments/landing-process/src/process.component.tsx
> +          </Box>
Зачем ты используешь тут абсолютное позиционирование?

2023-07-07 11:52 UTC, TorinAsakura commented on landing/fragments/landing-process/src/item/item.component.tsx
> +    <Box>
Конечно нет. Бокс - див, контейнер для стилизации. Размеры задаются через лэйаут, в редких случаях для этого может потребоваться бокс.

2023-07-07 11:52 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/item/item.component.tsx
> +        <CrossIcon width='100%' height='100%' />
А почему иконка у тебя зависит от родительского блока? Посмотри повнимательнее как мы с иконками работаем

2023-07-07 12:00 UTC, Mirved64 commented on landing/fragments/landing-process/src/process.component.tsx
> +          </Box>
@TorinAsakura 

тут изображение выбивается из потока документа, и я решил, что так будет проще его спозиционировать относительно блока с процессами

2023-07-07 12:03 UTC, TorinAsakura commented on landing/fragments/landing-process/src/process.component.tsx
> +          </Box>
> @TorinAsakura
> 
> тут изображение выбивается из потока документа, и я решил, что так будет проще его спозиционировать относительно блока с процессами

а кто сказал, что нужно делать "проще"? Нужно делать, чтобы нормально работало. Абсолютное позиционирование заставляет делать на каждый пиксель корректировку. Что, будешь под каждое разрешение тьюнить отступы?

2023-07-07 12:18 UTC, Mirved64 commented on landing/fragments/landing-process/src/process.component.tsx
> +          </Box>
@TorinAsakura 

Мне думалось свойства: 
```
margin='auto'
top='0'
left='0'
bottom='0'
right='0'
```
автоматически помещают изображение в центр блока родителя.
Буду искать другой способ

2023-07-07 12:20 UTC, TorinAsakura commented on landing/fragments/landing-process/src/process.component.tsx
> +          </Box>
Ты можешь так сделать, если это будет работать. Проверь на других разрешениях и посмотри сколько тебе нужно будет сделать телодвижений.

2023-07-07 12:41 UTC, Mirved64 commented on landing/fragments/landing-process/src/process.component.tsx
> +          </Box>
@TorinAsakura 

Код не менял. Изображение на разных разрешениях. Квадрат в центре блока родителя.
По моему мнению, работает

![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/84ecee11-8cd6-4424-b1db-a801ee0819e1)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/72fc0783-3629-4c0a-8bbc-dfa8f833ced5)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/d82878ed-727e-4778-9a43-37fc09456503)
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/92d7dea5-48f2-464e-ae75-2a4a850b9506)

2023-07-08 15:55 UTC, Mirved64 commented on landing/fragments/landing-faq/src/item/item.component.tsx
> +        <CrossIcon width='100%' height='100%' />
@TorinAsakura 

**Скоуп**
Размеры иконок на разных разрешениях

**Описание**
Не могу задать размеры `svg` элементам в виде массива чисел или строк, как для других элементов.
Это приводит к увеличению кода для иконок с разными размерами на разных разрешениях (например иконка логотипа и иконка креста в секции вопросы)

**Вопрос**
В такой ситуации лучше задавать размеры блоку обертке `svg` элемента или дублировать код?

2023-07-10 12:40 UTC, TorinAsakura requested changes
Box и Layout являются компонентами, которые обеспечивают удобные пропсы для стилизации и разметки. Они оба являются частью набора компонентов @rebass/grid, который использует styled-system для создания гибких компонентов сетки.

Box - это базовый компонент, который может принимать любые пропсы стиля, предоставляемые styled-system. Это делает его очень гибким для использования в качестве обертки или контейнера для других компонентов.

Layout, с другой стороны, является более специализированным компонентом, который предназначен для управления разметкой страницы. Он может принимать пропсы, такие как width, height, display, space, color и flexbox, что позволяет управлять расположением и стилизацией дочерних элементов.

В общем контексте вёрстки, "box" и "layout" обычно относятся к двум различным аспектам дизайна. "Box" обычно относится к отдельным элементам или компонентам на странице, в то время как "layout" относится к общей структуре или схеме страницы.

Исходя из того, что ты опять всё попереименовывал - ты не понял ничего.

2023-07-10 23:39 UTC, TorinAsakura requested changes

2023-07-10 23:39 UTC, TorinAsakura commented on landing/fragments/landing-about/src/about.component.tsx
> +          <Box display='inline'>
зачем ты используешь преобразование в потоковый объект? Зачем тебе тут инлайн?

2023-07-10 23:39 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/item/item.component.tsx
>    <Column height='100%'>
опять, зачем ты ставишь высоту 100%? Используй флексы

2023-07-10 23:39 UTC, TorinAsakura commented on landing/fragments/landing-faq/src/item/item.component.tsx
> +      <Box display={['none', 'flex']} alignItems='center'>
ты же понимаешь, что тут не будут работать обе директивы? Почитай про свойство alignItems, пожалуйста и больше не делай так

2023-07-10 23:39 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/hero.component.tsx
> +            <Box flexShrink='1'>
зачем тебе тут шринки?

2023-07-11 13:39 UTC, TorinAsakura requested changes

2023-07-11 13:39 UTC, TorinAsakura commented on landing/fragments/landing-about/src/about.component.tsx
> +        <Box display={['none', 'block']}>
как у тебя может быть display=block, когда у тебя box имеет display=flex, что вообще происходит?

2023-07-11 13:39 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/hero.component.tsx
> +          <Row flexWrap='wrap'>
зачем тебе тут врап?

2023-07-11 14:33 UTC, Mirved64 commented on landing/fragments/landing-about/src/about.component.tsx
> +        <Box display={['none', 'block']}>
@TorinAsakura 

Если поставить `display=flex`, то дочерние блоки (флекс-элементы) выстроятся не так, как нужно по макету. 
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/2e1ebbb9-feb8-48d7-89a1-3b94cbc63a43)

2023-07-11 14:40 UTC, Mirved64 commented on landing/fragments/landing-hero/src/hero.component.tsx
> +          <Row flexWrap='wrap'>
@TorinAsakura 

Что бы при уменьшении разрешения экрана, `Row`, при переполнении, переносил дочерние элементы (их там три: блок с текстом, элемент `Space` и блок с текстом).
![image](https://github.com/atls-academy/Mirved64.github.io/assets/99605124/19155417-642e-4dce-bc7a-148173d89cf6)

2023-07-11 14:53 UTC, TorinAsakura commented on landing/fragments/landing-about/src/about.component.tsx
> +        <Box display={['none', 'block']}>
ну так ты сделай направляющий ёкарный-ты-бабай! Роу или коламн, что тебе там надо да и всё!

2023-07-11 17:17 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/hero.component.tsx
> +          <Row flexWrap='wrap'>
А посмотри, в каком состоянии свойство flexWrap находится по умолчанию, пожалуйста

2023-07-11 17:23 UTC, TorinAsakura requested changes

2023-07-11 17:23 UTC, TorinAsakura commented on landing/fragments/landing-about/src/about.component.tsx
>            <Box display='inline'>
зачем тут-то инлайн?

2023-07-11 17:23 UTC, TorinAsakura commented on landing/fragments/landing-about/src/about.component.tsx
>                display='inline'
и тут

2023-07-11 17:23 UTC, TorinAsakura commented on landing/fragments/landing-courses/src/courses.component.tsx
> +              <FormattedMessage id='coursesTitle' defaultMessage='Курсы' description='Курсы' />
я уже писал ранее, что defaultMessage резонно устанавливать при наличии других языков

2023-07-11 17:23 UTC, TorinAsakura commented on landing/fragments/landing-hero/src/hero.component.tsx
> +      <Layout flexBasis={[20, 230]} flexShrink='0' />
скажи, если убрать шринк у потомка и при этом оставить у родителя, как будет работать сокращение?

2023-07-11 17:43 UTC, Mirved64 commented on landing/fragments/landing-hero/src/hero.component.tsx
> +          <Row flexWrap='wrap'>
По умолчанию в `nowrap`. Чекнул свойства `Box`, `Row` и `Column` в библиотеке, там не указан `flexWrap`, значит `nowrap`

2023-07-12 05:21 UTC, Mirved64 commented on landing/fragments/landing-hero/src/hero.component.tsx
> +      <Layout flexBasis={[20, 230]} flexShrink='0' />
В этом месте я хотел указать, что `Row` может сжиматься, но за счет сжимания `Column`, а `Layout`ы сжиматься не должны

2023-07-13 13:37 UTC, TorinAsakura approved these changes

2023-07-13 13:38 UTC, merged